


* Ref
ISI Proceedings

IEEE conference Proceedings

www.nstl.gov.cn/index.html

AIP conference Proceddings

www.meeting.edu.cn

www.allconferences.com
* conference index
is it scopus indexed


* Fluid Mechanics related research centers

    Institute of Aerodynamics, RWTH Aachen University
    The Fluid Dynamics Research Center (FDRC), Chicago
    Thermo-fluid Mechanics Research Centre, UK

* Conferences on fluids, CFD

Experimental Fluid Mechanics 2014


International Conference on Mechanical Engineering and Mechatronics


International Conference on heat Transfer and Fluid Flow

IMA Conference on Mathematical Modelling of Fluid Systems


International Conference on Modeling Fluid Flow

Offshore Energy Exhibition & Conference 2018

7th International Conference on Ocean Energy 2018

Eleventh International Symposium on Turbulence and Shear Flow Phenomena (TSFP11)

AIAA Computational Fluid Dynamics Conference 

European Wave and Tidal Energy Conference

European Conference on Computational Fluid Dynamics

World Congress on Computational Mechanics

** ref
https://www.omicsonline.org/fluid-mechanics-journals-conferences-list.php

[[https://ukfluidsconference2018.weebly.com/contact.html][uk fluids conference]]




* Workshops
6th AIAA CFD Drag Prediction Workshop

6th Oxford Tidal Energy Workshop

Summer School on “Interscale Interactions in Fluid Mechanics and Beyond” Imperial College
  + Ugo Piomelli, Queen's University, Canada
sublilter-scale modelling for LES
* Ranking
https://aminer.org/ranks/conf
https://conferencealerts.com/

* Feedback from QMUL Symposium


Suggestions to Phd students on their research
1, the student should have a clear understanding of the state-of-the-art of their research topic, the novel contribution of their project, how their new results contribute to advance science and technology, and potential impact of the project.
2, Some projects from the engineering students were presented as research which could be done by industry, while PhDs should have a strong focus on science. In many cases this is an issue of presentation of the results, other than the way the research is carried out. 
3, Students should always ask themselves: “what are the fundamental challenges in my field?”, and focus on those challenges other than exploring all possible routes.

Suggestions to Phd students on their presentation
1, Presentations must contain information about state of the art, students must include references to relevant work
2, Students should present themselves professionally: speaking less colloquially and maybe dress also more appropriately for a formal academic setting, sufficient eye-contact with the audience 
3, make sure to include scale bars, have all fonts above 14 or 16, have references properly included underneath the specific graph/image
4, Students should ask questions
5, All students should attend the event: this is hugely important to their research development in many aspects.  

* The World Congress on Engineering WCE 2018

Registration number:  WCE2018_1523613654
WCE2018_1523874920

http://www.iaeng.org/WCE2018/enquiry.html
WCE 2018 Paper Number: ICME_57
Paper Title: The surface curvature effect on performance of a laboratory scale tidal turbine


	


** The presentations in each time slot
The 2018 International Conference of Mechanical Engineering ( ICME )
	
ICME I [ Day One ( *14:00 - 15:45* ) at Seminar Room A ]
Comparative Mechanical Microscopy of Mn-Ni-Co 4:1:1 Li-Ion Battery Cathodes
	Dr. Alexander Korsunsky

The Observation and Interpretation of Crack Closure under Plain Fatigue Conditions
	Dr. Alexander Korsunsky

On Diatom Colonization of Porous UHMWPE Scaffolds
	Dr. Alexander Korsunsky

On the Microstructure Size Effect in SLS-built 316L Stainless Steel Parts
	Dr. Alexander Korsunsky

*The Performance of a Vertical Axis Wind Turbine with Camber and Tubercle Leading Edge as Blade Passive Motion Controls*
	Mr. Ian Carlo Lositano

A Simple Approximate Method for Predicting Impact Force History and Application to Pyroshock Simulation
	Mr. Mun-Guk Kim

ICME II [ Day One ( 16:15 - 18:00 ) at Seminar Room A ]
Corners Restrictions and its Application in the Analysis of Thin Plates by the Boundary Element Method
	Prof. Joao Paiva

Experimental Investigation of the Ground Coupled Heat Exchanger System under the Climatic Conditions of Sahiwal, Pakistan
	Dr. Hafiz Muhammad Ali

Integrated DLM-COPRAS Method in Materials Selection of Laminated Glass Interlayer for a Fuel-Efficient Concept Vehicle
	Mr. Mark Vincent Manalo

Frost Measurement Methods for Demand Defrost Control Systems: A Review
	Mr. Martim Aguiar

Semi-analytical Solution for Postbuckling Behavior of Highly Deformable Nanobeams
	Prof. S. Ahmad Fazelzadeh

ICME III [ Day Two ( 11:15 - 13:00 ) at Seminar Room A ]
Design and Off-Design Operation and Performance Analysis of a Gas Turbine
	Dr. Abdulkarim Nasir

VAWT Cluster Parameter Study on Overall Cluster Performance, Part II: Oblique Angles and Direction of Rotation
	Dr. Louis Angelo Danao

Multiple Jet Impingement in Reflow Soldering -a Numerical Approach
	Miss FLAVIA BARBOSA

A Study on the Behavioral Characteristics of Traditional Timber House under Lateral Loads
	Mr. Bum-Soo Park

Design Solutions for Human Legs Motion Assistance Exoskeletons
	Dr. Geonea Ionut Daniel

The Interaction between a Surface Nonuniform Foundation and a Regular System of Punches with Rough Bases
	Dr. Dmitry Parshin

ICME IV [ Day Two ( 14:00 - 15:45 ) at Seminar Room A ]
Structural Performance of CFRP Confined Circular Concrete Columns
	Prof. Nasr-Eddine Chikh
Numerical and Experimental Assessment of the Performance of Wearable Airbags for Motorcycle Riders
	Mr. Edoardo Marconi

*Design and Implementation of 0.5kw Horizontal Axis Wind Turbine for Domestic Use*
	Mrs. Imhade Okokpujie

VAWT Cluster Parameter Study on Overall Cluster Performance, Part I: Model Development and Rotor Spacing
	Mr. Jeffrey Silva

Sample-Free Measurement of Linear Thermal Expansion Coefficient of Aluminum-Matrix Composites Using Speckle-Interferometry Method
	Dr. Evgenii Murashkin

Comparison of Experimental Data and Isotropic Sky Models for Global Solar Radiation Estimation in Eastern Nigeria
	Dr. PAUL AMAECHI OZOR

ICME V [ Day Two ( 16:15 - 18:00 ) at Seminar Room A ]
*The Influence of Unsteady Flow to the Performance of a Horizontal Axis Tidal Turbine*
	Dr. Binoe Abuan

Numerical Analysis of LM MHD Flows in Splitting Ducts under a Uniform Magnetic Field
	Miss YANG LUO

Mechanical Modelling of AM Processes for Centrifugal Deposition of Viscoelastic Material Layers on a Cylindrical Mold
	Dr. Dmitry Parshin

Studies on Properties of Al-SiC Metal Matrix Composite Material for Making IC Engine Valves
	Mr. Nilamkumar Patel

Effects of Process Parameters on Vibration Frequency in Turning Operations of Perspex Material
	Mrs. Imhade Okokpujie

ICME VI [ Day *Three* ( 9:00 - 10:45 ) at Seminar Room A ]
Fatigue Life Prediction for Supersonic Aircraft Skin Panels Subjected to Acoustic Loading
	Mr. Eun-Su Go

Overrunning Clutches in Designs of Inertial Continuously Variable Transmissions
	Dr. Sergei Aliukov
Characterization of Sewage Treatment Plant in an Emerging Territory
	Dr. PAUL AMAECHI OZOR

*Surface Curvature Effects on Performance of a Laboratory Scale Tidal Turbine*
	Mr. Kaiming Ai

Techno-Economic Analysis of NERC's Feed-in-Tariff for Sustained Grid-Connected Renewable Power Supply: Case of 3 Selected Sites of Northern Nigeria
	Prof. Oluseyi Ajayi

Analysis of Die Tilt Effect on the Stress Distribution in a Small Outline Transistor Using Finite Element Method
	Ms. Jennifer Fabular

ICME VII [ Day Three ( 11:15 - 13:00 ) at Seminar Room A ]
Residual Stresses Computing in Blood Vessels in virtue of Pathological Growth Processes
	Mr. Nikita Stadnik

A FMECA-Based Analysis of the Complex Plant Controlling a Variable Pitch Propeller
	Dr. Revetria Roberto

Experimental Investigation into the Effects of Al-composite Nanolubricants on the Energy and Exergy Performance of Vapour Compression Refrigerator Compressor
	Prof. Oluseyi Ajayi

Investigation of the Effect of Varying Silicon Die Size and Thickness on a Small Outline Transistor on the Silicon Die Crack Using Finite Element Method
	Ms. Hannah Erika Ducusin

Simulation and Analysis of a Switched Reluctance Machine for Flywheel Replacement
	Mr. Daniel Cardoso

Structural Planning of Long-span Hanok Considering Lateral Loads
	Prof. Yeong-Min Kim

ICME VIII [ Day Three ( 14:00 - 15:45 ) at Seminar Room A ]
Multi Objective Optimization of Material Removal Rate and Tool Wear Rate in EDM Machining of Metal Matrix Composite using Firefly Algorithm
	Dr. Murali Krishna Chimata

Experimental Validation of Bridge Screening Method based on Vehicle Response Analysis
	Dr. Kyosuke Yamamoto

Experimental Study of Flow Boiling Heat Transfer in Spider Netted Microchannel for Chip Cooling
	Prof. Pingan Du

Development of a Design Tool for a Two-Degree of Freedom Gear Train with Sun-Planet-Planet-Sun Configuration
	Prof. Ralph Jose

Thermal Residual Stresses Computing in Elastic-Plastic Ball with Rigid Inclusion under Heat Treatments
	Dr. Evgenii Murashkin

Kinetic Modelling for Tar Evolution and Formation in a Downdraft Gasifier
	Mr. Ahmed Salem

ICME IX [ Day Three ( 16:15 - 18:00 ) at Seminar Room A ]
A Review of System Dynamics Models Applied in Social and Humanitarian Researches
	Dr. Revetria Roberto
A Consolidated Economic Analysis of Alternative Fuel for Public Utility Jeepneys
	Prof. Jose Gabriel Mercado
Forming Analysis for the Thickness and Diameter of the Bent Pipe Decreases Prediction
	Mr. Seong-hun Ha
The Link Between Roll and Steering Torque in Motorcycles
	Mr. Thomas Lane
Non-Conservative Stability Analysis of Hauger Types of Columns with Different Boundary Conditions
	Prof. S. Ahmad Fazelzadeh

Poster Session

A Parametric Study of the Effect of the Leading-Edge Tubercles Geometry on the Performance of Aeronautic Propeller using 
Computational Fluid Dynamics (CFD)
	Mr. Fahad Butt



** About Registration ****

Registration website: 
http://www.iaeng.org/WCE2018/registration.html

If bank transfer is used, a bank charge of USD 30 should be added to the fee. 
For details, please refer to Note (Only for bank transfer) in the registration 
website.


** About Camera-ready Paper *** 

You are advised to send it immediately once it is ready and at least THREE days
before the due. Usually, authors need to submit revised version more than once 
before it getting accepted as camera-ready version.

The details about the camera-ready paper format and templates are available at:
http://www.iaeng.org/WCE2018/publications.html#templates

Do not simply copy and paste the prepared content to the template. This method 
overrides the format of the given template and should not be used.

To ensure the correctness of the format, you are required to check your 
revised paper against the checklist available for download at
http://www.iaeng.org/publication/download/Checklist_camera-ready_general.pdf
**** checklist for camera ready paper


** About the Delay of Payment *** 

Please complete the registration (both online registration and payment confirmation) 
by the FINAL due so to include the paper in the proceedings in time. 

Suppose someone can make a promise that the payment will be made certainly, 
please send us a Late Payment Explanation Letter which includes the information below. 

-the reason for late payment,
-the registration number, and
-the last date the payment will be made
-the person and/or the organization who promise the late payment and the corresponding contact information

The registration number can be got after confirming the data input at the registration website 
http://www.iaeng.org/WCE2016/registration.html

Conditional promise or insufficient information will not be considered. 
We will inform you whether the late payment can be granted.

Suppose the late payment is granted, we will include the paper in the proceedings 
and there is no reversal. You need to settle the payment under any circumstance.

Please send us the Late Payment Explanation Letter immediately for our consideration. 
Otherwise, we cannot include your paper in the proceedings in time.


** Important Dates *** 
Camera-Ready Papers Due & Registration Deadline (FINAL): 18 April, 2018
WCE 2018: 4-6 July, 2018


** Submission Summary ***
The summary of submissions and accepted papers in WCE 2018 is as followed:
Total number of submissions received in WCE 2018: 528 
Total number of papers that have been accepted for WCE 2018: 269 
(Acceptance rate: 50.95%)


The titles and contact authors of submitted papers that have been reviewed and 
accepted (or accepted with minor revisions) for WCE 2018 are listed here:

titles_A_D:
http://www.iaeng.org/WCE2018/doc/titles_A_D.html

titles_E_N:
http://www.iaeng.org/WCE2018/doc/titles_E_N.html

titles_O_Others:
http://www.iaeng.org/WCE2018/doc/titles_O_Others.html

We are looking forward to your participation in the WCE 2018 and would 
like to express our warm welcome to you in advance.

WCE 2018 Organizing Committee
http://www.iaeng.org/WCE2018

** Email exchange
  The conference participants can collect the official payment receipt 
at our conference reception during the conference period.

  The same as our other conferences, most of our participants are eager to 
attend other sessions, besides making their own presentations. Thus it is very 
important to keep our program schedule up-to-date. If it happens that you 
cannot attend the conference personally due to various difficulties, please 
inform us at least one month before the conference. We would send the 
proceedings book by surface mail after the conference to only those 
participants who have informed us in advance.

  If you have a paper to present, please report to the session chair before 
the session starts. Please be punctual so that the session can run smoothly. 
The duration for each paper presentation is 15 - 20 minutes. Our equipment 
includes a LCD projector and a PC/notebook supporting CD-Rom and 
USB port connection. Participants are advised to load their presentation 
files into the PC/notebook before the presentation session (Participants are 
welcome to use their own notebooks as well).

  Participants who need to present a paper will be given a certificate of 
presentation, which means that the receiver has attended the congress and 
presented the paper, by the session chair after their presentations.
Participants who do not need to present any paper can collect a certificate 
of attendance in the reception counter.  


Important Dates:
WCE 2018: 4-6 July, 2018.

The details about the camera-ready paper format and templates
are available at:
http://www.iaeng.org/WCE2018/publications.html

The details about the accommodation are available at:
http://www.iaeng.org/WCE2018/travel.html

More details about the WCE invited lectures are available at:
http://www.iaeng.org/WCE2018/program.html

The program schedule will be available in our conference web 
page before the conference:
http://www.iaeng.org/WCE2018/program.html

  If you would like to receive the official invitation for the 
WCE 2018 by mail for your visa application etc., you are 
welcome to tell us. 
	

* UK Fluids Conference 2018


** the Marine Hydrodynamics Special Interest Group (UKFN)
Forcus:  hydrodynamics of Propellers and Turbines

200-word abstracts 
Deadline:  23 April 
Manchester on 4-6 September 2018

As we had agreed that this would be the best forum for our 
PhD students to interact with the SIG I hope you will all encourage your students working in marine hydrodynamics to submit abstracts.

 We can then decide what format of meeting/networking event we hold for the SIG at the UK Fluids Conference.

I am also keen to confirm a date for the third meeting of the SIG during the next couple of months.
 I will *circulate a doodle poll* to everyone tomorrow to establish the most convenient dates for people to attend. 



Therefore we would invite members to present their recent research in this area and
 we will invite relevant industry with experience in this area to join us to promote discussion regarding the key areas for future research.

I am happy to host the third meeting in Southampton again, however if anyone else would like to host this meeting please let me know.


** 2nd 

10:00-12:00 Academic SIG members

•         Summary of outcomes from previous meeting

•         Future outcomes from SIG activities

o   Mapping exercise of current marine hydro tools and techniques onto different applications

o   Working groups on key challenges

•         Future SIG activities
12:00-1300 Lunch (including Industrial Guests)
13:00-1530 Discussion session with Industry guests

•         Summary of the SIG for guests

•         Brief introduction from Industrial guests

o   How does their business relate to marine hydrodynamics

o   What are the current and future hydrodynamic challenges they face

•         Group Discussion

o   Shared areas of interest/ Key Research questions

o   Future collaborations/interactions
1530-1600 AoB and future actions

Please let me know if there are any other topics you would like to discuss.

So far I have the following people down as attending along with some industrial guests in the afternoon:

Joe Banks <J.Banks@soton.ac.uk<mailto:J.Banks@soton.ac.uk>>
Narakorn Srinil <Narakorn.Srinil@newcastle.ac.uk<mailto:Narakorn.Srinil@newcastle.ac.uk>>
Dominic Hudson <dominic@soton.ac.uk<mailto:dominic@soton.ac.uk>>
Gabe Weymouth <G.D.Weymouth@soton.ac.uk<mailto:G.D.Weymouth@soton.ac.uk>>
Richard Willden <richard.willden@eng.ox.ac.uk<mailto:richard.willden@eng.ox.ac.uk>>
Christopher Vogel <christopher.vogel@eng.ox.ac.uk<mailto:christopher.vogel@eng.ox.ac.uk>>
Ignazio Maria Viola <i.m.viola@ed.ac.uk<mailto:i.m.viola@ed.ac.uk>>
T.S. van den Bremer <ton.vandenbremer@ed.ac.uk<mailto:ton.vandenbremer@ed.ac.uk>>
Yigit Demirel <yigit.demirel@strath.ac.uk<mailto:yigit.demirel@strath.ac.uk>>
Gregory Payne <gregory.payne@strath.ac.uk<mailto:gregory.payne@strath.ac.uk>>
Lin, Zi <Zi.Lin@cranfield.ac.uk<mailto:Zi.Lin@cranfield.ac.uk>>
Anna Young <amy21@cam.ac.uk<mailto:amy21@cam.ac.uk>>

Please let me know if you are intending on coming but I have missed you off the list.

Best regards,

Joe


Dr Joe Banks
New Frontiers Fellow | Fluid Structure Interactions Group |Performance Sport Engineering Laboratory | Engineering and Environment |University of Southampton | SO16 7QF | +44 (0) 2380596625 |email:J.Banks@soton.ac.uk<mailto:J.Banks@soton.ac.uk>




From: Banks J.
Sent: 24 October 2017 18:04
To: VIOLA Ignazio Maria <I.M.Viola@ed.ac.uk<mailto:I.M.Viola@ed.ac.uk>>; Narakorn Srinil <Narakorn.Srinil@newcastle.ac.uk<mailto:Narakorn.Srinil@newcastle.ac.uk>>; Turnock S.R. <S.R.Turnock@soton.ac.uk<mailto:S.R.Turnock@soton.ac.uk>>; Hudson D.A. <dominic@soton.ac.uk<mailto:dominic@soton.ac.uk>>; Weymouth G.D. <G.D.Weymouth@soton.ac.uk<mailto:G.D.Weymouth@soton.ac.uk>>; Thomas, Giles <giles.thomas@ucl.ac.uk<mailto:giles.thomas@ucl.ac.uk>>; Swan, Chris <c.swan@imperial.ac.uk<mailto:c.swan@imperial.ac.uk>>; Thomas Adcock <thomas.adcock@eng.ox.ac.uk<mailto:thomas.adcock@eng.ox.ac.uk>>; Richard Willden <richard.willden@eng.ox.ac.uk<mailto:richard.willden@eng.ox.ac.uk>>; Danielle Wain <D.J.Wain@bath.ac.uk<mailto:D.J.Wain@bath.ac.uk>>; VAN DEN BREMER Ton <Ton.VandenBremer@ed.ac.uk<mailto:Ton.VandenBremer@ed.ac.uk>>; Richard Pemberton <richard.pemberton@plymouth.ac.uk<mailto:richard.pemberton@plymouth.ac.uk>>; Atilla Incecik <atilla.incecik@strath.ac.uk<mailto:atilla.incecik@strath.ac.uk>>; Maurizio Collu <maurizio.collu@cranfield.ac.uk<mailto:maurizio.collu@cranfield.ac.uk>>; Dr Anna Young <amy21@cam.ac.uk<mailto:amy21@cam.ac.uk>>; Jun Zang <J.Zang@bath.ac.uk<mailto:J.Zang@bath.ac.uk>>; Nishino, Taka <t.nishino@cranfield.ac.uk<mailto:t.nishino@cranfield.ac.uk>>; Trarieux, Florent <F.Trarieux@cranfield.ac.uk<mailto:F.Trarieux@cranfield.ac.uk>>; Sandy Day <sandy.day@strath.ac.uk<mailto:sandy.day@strath.ac.uk>>; Klettner, Christian <ucemkle@ucl.ac.uk<mailto:ucemkle@ucl.ac.uk>>; Tahsin Tezdogan <tahsin.tezdogan@strath.ac.uk<mailto:tahsin.tezdogan@strath.ac.uk>>; Yigit Demirel <yigit.demirel@strath.ac.uk<mailto:yigit.demirel@strath.ac.uk>>; E Avital <e.avital@qmul.ac.uk<mailto:e.avital@qmul.ac.uk>>; Lorenzo Botto <l.botto@qmul.ac.uk<mailto:l.botto@qmul.ac.uk>>; JJR Williams <j.j.r.williams@qmul.ac.uk<mailto:j.j.r.williams@qmul.ac.uk>>; Taunton D.J. <djt2@soton.ac.uk<mailto:djt2@soton.ac.uk>>; Pablo Ouro Barba <OuroBarbaP@cardiff.ac.uk<mailto:OuroBarbaP@cardiff.ac.uk>>; Chaplin J.R. <J.R.Chaplin@soton.ac.uk<mailto:J.R.Chaplin@soton.ac.uk>>; p.f.linden@damtp.cam.ac.uk<mailto:p.f.linden@damtp.cam.ac.uk>; Christopher Vogel <christopher.vogel@eng.ox.ac.uk<mailto:christopher.vogel@eng.ox.ac.uk>>; Simon Neill <s.p.neill@bangor.ac.uk<mailto:s.p.neill@bangor.ac.uk>>
Subject: Re: 2nd meeting of the Marine Hydrodynamics Special Interest Group (UKFN) 28th Nov

Dear Marine Hydro SIG members,

As the date of our next meeting is fast approaching could I ask you all to confirm if you are planning to attend the meeting on Tuesday the 28th November in Edinburgh. This has been scheduled to follow on from the Annual Meeting of the UK Centre for Marine Energy Research<http://www.supergen-marine.org.uk/> in Edinburgh on Monday the 27th. It is our intention that we will provide dinner and accommodation on the Monday night for those that want it. Therefore, as part of your confirmation of attendance can you please specify if you want dinner and accommodation on the Monday night.

We are inviting industrial partners from the marine energy sector to join us for the afternoon of the 28th so please let us know if you have contacts in this area you would like to invite.

This would also be a good opportunity to engage some of the Naval architecture sector from this region so likewise please let us know if you have industrial contacts in this area that you would like to invite to join us.

I look forward to hearing from those of you that have not already replied shortly.

Many thanks,

Joe


Dr Joe Banks
New Frontiers Fellow | Fluid Structure Interactions Group |Performance Sport Engineering Laboratory | Engineering and Environment |University of Southampton | SO16 7QF | +44 (0) 2380596625 |email:J.Banks@soton.ac.uk<mailto:J.Banks@soton.ac.uk>



From: "Banks J." <J.Banks@soton.ac.uk<mailto:J.Banks@soton.ac.uk>>
Date: Monday, 14 August 2017 at 16:41
To: VIOLA Ignazio Maria <I.M.Viola@ed.ac.uk<mailto:I.M.Viola@ed.ac.uk>>, Narakorn Srinil <Narakorn.Srinil@newcastle.ac.uk<mailto:Narakorn.Srinil@newcastle.ac.uk>>, "Turnock S.R." <S.R.Turnock@soton.ac.uk<mailto:S.R.Turnock@soton.ac.uk>>, "Hudson D.A." <dominic@soton.ac.uk<mailto:dominic@soton.ac.uk>>, "Weymouth D." <G.D.Weymouth@soton.ac.uk<mailto:G.D.Weymouth@soton.ac.uk>>, "Thomas, Giles" <giles.thomas@ucl.ac.uk<mailto:giles.thomas@ucl.ac.uk>>, "Swan, Chris" <c.swan@imperial.ac.uk<mailto:c.swan@imperial.ac.uk>>, Thomas Adcock <thomas.adcock@eng.ox.ac.uk<mailto:thomas.adcock@eng.ox.ac.uk>>, Richard Willden <richard.willden@eng.ox.ac.uk<mailto:richard.willden@eng.ox.ac.uk>>, Danielle Wain <D.J.Wain@bath.ac.uk<mailto:D.J.Wain@bath.ac.uk>>, VAN DEN BREMER Ton <Ton.VandenBremer@ed.ac.uk<mailto:Ton.VandenBremer@ed.ac.uk>>, Richard Pemberton <richard.pemberton@plymouth.ac.uk<mailto:richard.pemberton@plymouth.ac.uk>>, Atilla Incecik <atilla.incecik@strath.ac.uk<mailto:atilla.incecik@strath.ac.uk>>, Maurizio Collu <maurizio.collu@cranfield.ac.uk<mailto:maurizio.collu@cranfield.ac.uk>>, Dr Anna Young <amy21@cam.ac.uk<mailto:amy21@cam.ac.uk>>, Jun Zang <J.Zang@bath.ac.uk<mailto:J.Zang@bath.ac.uk>>, "Nishino, Taka" <t.nishino@cranfield.ac.uk<mailto:t.nishino@cranfield.ac.uk>>, "Trarieux, Florent" <F.Trarieux@cranfield.ac.uk<mailto:F.Trarieux@cranfield.ac.uk>>, Sandy Day <sandy.day@strath.ac.uk<mailto:sandy.day@strath.ac.uk>>, "Klettner, Christian" <ucemkle@ucl.ac.uk<mailto:ucemkle@ucl.ac.uk>>, Tahsin Tezdogan <tahsin.tezdogan@strath.ac.uk<mailto:tahsin.tezdogan@strath.ac.uk>>, Yigit Demirel <yigit.demirel@strath.ac.uk<mailto:yigit.demirel@strath.ac.uk>>, E Avital <e.avital@qmul.ac.uk<mailto:e.avital@qmul.ac.uk>>, Lorenzo Botto <l.botto@qmul.ac.uk<mailto:l.botto@qmul.ac.uk>>, JJR Williams <j.j.r.williams@qmul.ac.uk<mailto:j.j.r.williams@qmul.ac.uk>>, "Taunton D.J." <djt2@soton.ac.uk<mailto:djt2@soton.ac.uk>>, Pablo Ouro Barba <OuroBarbaP@cardiff.ac.uk<mailto:OuroBarbaP@cardiff.ac.uk>>, "Chaplin J.R." <J.R.Chaplin@soton.ac.uk<mailto:J.R.Chaplin@soton.ac.uk>>, "p.f.linden@damtp.cam.ac.uk<mailto:p.f.linden@damtp.cam.ac.uk>" <p.f.linden@damtp.cam.ac.uk<mailto:p.f.linden@damtp.cam.ac.uk>>
Subject: RE: 2nd meeting of the Marine Hydrodynamics Special Interest Group (UKFN)

Dear Ignazio/All,

Thank you for confirming the proposed date and for offering to host the 2nd SIG meeting in Edinburgh. I think this provides an excellent opportunity to involve the tidal energy sector.

Please can you all let myself and Ignazio know if you will be able to attend on the 28th November.

Many thanks,

Joe


Dr Joe Banks
New Frontiers Fellow | Fluid Structure Interactions Group |Performance Sport Engineering Laboratory | Engineering and Environment |University of Southampton | SO16 7QF | +44 (0) 2380596625 |email:J.Banks@soton.ac.uk<mailto:J.Banks@soton.ac.uk>



From: VIOLA Ignazio Maria [mailto:I.M.Viola@ed.ac.uk]
Sent: 14 August 2017 14:31
To: Banks J. <J.Banks@soton.ac.uk<mailto:J.Banks@soton.ac.uk>>; Narakorn Srinil <Narakorn.Srinil@newcastle.ac.uk<mailto:Narakorn.Srinil@newcastle.ac.uk>>; Turnock S.R. <S.R.Turnock@soton.ac.uk<mailto:S.R.Turnock@soton.ac.uk>>; Hudson D.A. <dominic@soton.ac.uk<mailto:dominic@soton.ac.uk>>; Weymouth G.D. <G.D.Weymouth@soton.ac.uk<mailto:G.D.Weymouth@soton.ac.uk>>; Thomas, Giles <giles.thomas@ucl.ac.uk<mailto:giles.thomas@ucl.ac.uk>>; Swan, Chris <c.swan@imperial.ac.uk<mailto:c.swan@imperial.ac.uk>>; Thomas Adcock <thomas.adcock@eng.ox.ac.uk<mailto:thomas.adcock@eng.ox.ac.uk>>; Richard Willden <richard.willden@eng.ox.ac.uk<mailto:richard.willden@eng.ox.ac.uk>>; Danielle Wain <D.J.Wain@bath.ac.uk<mailto:D.J.Wain@bath.ac.uk>>; VAN DEN BREMER Ton <Ton.VandenBremer@ed.ac.uk<mailto:Ton.VandenBremer@ed.ac.uk>>; Richard Pemberton <richard.pemberton@plymouth.ac.uk<mailto:richard.pemberton@plymouth.ac.uk>>; Atilla Incecik <atilla.incecik@strath.ac.uk<mailto:atilla.incecik@strath.ac.uk>>; Maurizio Collu <maurizio.collu@cranfield.ac.uk<mailto:maurizio.collu@cranfield.ac.uk>>; Dr Anna Young <amy21@cam.ac.uk<mailto:amy21@cam.ac.uk>>; Jun Zang <J.Zang@bath.ac.uk<mailto:J.Zang@bath.ac.uk>>; Nishino, Taka <t.nishino@cranfield.ac.uk<mailto:t.nishino@cranfield.ac.uk>>; Trarieux, Florent <F.Trarieux@cranfield.ac.uk<mailto:F.Trarieux@cranfield.ac.uk>>; Sandy Day <sandy.day@strath.ac.uk<mailto:sandy.day@strath.ac.uk>>; Klettner, Christian <ucemkle@ucl.ac.uk<mailto:ucemkle@ucl.ac.uk>>; Tahsin Tezdogan <tahsin.tezdogan@strath.ac.uk<mailto:tahsin.tezdogan@strath.ac.uk>>; Yigit Demirel <yigit.demirel@strath.ac.uk<mailto:yigit.demirel@strath.ac.uk>>; E Avital <e.avital@qmul.ac.uk<mailto:e.avital@qmul.ac.uk>>; Lorenzo Botto <l.botto@qmul.ac.uk<mailto:l.botto@qmul.ac.uk>>; JJR Williams <j.j.r.williams@qmul.ac.uk<mailto:j.j.r.williams@qmul.ac.uk>>; Taunton D.J. <djt2@soton.ac.uk<mailto:djt2@soton.ac.uk>>; Pablo Ouro Barba <OuroBarbaP@cardiff.ac.uk<mailto:OuroBarbaP@cardiff.ac.uk>>; Chaplin J.R. <J.R.Chaplin@soton.ac.uk<mailto:J.R.Chaplin@soton.ac.uk>>; p.f.linden@damtp.cam.ac.uk<mailto:p.f.linden@damtp.cam.ac.uk>
Subject: Re: 2nd meeting of the Marine Hydrodynamics Special Interest Group (UKFN)

Dear All,

I have just been told that the next Annual Meeting of the UK Centre for Marine Energy Research<http://www.supergen-marine.org.uk> will be held in Edinburgh on Monday 27th November 2017. The Wave Energy Scotland<http://www.waveenergyscotland.co.uk/> Conference will be held on the next day, 28th Nov.

If you and Jo wish, I will be delighted to invite you for a SIG meeting in Edinburgh on

Tuesday 28th November.

I look forward to hearing confirmation from Jo.

Best regards,
Ignazio
________________________
Dr Ignazio Maria Viola
Senior Lecturer
Institute for Energy Systems
School of Engineering
University of Edinburgh
www.homepages.ed.ac.uk/iviola<http://www.homepages.ed.ac.uk/iviola>


On 14 Aug 2017, at 13:59, Banks J. <J.Banks@soton.ac.uk<mailto:J.Banks@soton.ac.uk>> wrote:


I am aware that the UK Fluids Conference is almost upon us and we have not made any formal plans for our 2nd meeting.
 One of the key objectives of this meeting was to engage tidal energy industrial partners in a similar manor to when we met with contacts from Naval Architecture companies during our first meeting. I am aware that we will not be able to arrange this in time for the UK Fluid conference which starts on the 6th of September therefore I suggest our next main SIG meeting be moved to sometime during the Autumn. Ignazio has suggested that the SuperGen UK Centre for Marine Research usually hosts an annual meeting in November which attracts many industry partners, so this might be a possibility. Otherwise please let me know if you would be keen to host a meeting in your institution.

As for the UK fluids conference I will be attending and would like to arrange an informal catch up with any SIG members who also plan to attend. So please let me know if you will be there and on which days and I can make arrangements for this. Looking forward to the next UK Fluids conference we agreed that we would use this event in the future to bring together and interact with the PhD students working in marine hydrodynamics. I would hope therefore that we would aim to have some dedicated sessions and a social event at the conference next year.





