* Chicken wing
garlic juice + salt + minced chilli
seanson over night
preheat oven 10 minutes
1--15 minutes per side
1. 腌制：这一步是为了味道
2. 低温烤熟：这一步是为了内外都烤熟，在达成目的的同时要保住水分，干巴巴的肉不好吃
3. 高温靠脆：这一步更多是卖相和口感，把外面烤脆。

* food safety
how fresh is fresh food at the supermarket

From <http://www.dailymail.co.uk/news/article-1370130/Just-fresh-fresh-food-supermarket.html> 



New Zealand lamb, two month
British lamb, 3-4 weeks

Good beef should be three or even four weeks old before it reaches the shelves because the flavour and texture of the meat improves if it is hung

Sainsbury’s says it takes eight days for pork to get from the slaughterhouse to its shelves.  


Most popular sliced brands have preservatives and mould inhibitors such as calcium propionate and ascorbic acid. They may be baked using enzymes that don’t have to be declared on ingredients lists, so beware of labels that say ‘stays fresher longer’

much of our food is frozen, de-frosted and re-frozen, yet people rarely get ill.

Once upon a time, you could get fresh fruit juice only by squeezing it yourself

The cheapest — and least fresh — is ‘juice made from concentrate’

Preservatives are often added, and the resulting shelf life can be a year or more.

a chemical substance that is used to prevent things from decaying, for example food or wood

food that contains no artificial preservatives 

Reference:
USDA 
"Food Inc" documentary
美国食品药品监督管理局（FDA

From <https://www.zhihu.com/question/20297984> 

纪录片supplements&safety

From <https://www.zhihu.com/question/20297984> 

No dietary supplement

From <https://www.zhihu.com/question/20297984> 

http://www.pbs.org/wgbh/frontline/film/supplements-and-safety/



从事食品行业的人，绝不会吃哪些食品？
辣炒田螺的巡回演出


收拾剩菜的时候都要把盘子里没吃光的田螺收在同一个塑料盆里，晚上倒回酱田螺用的大锅



每个扇贝壳若无破碎，定被老板于夜间收走
扇贝肉都是散装冷冻而来，扇贝壳只是充当一下容器


一滴香、飘香剂、辣椒精


自制臭豆腐毛豆腐腐乳等常见的杂菌污染是会产生毒素的芽孢杆菌，比如蜡状芽孢菌，产气荚膜梭菌



不吃鸭血

From <https://www.zhihu.com/question/31092804> 

不吃毛肚，松花蛋，百叶，路边的麻辣烫，熟食，烧烤


地沟油：
、还算干净的，用屠宰场动物尸体制成
2、餐馆酒店的泔水制成
3、下水道

From <https://www.zhihu.com/question/31092804> 

日本政府高价回收后制作生物柴油

From <https://www.zhihu.com/question/31092804> 

商户们八仙过海，监管有心无力，基层惴惴不安，上头唯唯诺诺

From <https://www.zhihu.com/question/31092804> 

尽量少在外面吃饭

From <https://www.zhihu.com/question/31092804> 

现在杀牛已经不抹脖子了，一刀直插心脏，然后赶紧把接着温水的水管插进牛的心脏里，往里面灌温水，这样水就顺着牛的血液循环系统均匀的分布到全身

From <https://www.zhihu.com/question/31092804> 

火锅食材是化学原料使用得比较频繁的地方

From <https://www.zhihu.com/question/31092804> 

百叶，黄喉，蹄筋什么的，大多是碱发的，碱发就是说干货用碱水泡，碱水可以破坏食材的组织结构，从而让水分进入到食材内部，达到增加重量的目的，说穿了还是为了涨点称，多卖点钱

From <https://www.zhihu.com/question/31092804> 

全国那么多养殖狐狸或者貂的养殖场，那些狐狸和貂取完皮以后肉就扔了？你信吗

开火锅店的时候，卖过一段时间“羊肉汤锅”，那时间市面上卖羊肉汤锅的餐厅，熟羊肉的价格基本上都是70或者75一斤。我到现在都还记得，我第一次买了396块钱的羊肉回来，煮熟了以后一称，按75一斤卖的话，能卖出405块。你说怎么办吧，不掺假的话，我至少得卖150一斤才能保证我的毛利率，但是在别人都卖70的情况下我卖150，你觉得我能卖出去多少

水煮肉片为了能嫩一点，直接加“食粉”腌肉，“食粉”是厨师们给起的名字，其实就是刷厕所用的洁厕灵，用它的腐蚀性破坏猪肉的组织结构，让水分渗透进去，肉就变嫩了

From <https://www.zhihu.com/question/31092804> 
No 街头麻辣串
No 铁板鱿鱼
冰淇淋奶茶摊贩
熟食麻辣类
火腿类
饼干零食类

From <https://www.zhihu.com/question/31092804> 

泡面的问题在于营养单一，长期吃会营养不良，不存在添加剂滥用、过量，一包泡面就两三块，你还想吃那么多添加剂，想得美啊，添加剂不要钱啊

From <https://www.zhihu.com/question/31092804> 

奶茶产品和调味乳，其中的营养成分的确是不如纯牛奶

From <https://www.zhihu.com/question/31092804> 

速溶咖啡中的植脂末等含有反式脂肪酸，但是只有在大量摄入情况下才有风险，喝得不多没问题，但是能量挺高的

From <https://www.zhihu.com/question/31092804> 

有短保质期的就不买长保质期的，有冷藏的就不买常温的，售价低于实际该有价值的产品不买

From <https://www.zhihu.com/question/31092804> 

牛奶，不买四个月保质期的利乐包奶，买七天保质期的巴氏奶，例如乳酸菌，买需要冷藏的养乐多，而从来不会买常温的某些乳酸菌饮料，例如火腿肠，因为此类产品基本都是淀粉和某些下脚料肉做成的，严重低于实际成本，所以工作后这十几年没再吃过了

From <https://www.zhihu.com/question/31092804> 

大多数牛肉干都不是牛肉

From <https://www.zhihu.com/question/31092804> 

.红枣 核桃 杏仁等
多数新旧掺着卖

From <https://www.zhihu.com/question/31092804> 

鸡爪瓜子等零食
多数不知名小厂生产 多为临期产品

From <https://www.zhihu.com/question/31092804> 

绿色食品、无公害、纯手工都是 智商税！！！

From <https://www.zhihu.com/question/31092804> 

不吃任何果冻和带颜色的饮品

From <https://www.zhihu.com/question/31092804> 

街头卤牛肉

From <https://www.zhihu.com/question/31092804> 

所有特别辣特别麻的口味特别重食品和菜

From <https://www.zhihu.com/question/31092804> 

现在人的口味越来越重，卖的好的食品，生意好的饭店无一例外都是些重口味的，基本上麻辣咸甜占据着大部分的餐桌

From <https://www.zhihu.com/question/31092804> 

绝不喝任何高价矿泉水尤其是要自己出钱去买。
理由：那里面智商税太他妈高了

From <https://www.zhihu.com/question/31092804> 

Kfc
recommends
吮指原味鸡

From <https://www.zhihu.com/question/31092804> 
饮料可以在外面超市买可乐然后问前台面善妹子要一杯冰块
刚烤出的蛋挞
绝对不吃保健品,交不起智商税
蜂蜜：它就是一杯糖水
方便面本身是没有问题的，汉堡也没有问题，单一才是问题。这一餐中膳食纤维的量严重不足，如果煮方便面时加点蔬菜加个鸡蛋，吃汉堡时配个蔬菜沙拉，这样就做到了膳食平衡。

From <https://www.zhihu.com/question/31092804> 


在家自己煮火锅

菜市场的半成品
怎么说呢，不要吃，因为过程不可控。

From <https://www.zhihu.com/question/31092804> 

外面肉馅的东西（肉包子、狮子头等等

光明牛奶是含有增稠剂的。这个增稠剂是合法添加物

From <https://www.zhihu.com/question/31092804> 

基本上所有市面流通的酒都是勾兑的

饮料要少喝，最健康的就是白开水



麻辣烫、卤制品（周黑鸭、凤爪那种类型的）、烤鸭（烤的时候特别香的那种

From <https://www.zhihu.com/question/22593066> 

Bacon Expiration Date
(Unopened)	Refrigerator	Freezer
	Past Printed Date	Past Printed Date
Bacon lasts for	1-2 Weeks	6-8 Months
Bacon Bits last for	6 Months	6 Months
(Opened)	Refrigerator	Freezer
Fresh Bacon lasts for	1 Week	6 Months
Cooked Bacon lasts for	7-10 Days	6 Months
Bacon Bits last for	6 Weeks	6 Months

From <http://www.eatbydate.com/proteins/meats/bacon-shelf-life-expiration-date/> 

Reference:
	1. usda
http://www.efsa.europa.eu/

	2. Food Safety and Inspection Service (FSIS), USDA,US

From <https://www.fsis.usda.gov/wps/portal/informational/aboutfsis> 



** Freezing and Food Safety
You can freeze almost any food. Some exceptions are canned food or eggs in shells. However, once the food (such as a ham) is out of the can, you may freeze it.



From <https://www.fsis.usda.gov/wps/portal/fsis/topics/food-safety-education/get-answers/food-safety-fact-sheets/safe-food-handling/freezing-and-food-safety/CT_Index> 


Washing raw poultry, beef, pork, lamb, or veal before cooking
 it is not recommended. Bacteria in raw meat and poultry juices can be spread to other foods, utensils, and surfaces.

** Barbecue and Food Safety

From <https://www.fsis.usda.gov/wps/portal/fsis/topics/food-safety-education/get-answers/food-safety-fact-sheets/safe-food-handling/barbecue-and-food-safety/CT_Index> 

** Wild Fermentation
USDA microbiologist Fred Breidt

From <http://www.foodsafetynews.com/2014/03/fermenting-veggies-at-home-follow-food-safety-abcs/> 
Think foods such as cheese, yogurt, sauerkraut, kimchee, olives, salami, jerky and even bread. And think beverages such as wine and beer, not to mention coffee and hot chocolate. All of these — and many more — are examples of fermented foods.

the idea of fermenting our own food conjures up images of strange, iffy, and perhaps dangerous dishes



Historically, it was a way for people to preserve the harvest for the winter



What about food safety?



from a food-safety standpoint, fermented vegetables can be safer than raw vegetables.



Proper temperature is important. According to USDA, at temperatures between 70-75 degrees F, kraut will be fully fermented in about three to four weeks; at 60-65 degrees F, fermentation may take five to six weeks. At temperatures lower than 60 degrees F, kraut may not ferment, and, above 75 degrees F, kraut may become soft.



The correct level of salt to use varies with the food being fermented. It ranges from 2.25  percent (by volume) for sauerkraut to more than 13 percent for other food items. Again, tested recipes should be followed when it comes to the proper amount of salt to use.



fermented foods can be stored for up to three months, or longer, without losing their quality and good taste.



Fermented food needs to reach a pH level of 4.6 or lower (which indicates it is acidic enough to be safe). 



Breidt advises beginners to grate, chop or shred the vegetables they plan to ferment because vegetables such as carrots and beets are dense enough that it’s difficult for the lactic acid to get inside of them if they’re in big chunks. The more surface area, the better — and the safer.
However, he said that’s not the case with cucumbers, primarily because they’re about 90 percent water, which makes it easier for the lactic acid to penetrate them.



** Leftovers and Food Safety
Bacteria grow rapidly between the temperatures of 40° F and 140° F.

leftovers must be refrigerated within Within 2 hours. 

Cover leftovers, wrap them in airtight packaging, or seal them in storage containers.

Leftovers can be kept in the refrigerator for 3 to 4 days or frozen for 3 to 4 months

From <https://www.fsis.usda.gov/wps/portal/fsis/topics/food-safety-education/get-answers/food-safety-fact-sheets/safe-food-handling/leftovers-and-food-safety/CT_Index> 

Fresh meat no sausage
焯水可以去掉肉类中的嘌呤物质，这是尿酸高，痛风的罪魁祸首啊…

No dietary supplement
supplements&safety documentary

From <https://www.zhihu.com/question/20297984> 


Sources of toxic heavy metal
Mercury in fish
Lead in bone broth
Cadmium in cigarettes
Leeks: from Farm to Fork 

From <https://www.youtube.com/watch?v=4MI025_NiKE> 

http://www.howgrow.org/

Lamb and seafish
This is because sheep are less likely to experience the confined factory farm conditions other animals do

From <http://www.takepart.com/article/2013/04/22/eat-more-lamb/> 
freshwater fish will taste muddy

From <https://www.theguardian.com/lifeandstyle/wordofmouth/2011/jan/17/freshwater-fish-fight> 

13 Foods With Natural Umami

From <http://www.rd.com/food/recipes-cooking/13-foods-with-natural-umami/> 

Some fish is OK to thaw, while others are better when cooked straight from the freezer. 

From <http://www.cheatsheet.com/life/what-you-need-to-know-about-cooking-frozen-fish.html/?a=viewall> 

Cross contamination
	• Use separate refrigerators for raw meat and cooked/ready-to-eat foods where possible.
	
	• store raw meat in the bottom of a shared refrigerator below the cooked/ready-to-eat foods.
	• 
	http://www.foodstandards.gov.scot/sites/default/files/rshrcrosscontam.pdf





* tender meat
- add water/power/egg to wrap the meat
- tenderrizer
- reduce cook time

