#+SETUPFILE: theme-bigblow.setup
* TODO 提取保证金
	
10 working days

010-88395714
	

tqbzj@csc.edu.cn 
* DONE CSC 申请回国证明
contact teacher at UK ambausdar

** 个人留学总结
1. paper
2. conferences
3. workshops

4. skills

** 在线申请信息填写
 1. 回国日期：请按照确定的回国机票日期选择填写。 
2. 注册入学日期：非攻读学位类别人员，请按照在英正式进行学习、进修时间选择填写；攻读学位类别人员，请按照就读学校和专业正式开学时间选择填写；以上一般均应晚于实际抵英时间。 

3. 毕（结）业日期： 攻读学位类别人员，应按照取得学位证书上注明的颁发时间填写。

确需在获得学位证书前即申办证明的攻读学位人员，也可选择将留学单位主管部门出具的、可确认取得学位证明信的时间作为毕结业时间。 



4. 毕结业证书类别：请按照留学实际情况进行选择 
5. 毕业证书号码：非必填项，请根据实际情况填写或留空。


6. 取证明表方式：申请回邮留学证明人员，请选择“邮寄”；拟赴教育处领取或现场申办留学证明人员，请选择“自取”。 

7. 邮寄地址：可留空。 

8. 以往留学经历：可留空。 二、上传材料清单及要求 
a. 个人留学总结：需对完整留学期限内的工作进行回顾总结，本人签字。
b. 导师评语：对留学人员在英学习、进修情况的评价，需使用留学单位抬头信纸书写，导师签字；没有明确导师的，请留学专业课程协调人出具。 
c. 回国机票确认单：由指定机构通过电子邮件通知本人；因故放弃公费回国机票的人员，仍需事先登录信息平台并在“预订回国机票”模块内录入详细回国信息并提交自定回国机票确认单。 d
d. 学位证书：攻读学位类别人员须提供；或以在英留学单位主管部门出具、说明已完成学业且可获得既定学位的证明信。 
e. 退还生活费表格：需退还生活费人员提供；有规定格式，本人签字。 
f. 回邮快递单：申请回邮人员须提供，自取证明人员免交。上传材料请均使用PDF格式文件，每个文件不超过3MB。 


** 其他
 因提前回国或曾中途回国需要退还部分奖学金生活费的留学人员，
建议携带现金到教育处现场申办证明。
如以Postal Order（可在当地邮局购买）或银行转账方方式退还奖学金，教育处财务在确认入账后，方可办理证明。
办理Postal Order信息：收款人：Education Section，the Embassy of P. R. China；
邮寄地址：Education Section, The Embassy of P.R. China, 50 Portland Place, London, W1B 1NQ, UK。
办理银行转账信息： Bank Name: BANK OF CHINA (UK) LIMITED A/C Name: CHINESE EMBASSY EDUCATION DEPT A/C No : 13284550（domestic 英国境内汇款账户），100200100042913（international国际汇款账户） Sort Code: 405037

* account
akmkevin
 a@@1**8!**5

学号： 2014 0637 0178 

* Contacts 
** Contacts 

石 磊 一等秘书（片区：中东部地区、北威尔士地区及部分伦敦地区）

　　020-76120269，
shilei@edu-chineseembassy-uk.org

http://www.edu-chineseembassy-uk.org/publish/portal132/tab6665/





* 《国家公派留学人员预订回国机票说明》
* 回国手续
** 申办及开具《留学回国人员证明》
*** 在线申办

　　完成回国机票预订，并已收到指定机构的出票确认单后，留学人员可在线申办《留学回国人员证明》，同时上传下述材料：

　　①个人留学总结（本人签字）；

　　②导师评语（导师签字，使用留学单位抬头信纸）；

　　③指定机构提供的回国航班出票确认单（因故放弃公费回国机票的人员，
需登录信息平台并在“预订回国机票”模块内录入详细回国信息，并上传自定回国机票确认单）；

　　④在英留学单位出具的，已完成学业且可获得相应学位的证明信或学位证书复印件；

　　⑤留学人员退还生活费表格（须退还生活费人员提供，本人签字）；

　　⑥已付费并填写完整的回邮快递单（申请“邮寄证明”人员请上传付费后生成的快递单（快递服务：英国境内快递，英国至中国快递），自取证明人员无需上传）。

　　注：上传材料均为PDF格式，每个文件不能大于3MB。

　　教育处收到申请后对上传材料进行审核。留学人员可在线查看办理进度。申请被退回者，可点击“查看”按钮查询审核未通过原因，并选择“编辑”按钮在对应栏目补充上传材料，或对其他申办信息进行修正后重新提交。

　　中国科学院公派来英留学人员需通过“留学人员报到登记信息管理系统（http://hr.csc.edu.cn/commoner/uklogin）”提交办理证明申请并将申请材料寄/送至驻英使馆教育处；申请材料同国家公派留学人员。2018年8月15日以后，中国科学院公派来英留学人员将可通过该系统在线申办留学回国证明。

　
*** 证明领取

　　留学人员在线申请时，需在“取证明表方式”栏选择“快递回邮”或“自取”。证明领取方式一旦确定，将不予更改。

　　选择快递回邮留学回国证明人员，由教育处打印上传的快递单，并邮寄留学回国证明。
材料邮寄问题，请留学人员自行联系投递服务提供商（sto-express.co.uk，
教育处不负责查询投递结果。

　　选择 自取 留学回国证明人员，如系统显示“申请已通过”，可提前两周与管片老师预约，并在工作日办公时间（09:00-12:00,14:00-17:00）凭个人证件到教育处前台领取。

** 退还奖学金生活费

　　根据规定，应退还部分奖学金生活费的国家公派留学人员，需在取得《留学回国人员证明》 *前* 办理完成退费手续。

　　上述人员需事先按指定要求填写并提交《留学人员退还生活费表格》。
留学人员可选择回国前在教育处 *现场办理* *现金* 退费，亦可通过银行划转方式退费，并向管片老师提供相关汇款证明。
汇款确认收到后，方可办理相关回国手续。教育处银行账户信息如下：

　　(1) 英国本地汇款账户信息

　　A/C Name（开户名）: CHINESE EMBASSY EDUCATION DEPT

　　开户人地址： 50 Portland Place，W1B 1NQ，London，UK

　　A/C No （银行账号）:13284550

　　Sort Code: 405037

　　Bank Name（开户银行）: BANK OF CHINA (UK) LIMITED

　　开户行地址：1 Lothbury London，EC2R 7DB，UK

　　(2) 国际汇款账户信息

　　A/C Name（开户名）: CHINESE EMBASSY EDUCATION DEPT

　　开户人地址： 50 Portland Place，W1B 1NQ，London，UK

　　A/C No （银行账号）:

　　100200100042913

　　SWIFT Code（国际银行账号代码）:BKCHGB2UXXX

　　IBAN:GB10 BKCH 4050 3713 2845 50

　　Bank Name（开户银行）: BANK OF CHINA (UK) LIMITED

　　开户行地址：1 Lothbury London，EC2R 7DB，UK

　　接收币种：英镑

　　(3) 汇款留言均为退款人姓名全拼。

**  启程回国

　　留学人员按照既定回国时间和航班启程回国，联系国家留学基金管理委员会办理回国报到手续。
http://www.edu-chineseembassy-uk.org/publish/portal132/tab6713/info135176.htm

* 关于调整国家公派留学人员回国机票预订方式的通知
驻英使馆教育处将于2018年1月1日正式启用国家留学基金管理委员会“国家公派留学管理信息平台”
（http://apply.csc.edu.cn，以下简称“信息平台”）进行国家公派留学人员回国机票的预订申请与审核工作。现将有关事宜通知如下：

　　一、凡须由我处负责购买回国机票的国家公派留学人员，
请至少提前40天通过信息平台“预订回国机票”模块在线提交申请。管片老师将通过信息平台进行审核，并将有关信息推送至指定机构协助您完成机票预订，并同时通过指定电子邮箱（csc@csc.edu.cn）通知本人。我处不再通过电子邮件受理国家公派留学人员的回国机票预订申请。

　　二、请您在提交申请前仔细阅读信息平台关于《国家公派留学人员预订回国机票说明》，
并按要求提供相关信息。机票确认出票后，一般不予更改；有特殊情况确需修改的，须报管片老师批准，改票费由留学人员自理。
我处指定国家公派留学人员回国机票预订机构联系电话：020-73888838。

　　三、其他

　　1.因故拟放弃公费回国机票的国家公派留学人员，仍需登录信息平台并在“预订回国机票”模块内录入详细回国信息并提交我处备案。

　　2.中国科学院公派来英留学人员仍按原方式申请预订回国机票，以“回国机票预订”为题，通过电子邮件向管片老师提交《公派留学人员机票预订单》。

　　特此通知。

请您仔细阅读本说明并按以下要求录入预订回国机票信息。 
     一、乘机日期：请选择结束本次留学，拟回国的乘机日期。 
     二、选择航空公司/机票代理：需提供回国机票人员，请选择“China Travel”。 
     三、航班号：须预订国内航空公司机票（英国境内联程机票除外）；若涉及联程，请按照搭乘航班顺序填写完整航班号，并使用逗号分隔。
参考航班包括，但不限于：CA938或CA856、MU552、CZ304或CZ604、HU7904等。 
     四、是否需要国内联程机票：如有需要，请务必选择“是”；可提供部分国内航段免费联程机票，具体以订票公司答复为准。 
     五、国内目的地城市：请填写国内入境城市；如预订联程机票，请填写入境城市及最终目的地城市，如“北京-西安”。 
     六、取票方式：请选择“电子机票”。 
     七、邮寄地址、邮政编码：可不填。 
     八、24小时联系电话、预订机票电子信箱：请提供英国手机号码和常用电子邮箱（尽量避免使用QQ邮箱），以便订票公司及时与您联系。 
     九、需要托运行李件数：填写阿拉伯数字即可。通常为您订购的机票可以提供2件免费托运行李，如有额外需求，可能会产生部分费用。 
     十、护照签发地：请按所执护照相应内容填写，如“广东/GUANGDONG” 
     十一、备注说明：需要说明的其他事项。 
     十二、其他 
     1.预订机票时将自动使用您在系统内录入的姓名、拼音、护照号码及护照有效期等信息，如有变更，请务必在“备注说明”栏中注明。 
     2.放弃公派回国机票人员也须登记、提交相关信息，注明回国时间、航班信息等等，请在“选择航空公司/机票代理”栏选择“放弃公费回国机票”。

* 个人学习/研修情况总结
（请按以下提示撰写，最终制作成一个PDF文件上传） * 
   (1.本阶段学习和研修基本情况; 2.发表的论文及专利等科研成果; 3.参加学术活动情况; 4:接下来半年的研修计划) 
* ref
[[http://www.edu-chineseembassy-uk.org/publish/portal132/tab6664/][中国驻英国大使馆教育处]]

