* 苏志花
results: refused by She
location(home): sujia
institution: 东莞美熙伊美医疗美容门诊部有限公司
title: 总监
大股东:广东恩泽医院投资有限公司(including 华美 美莱)
address(地址)：东莞市南城街道鸿福社区元美路华凯广场C栋七楼701室

** CV:
中山大学第一附属医院
** attitudes:
以后我不打算做女强人，我不觉得一个靠女人支持整个家庭的男人能受到女人多少尊重

我希望我以后的老公可以支撑整个家庭

我也不想一直这样辛苦，我觉得女人还是以家庭为主，兼顾事业，看别人一家幸福，我也很羡慕

你要努力，我也努力，无能为力，就没办法，我也想有个男友在身边

不托尼带水，能就结，不能就不耽误，

只能做老师吗?

** requirements
annual income:  30W+

** house
area: 90 m^2

首付: 106W 

月供 4k+

period: 30 years
** 目标：1.副总，2. 30W的车， 3， 房子装修 4。 给爸妈在鹰谭买房

** Conclusions:

如果2020年过年前，你我都没找到对象，那么如果觉得彼此合适的话， 可以考虑看看
但目前的我们，是不是交往，太多客观因素，相信你也这么认为吧
在此期间，我可能不会和你交流太频繁，工作太忙碌
专心工作，2019 很多目标等我实现
那么如果，在此期间，有更好合适我们对方的，那么就彼此祝福，成为好朋友或者你说的姐弟


我大概考虑了一下，可能我们不太适合，更适合做朋友或姐弟，希望我们能找到彼此相伴一生的人


*  搭讪
无论说什么做什么，都记得只要是想认真谈恋爱在面对搭讪
者时想的都是：

- 这个人优秀吗？
- 这个人有在一起的可能吗？

所以，男生的任务就是去在短时间内尽可能解决这两个问题。
优秀是多方面的，但短暂的搭讪无法证明你的性格好坏，所以最好先证明自己学习/工作/能力不错。
比如哪个学校、哪个公司、什么职位。有无在一起的可能是，你是不是本地的，是在附近还是比较远，年龄差距大不大等等。

作者：YY Wu
链接：https://www.zhihu.com/question/28937890/answer/42964457

* air crew
flight crew
因为她在工作中，早就透支完了自己的情绪，在生活中已经没有太多的精力了。

让她们感觉到你尊重她们，而非想要拿她们炫耀
- 所以和她们相处的时候，你谈话的重点一定不能是她的工作
- 追空姐的过程中你就当成是你在追一个普通的女孩子
- 女生会喜欢哈巴狗, 但是不会和一个像哈巴狗一样的男人在一起

* blint dating
三十多岁的男性只会有2种选择，第一，年轻漂亮的女人，如果不漂亮那一定要年轻。第二，三十多岁家里有钱有权可以帮到男性事业的女人。
* dating
- confidence
- smile
where do girls go to kill time?
一笔简单的“财”“貌”交易：甲方提供迷人的外表，乙方出钱，公平交易，童叟无欺
你的美貌会消逝，但我的钱却不会无缘无故减少。事实上，我的收入很可能会逐年涕增，而你不可能一年比一年漂亮
对一件会加速贬值的物资，明智的选择是租赁，而不是购入。年薪能超过50万的人，当然都不是傻瓜，因此我们只会跟你交往，但不会跟你结婚。所以我劝你不要苦苦寻找嫁给有钱人的秘方。顺便说一句，你倒可以想办法把自己变成年薪50万的人，这比碰到一个有钱的傻瓜的胜算要大。

* topics with ladies
- 不要查户口！

在不确定妹子对你的好感度之前不要强撩。尤其是不要使用狗血的霸道总裁戏码！妹子还是喜欢被撩的，不过这建立在她对你已经有一定的好感和信任的情况下。强撩&给自己加戏只会让她接受无能，而且容易让她感到没有被尊重。
** 投资专家

** international dating
*** Social skills
- make lady laugh
- flirt/jokes
*** outlook
- muscle
- clothing
- hairstyle
- personal hygiene

*** financial status
- career
*** hobby
- sports
- dance
- music

* reference





https://www.zhihu.com/question/45621693
https://www.zhihu.com/question/25695608
https://www.zhihu.com/question/45621693
http://io9.gizmodo.com/the-best-way-to-recover-from-a-break-up-according-to-1684775462

* pick up line
yo baby, I know your feet must be tired. 
cause you been running through my mind all day!"﻿

 I'm lost, can I ask for direction? direction to your heart. 这样顺多了﻿
