应当选个什么样的女孩结婚？
两个人共同经营、共同努力、共同前进，去创造一个新的家庭
我建议你找个和你妈比较像的女孩子结婚

两个人的共同，不光是体现在思想上的，收入上的也是要共同。即你的收入至少能满足你妻子的消费水平

你们的观念要大致相同，你能满足她现实的要求(或者是她能接受你的现实状况)，对方和你都是能为一件事付出巨大代价的人，即不自我的人

一个好女孩必然是阳光热情热爱生活的，所以她的朋友圈肯定是覆盖小学同学、初中同学、大学同学、原来的同事的

能共同承担家庭中的责任和义务
 一般我建议不会做饭不会洗碗不会洗衣服不会扫地拖地不会叠衣服（只要满足其中一条）的女人，
还是不要考虑了。因为她在她原来的生活中没有学会一条道理：共同承担家庭中的责任和义务。所以她在未来的生活中，她也不会去承担家庭中的责任和义务，那么当你重病卧床不起的时候，她十有八九是会跑路走人的。

不要急于做决定，建议先同居再结婚
同居是能完完全全暴漏两个人的缺点的方法，如果这一关过了，那才能考虑结婚的话题。
很多时候，女人为了结婚而结婚，男人为了冲动而结婚

婚姻就如一杯白开水，没有味道但是舒适而解渴

如果你无法承受离婚的后果，那么请你不要开始一段婚姻。

作为一个伴侣的基本要求，说白了就两点，生理和心理。生理上你对她有感觉，至少你们在恋爱的时候你起码是会经常性的欲火焚身的，如果你这点都没有那就不用谈了更别说结婚了。心理上就是说你们至少能沟通，能交流，不是鸡同鸭讲
** summary
①你的经济收入能满足她的物质要求。
②你们两的三观接近。
③她不是个自我的人、愿意为他人而做出改变。
④她的父母和你得父母能聊的很投缘。
⑤她会做家务而且会去做家务。
⑥她的朋友圈是些什么样的人。
⑦在你和她同居后还想和她结婚的。
⑧能够达到一个伴侣的基本要求。

真正的爱，是接受，不是忍受；是支持，不是支配；是慰问，不是质问；真正的爱，要道谢也要道歉。要体贴，也要体谅。要认错，也好改错；真正的爱，不是彼此凝视，而是共同沿着同一方向望去。其实，爱不是寻找一个完美的人。而是，要学会用完美的眼光，欣赏一个并不完美的人。婚姻是两个人的事情，从来就不是一个人的事情。只有两个人共同努力，才会幸福

不自私，有分寸，有边界，不会干涉除了对方之外的任何家人朋友


链接：https://www.zhihu.com/question/19732277/answer/12793112
把你追到手只不过是真正努力的开始，他会一辈子通过努力给你更多惊喜的！
把对方追到手并不意味着努力的结束，而恰恰是真正努力的开始

找老公，强烈建议找一个具备积极建设性回应习惯的。他心底上为你的每一次进步高兴，即使你只是第一次做饭不再烧焦了，他鼓励你尝试而不是打击你自信。他会给你带来充满意义的生活，也会让你将来的孩子变得更加自信、热忱、勇敢并且富有创造力！
* 权威人格
权威人格的人具有强烈的等级观念，认为人生而有三六九等，他们一方面向“弱者”夸耀力量、呼三喝四、企图控制；另一方面对强者卑躬屈膝、表示服从、丧失自尊。
他潜意识里认为你是他的长期资产，而不是“平等而相爱的终身伴侣”，或许是因为性格使然，或许是因为他花了很多物质代价把你买过来（比如提供房子），因此他觉得自己对你有“处置权”，各种方面高你一等。他喜欢控制你，不喜欢你违背他的意志。比如不让你跟男性朋友联系，控制你的社交圈，不让你在公众场合多说话等等。可笑的是，他不让你跟男性联系，自己却跟很多女性保持联系。他忍受不了你反对他。如果你在他的朋友面前反对他的某个观点，他会异常生气，而这是种撕裂式的气氛，少不了回家找你麻烦。有时他也会呵护你，但是这种呵护并不是平等的爱，而是“皇帝对子民的恩泽”，还不赶紧跪舔？因为他迷信权威、卑躬屈膝，因此自尊体系非常不健康，经常被伤自尊，而在外面被伤自尊的结果就是回来吵你发脾气甚至打你



* Questions

1. 我们要不要孩子？如果要，主要由谁来负责？ 
2. 我们的家庭赚钱能力及目标是什么？ 消费观及储蓄观会不会发生冲突？ 
3. 我们的家庭如何维持？由谁来掌握可能出现的风险? 
4. 我们有没有详尽地交换过双方的疾病史？包括精神上的. 
5. 我们父母的态度有没有达到我们的预期？会不会给足够的祝福？ 
6. 我们有没有自然、坦诚地说出自己的性需求、性的偏好及恐惧？ 
7. 卧室能放电视机吗？ 
8. 我们真的能倾听对方诉说，并公平对待对方的想法和抱怨吗？ 
9. 我们清晰地了解对方的精神需求及信仰吗？我们讨论过孩子将来的信仰问题吗？
10. 我们喜欢并尊重对方的朋友吗？ 
11. 我们能不能看重并尊敬对方的父母？我们有没考虑到父母可能会干涉我们的关系？
12. 我的家庭最让你心烦的事情是什么？
 13. 我们永远不会因为婚姻放弃的东西是什么？
 14. 如果我们中的一人需要离开其家族所在地陪同另一个人到外地工作，做得到吗？
 15. 我们是不是充满信心面对任何挑战使婚姻一直往前走？
 原文：Relationship experts report that too many couples fail to ask each other critical questions before marrying. Here are a few key ones that couples should consider asking: 1) Have we discussed whether or not to have children, and if the answer is yes, who is going to be the primary care giver? 2) Do we have a clear idea of each other’s financial obligations and goals, and do our ideas about spending and saving mesh?3) Have we discussed our expectations for how the household will be maintained, and are we in agreement on who will manage the chores?4) Have we fully disclosed our health histories, both physical and mental? 5) Is my partner affectionate to the degree that I expect?6) Can we comfortably and openly discuss our sexual needs, preferences and fears? 7) Will there be a television in the bedroom?8) Do we truly listen to each other and fairly consider one another’s ideas and complaints? 9) Have we reached a clear understanding of each other’s spiritual beliefs and needs, and have we discussed when and how our children will be exposed to religious/moral education?10) Do we like and respect each other’s friends?11) Do we value and respect each other’s parents, and is either of us concerned about whether the parents will interfere with the relationship?12) What does my family do that annoys you?13) Are there some things that you and I are NOT prepared to give up in the marriage?14) If one of us were to be offered a career opportunity in a location far from the other’s family, are we prepared to move?15) Does each of us feel fully confident in the other’s commitment to the marriage and believe that the bond can survive whatever challenges we may face?




