
* FAQ
** real estate 
转移地方政府和企业的杠杆到居民身上
** 怎样一步步地培养自己的理财能力？

- 风险可控的理财产品、基金、债券不超过8%的收益
- 理财永远只有锦上添花
- 低风险：国债、保险、存款、银行理财产品、货币基金
- 中低风险：债券型基金、基金定投
- 中等风险：股票型基金、P2P理财、信托理财、黄金、房地产
- 高风险：股票、外汇、期货、股权类投资

激进型：高风险45%，中等风险30%，中低和低风险20%，最后5%存款、货币基金保证流动性。

如果你13年甚至更早在一线城市和个别二线城市买了房，
恭喜你，你无论有没有理财都可以跑赢绝大多数没有买房的一般老百姓了（M2主要流向房地产）。
股市里面有一句名言：二级市场永远亏钱，一级市场永远赚钱。
https://www.zhihu.com/question/21855830/answer/101479873



最好把今年的理财目标定位5.5%以上

如果银行卖的 *理财产品* 就能跑赢及格线，那就只有两种可能。
1、他们是活雷锋，不挣中间的息差。
2、他们放大了风险敞口，高息借给资质更差的渠道。
很明显两种都不太可能，所以你想要跑赢5.5%就别指望银行了。

五年期国债利率，2016年发的最后一期为4.17%，所以公允的无风险利率不应该比4.17%还要低，
说的更直白一些，购买年化收益低于4.17%的理财就是财富自杀

*跑赢5.5%的品种*
1. 信托（适合100万+的大户）
 购买信托产品时要注意资金投向，
风险最低的是地方政府财政担保的基建类项目，
就是修桥修路之类的，收益率也比较低，大都在5.8-6.2%这个区间。
其他还有股权质押、矿产投资、股权投资、金融机构信托，根据风险不同，收益率也略有浮动，
普遍在6.5-7.5%这个区间。如果是我的话，就哪个收益高买哪个，反正踩了雷就等着信托公司给我兜，区别不大。

2. 分级基金A（30万门槛）
- 分级基金是一个保息不保本的交易品，每年分一次利息，
但是其本身的价格会涨也会跌，如果后面社会公允利率往上涨，
有可能本金会出现5-10%的亏损，这是它的风险。

3. 打新
 - 最高效的打新是沪深各放15万股票，然后全年参与申购，收益率在0-50%这个区间波动，具体看人品。
如果你有300万，分散在10个账户，那收益率很大概率会落在10-15%这个区间。

4. P2P
- 陆金所、人人贷、宜人贷、开鑫贷、微贷网、投哪网、拍拍贷、搜易贷。
如果你把一年的收益目标定在7-8%这个区间，挑6-7个国企背景、金融机构背景、上市公司背景的平台分散投资，
完成起来并不难，即便你碰上一次招X宝那样的雷，由于干爹实力雄厚，本息也有人兜

5. 公司债券
- 本来公司债也是散户理财的一个很不错的渠道，我以前还在夜报里推荐过一些垃圾债，
基本上一年都有15-25%的收益，但是后来监管层采取了分层隔离措施，
垃圾债只允许300万以上的大鳄购买，公司债整个生态都不一样了。


现在违约不断，大鳄买的高收益债刀口舔血，
小散能买的低风险债要么收益很低，要么有炸雷倾向，
我想了想还是不推荐了。而且公司债也面临和分级A一样的问题，未来如果社会公允利率上升，价格会下跌的。

 6. 黄金
- 未来一年如果不出大的意外很可能还是继续横盘震荡。
我在夜报里其实说过多次对黄金投资的态度，投机没意思，主要用来防御风险。
这个风险包含了世界大战风险5%，金融危机风险35%，外汇风险60%，
我建议高净值家庭还是应该考虑配备一点。不用买实体黄金，买点黄金ETF就行。
其实只要政府还姓赵，买ETF和买实体黄金的区别不大

7.  关于房价的一些推理
推理，房价什么情况下会崩？
京沪深的千万房产都是什么人在买？
你要是春节很闲可以看看，其实浓缩起来就几句话：
- 房价受宏观（货币贬值、适婚人口增速、城市化进度、居民收入）和
微观（人口流入流出、产业发展、交通建设）等因素综合影响。
- 其中对房价影响最大的是中国整体经济的繁荣程度，
比如GDP整体如果比现在少一半，那就有很大很大的压力。
-  *房产税* 最多抑制房价，但不可能搞崩房价。
- *房地产* 是国家税收的重要补充，是国本，房市稳定且可持续发展符合国家利益。
- 政府从来没想要让房价下降，政府只怕房价上涨过快导致的杠杆风险。
- 限购限贷都是赵家控制杠杆风险的重要手段，且卓有成效。
- 春节热闹与否是判断一座城市人口流入流出的明显标志，越热闹的城市越没前途。
- 一线城市泡沫就算有也不会很大，刚需买房贷款不要超过家庭月收入100倍，投资买房贷款不要超过家庭月收入75倍。
- 买房决策应该和自己承受能力挂钩，而不是与涨跌预测挂钩，反正无论谁预测都是瞎蒙。
** 做投行、行研、咨询等金融岗位，有没有什么好用的找数据技巧呢？

** 有哪些不起眼却非常赚钱的行业？

** fianance
金融行业重要性，依次是 牌照、资源、人才
** 老公让我拿嫁妆钱买他们公司原始股，可行吗？
在你的朋友中找一个有钱的，并且对分散投资有兴趣的，老老实实的讲清楚目前这个情况，问他是否有兴趣投资，如果项目成功，你可以收取一成或两成的介绍费。
如果他考察之后不看好你老公的公司，那在这点上面，请相信比你有钱的人的眼光。
https://www.zhihu.com/question/35615567/answer/63695246

** 如何选购银行的理财产品？
债券，但是国债和企业债的风险就是天差地别了。
买非不买保, 如果你按照我说的选择了国有大行的理财产品，就没有必要非得买保本型


链接：https://www.zhihu.com/question/20803106/answer/162020968


一般有五个等级：
R1(谨慎型)、R2(稳健型)、R3(平衡型)、R4(进取型)、R5(激进型)。
根据题主的描述，我们来详细介绍一下五个等级的特点：

R1和R2级：首先说一下，R1基本保本保收益，风险很低；
R2不保本，但风险也相对较小。把这两个放在一起是因为R1和R2级别的投资范围基本一样，
大多都是风险比较低的交易所市场债券，资金拆借、信托计划、银行之间的市场及其他金融资产等。通常来看，
R1级别投资低风险部分的比例更高，且通常具有保本条款，也就是“保本保收益类”或“保本浮动收益类”产品。R3级：不保本，风险适中。这一级别的产品除了可以投资于债券、同业存放等低波动性金融产品外，还可投资于股票、商品、外汇等高波动性金融产品，后者的投资比例原则上不超过30%。但该级别不保证本金的偿付，有一定的本金风险，收益浮动。R4级：不保本，风险较大。该级别产品与股票、黄金、外汇等高波动性金融产品挂钩，且比例可超过30%，不保证本金偿付，本金风险较大，收益浮动且波动较大，投资较易受到市场波动和政策法规变化等风险因素影响，亏损的可能性较高。R5级：不保本，风险极大。该级别产品可完全投资于股票、外汇、黄金等各类高波动性的金融产品，本金风险极大，同时收益浮动且波动极大，投资较易受到市场波动和政策法规变化等风险因素影响，当然，对应的预期收益也会较高。总结来说，风险在R3以下的产品相对“安全”，R4和R5的理财产品就不太适合普通人购买。

除非发生大的国际国内军事事件或者国家对国内银行进行了大规模的调整，否则现阶段PR1-3级别的银行理财产品的预期收益都是能达到的，尤其是PR1-2级别。

*银行理财产品* 和在 *银行寄售* 的理财产品不是一个概念

银行寄售的理财产品: 保险,信托
普通投资者就没必要买分红型（或称返还型）的保险

信托对资金的要求门槛高，一般是一百万起，收益率一般都10%以上，但是风险由于没有银行声誉担保，有一定风险

银行在季末、年末发行的理财产品，往往预期收益率比平时更高。建议投资者可在这种时候购买银行理财产品。

*固定期限不可赎回型：*
这些理财产品一般是银行的主流理财产品，其投资期限是固定的，投资者在封闭期期内不可赎回，只能到产品到期后得到本金和预期收益。
由于其封闭性的特性，有闲置暂时不用的资金、并愿意承担一定风险、追求较高收益的投资者可以选择购买此类理财产品。
中国银行中银日积月累-月计划中银集富系列（除与时聚金系列）
中银稳富系列
  + 个人投资者10万元，以1千元累进。
中银债富系列
 + 起点金额: 个人投资者10万元，以1万元累进。


*非保本浮动收益型：*
    中银日积月累系列

    中银集富系列

    中银稳富系列

    中银债富系列



作者：理财小强
链接：https://www.zhihu.com/question/20803106/answer/27534960



check investment product
[[http://www.chinawealth.com.cn ][中国理财]]

** 如何确定未上市企业的利润真实性？
不论是基金公司、评级机构、银行甚至是个人投资者，要去查阅相关公司的内部数据信息难如登天
https://www.zhihu.com/question/20365173/answer/162606322
盈余管理的通常操作方式为将公司有利主要财务数据在关键财务期间提前、夸大体现或将不利数据推迟、缩小体现。
公司盈余管理主要动机如下： 
1. 企业管理层报酬动机 
2.资本市场融资动机
3.企业税收筹划动机 （税率变化、转移定价、保持高新技术企业etc.）
上市公司而言，三种动机发生的频率从高到低分别是1>2>3，而非上市公司而言频率基本是3>>2>>1

> IPO 40大财务迷局

** 人在美国，如何成为中产阶级，成为中产阶级之后如何理财？
financial planner
investopedia
CFP的教材
series 7的教材

- 工人下岗的本质还是属于国家单方面撕毁契约，不过这就涉及到一个哲♂学问题，为了社会进步必须要牺牲一部分人，你原意是被牺牲的那部分吗？
- 中产阶级本质就是无产阶级，他们的财富太脆弱
- 结果众多国企、矿山被白菜价卖出，连祖辈们的养老金都要现在的工作者来支付，这笔积累的巨大财富犹如开闸的洪水促进了经济的发展，也顺便不知道饱了哪些人的私囊
- 中国的高房价的吸血之处在于，一间房子它侵占了上一辈大半生的积蓄——现在多少年轻人买房不是靠父母出的首付？同时还透支了年轻人下半生的预期收益——有多少人买房贷款是在二十年以下的？

- 25万恐怕是投资咨询服务的门槛
- 对于顶尖富豪来说，“大衰退”是机会而不是危机，是一个低成本吞并中小资本的绝佳机会。
- 美国的一些中产阶级在金融证券和房地产上抵押了全部身家，这场金融危机不仅使他们血本无归，大公司的裁员浪潮还使他们中的很多人没有了工作，面对无力支付的教育费用、医疗费用和生活费用

- 某国将土地房产教育户籍制度捆绑销售
- A股就不说了 各种幺蛾子 当然你要是认识庄家或者自己做庄可以 

最重要的五个指标是，收益、风险、流动性、税收安排、其他限制
SP500的长期回报是8%-10%
invest on *Real Estate Investment Trust*, not buy a house and rent it out

几个概念：卖方；买方；商业银行；第三方中介/平台。

*卖方* ：把企业的股权/债权打包成证券，卖出去（主要为投资银行，(代)卖的是“证券”）

买方：把最终投资者的资金组成资金池，购买一级或二级市场上的 *证券* 进行投资管理
（主要是基金保险，买的是“证券/资产权证”，卖的是“投资产品”）

*商业银行* ：吸收储蓄，发放贷款，赚利差

第三方中介/平台：打包销售/零售别的公司的产品


1. *下层中产阶级*
- 用各种保险来“兜底”
- 401k-403b-IRA
- 员工股票-期权购
-  开始为子女教育存钱
- 买个不错的房子。
对于绝大多数中下层中产阶级（50k-100k）来说，“理财”其实几乎等同于“养老”

2. *上层中产阶级/小富*
- 用各种保险来“兜底”
- 升级医保/
- 401k-403b-IRA放满
- 员工股票-期权购买
-  子女教育基金
- 买个很棒的房子
-  mutual fund(共同基金): 金量在几万刀至几十万刀
-  permanent life insurance
-  wealth management - investment account
- / 多花钱来享受生活
-  投资个业余的小生意。
- 自己炒股，怎么说呢...个人态度始终是不建议几乎100%的中产阶级碰个股，除非你仅是炒的玩儿而已，或者你自己真的有bulge bracket或美国各大buy-side们的research and trading power
- 如果已经是“小富”了，或预计会留下很大一笔征税遗产（好比有大概上千万刀以上的资产），可以尽早设立不可撤销信托（trust）来规避遗产税
- 在美国， *房产投资* 仅对两类人有意义：1，真正搞商业房地产投资开发和运营的投资方；2，巨富。除此之外，对于中产阶级，房产就是妥妥的消费品
- 作为一个发达的经济体，更是在全力避免大批民众可以通过收租金来过上理想的生活

3. “富豪”：各种全方位的全面保险/ permanent life insurance/ wealth management - investment account/ 
不可撤销信托/ taxation planning/ 实业和商业地产投资/ 子女教育投资/ 各种花钱来享受生活/ 政治献金/ 慈善。

一个美国人，退休之后能拿到的收入，基本上就三块儿：
1，Social Security -- 类似我国的统筹账户
2，各种个人账户的法定分配 -- 类似我国的商业养老保险
3，个别政府/学校/机构的养老金(pension) -- 类似我们父母那一代人退休后拿的“退休金”其中，

3是个小概率事件，绝大多数企业都没有。1最好不用指望，Social Security账户已经入不敷出N年了，类似于你在交的SS Tax去养现在退休的老人


*个人有关产品购买渠道的意见是（美国版)*
：如果你要A家的基金，直接跟A买；如果你要B家的保险，直接跟B买；如果你账户开在了某华尔街大鳄旗下，甚至其自身就有基金C，直接跟这些卖方买也很靠谱。于是，纯粹的商行代理什么的，都没有打交道的必要，除非真的是图方便（以上提到的所有交易方，资产都是少则千亿美金起的）

作者：Fan Francis
链接：https://www.zhihu.com/question/37226210/answer/71403708


** 年入25万，有什么理财推荐？
不懂的不要碰！
涨多少怎么涨什么时候涨，只有证监会和海子里的人知道
https://www.zhihu.com/question/284498178

* Fund 基金 
** 如何选基金？
晨星的评级、天天的业绩排名、基金经理人有没有更换

选择的标准是：

- 支持T+0快速赎回。
- 知名[[大型基金公

- ETF :: Ｅｘｃｈａｎｇｅ　Ｔｒａｄｅｄ　Ｆｕｎｄ, a marketable security that tracks an index, a commodity, bonds, or a basket of assets like an index fund
- [[https://www.investopedia.com/terms/m/marketablesecurities.asp][Marketable securities]] :: are liquid financial instruments that can be quickly converted into cash at a reasonable price. 

- QDII ::    Qualified domestic institutional investor  
** recommended
*** index fund
510050 
深市100ETF(159901)
沪深300：易方达沪深300ETF联接（110020）

中证500：天弘中证500指数（000962）
标普500：博时标普500ETF联接A（050025）

纳指100：广发纳斯达克100指数A（270042）

恒生指数：华夏恒生ETF联接A（000071）

华夏上证50ETF (510050)
513100- 纳指ETF基金 - 场内基金, you need a stock account 
景顺长城沪深300增强(000311): 基金经理: 黎海威
华泰柏瑞量化增强混合A(000172) 田汉卿
两个基金经理都曾在贝莱德集团(BlackRock，美国规模最大的上市投资管理集团)担任过投资经理

富国中证500


国泰中小盘成长混合(LOF)(160211)


** morning star
Morningstar晨星(中国)2018年度基金奖

 


*** 激进配置型基金
银华富裕主题混合
东方红产业升级混合 

华安策略优选混合

汇添富蓝筹稳健混合

易方达中小盘混合
	



*** 混合型基金
	

winner: 景顺长城动力平衡混合
	
nominator:
南方优选成长混合

广发稳健增长混合

*** 激进债券型基金
	

易方达增强回报债券
	

易方达稳健收益债券

*** 普通债券型基金
	

华安信用四季红债券
	

大摩强收益债券

招商安心收益债券

*** 纯债型基金
	

新华纯债添利债券
	

长信纯债壹号债券

** 国家队基金
华夏新经济
嘉实新机遇
、易方达瑞惠
、南方消费活力、
招商丰庆

2015年救市的时候，证金公司出资了2000亿，成立了5只基金，每只400亿元的规模，分别交给了五大基金公司管理，这五只基金分别是：
鹏华丰泽分级债券B 150061
http://stock.finance.sina.com.cn/fundInfo/view/FundInfo_JJGK.php?symbol=150061
https://zhuanlan.zhihu.com/p/47586566

丰泽A份额将表现出低风险、低收益的明显特征，其预期收益和预期风险要低于普通的债券型基金份额；丰泽B份额则表现出高风险、高收益的显著特征，其预期收益和预期风险要高于普通的债券型基金份额。



** News

银华基金邹维娜：基本面支持债市向好
发表时间：2018-04-02 来源：每日经济新闻

      2017年债券市场的日子算不上好，市场预期、监管环境等多方面影响下，债券市场始终处在波动调整当中。这既表现在债基整体收益率上，也直观体现在投资者更为谨慎的投资态度里。

　　显然，这样的行情下更考验着专业管理人的研究能力和判断决断力。银华基金固定收益部副总监、基金经理邹维娜凭借对市场的深刻把握和对债券的充分认识，其管理的多只债基取得了优秀的业绩回报。
埋头研究市场珍视受托人责任

　　在债券市场上，邹维娜已有十年的投资经历。2012年加入银华基金之后，其管理的多只基金收益表现更是可圈可点。在债市表现差强人意的2017年里，邹维娜管理的银华信用四季红、银华信用季季红、银华纯债信用主题三只基金均跑赢业绩基准收益率。而从中长期的考察维度来看，在2015年～2017年三年里，这三只基金的收益率更是把业绩基准远远甩在身后，三只基金三年回报率均超过15%，其中银华信用季季红的收益率达到了20.44%。

　　持续稳定的收益既是对持有人的最好回报，也得到了行业内的认可。邹维娜管理的基金产品连续三年获得了“金牛奖”：2016年，银华纯债信用主题荣获“三年期开放式债券型持续优胜金牛奖”，银华信用四季红获得三年期开放式债券型持续优胜金牛奖；2017年银华信用四季红再次荣获该奖项；到了2018年，银华信用季季红又获得了该项业内大奖。

　　“对做债券投资来说，树立正确的投资理念非常重要。”在邹维娜看来，债基投资首先是沉下心费些“笨功夫”，回归债券产品本身做研究，搞懂最基本的也是最根本的知识，比如债券收益率如何获得，票息、净价如何变动，久期如何适配等。只有研究清楚，才能做出准确的定价，也才能通过分析研究来判断哪个品种会有超额收益，哪个品种上会有确定的回报。

　　其实，对市场走向的判断和券种的价值考量也来自于多年债券投资积累的丰富经验。而在投资理念上，邹维娜的态度更显谦虚，“要对自己有明确的认识，不断向市场学习。如果可以在某个方面、某个时间段能走在市场前面半步，其实就可以保证你战胜市场了。”

　　“还有一点很重要，我们有足够的诚意，非常珍视受托人的责任。不管是谁的钱都要认真负责地做投资，即使是面包渣般的小收益也要去赚，才能积少成多。”对质地不太良好、风险较大的债券，邹维娜的态度是很明确的规避——“我觉得现在是能给持有人赚很确定收益的时候，任何时候都不能拿持有人的钱去赌。”
乐观看待债市拐点或已出现

　　在经历了前两年债券市场的波动之后，邹维娜对今年的债市更偏乐观。“从大方向上判断，基本面是支持债券向好的，市场可能正处在牛熊的交界处。尽管拐点何时出现总是很难判断，从近期市场走势上看，很可能已经出现了；但是从投资上讲，方向是比幅度和转折点都更重要的”，邹维娜表示。

　　乐观态度的判断依据来自对基本面的研判，在邹维娜看来，从宏观经济趋势上全年是缓慢下行的。而从各个分项上看，货币层面当中比较确定的是今年社会融资规模余额是向下的趋势。出口方面可能不会像去年一样对经济是明显的向上、超预期的拉动，而是更偏向于对经济起到托底作用。投资方面，随着融资监管的加强，地方政府筹资能力面临一定的挑战，房地产和基建投资将进入下行阶段，尤其是基建投资产生的经济下行压力正在不断释放。当然最重要的标准还是估值，结合目前的资金成本和债券的估值水平，债券市场的投资价值依然较为明显。但短期新的上涨周期可能不会很快出现，还需要一定的催化。

　　具体到券种，邹维娜更看好的是利率债和高等级信用债在今年的表现，“持有利率债可能要耐得住寂寞，耐心等待，它的趋势肯定往下走，但你不知道它什么时候往上涨，持有一段时间可能会有涨幅相对较大的阶段。而高等级信用债，由于票息很高不会有太多惊喜，但能获得稳定的收益，而且整体波动性会比利率债小很多。但是对于低等级信用债并不是特别看好，因为它的信用利差也比较窄，又正处在信用风险本身比较大的阶段。
** terms
- 基金换手率 :: 

- ETF :: Ｅｘｃｈａｎｇｅ　Ｔｒａｄｅｄ　Ｆｕｎｄ, a marketable security that tracks an index, a commodity, bonds, or a basket of assets like an index fund
- [[https://www.investopedia.com/terms/m/marketablesecurities.asp][Marketable securities]] :: are liquid financial instruments that can be quickly converted into cash at a reasonable price. 

- QDII ::    Qualified domestic institutional investor  

** References
展恒基金研究中心
wind

*
** index
*key terms*

 Average annual total return
 Market capitalization
 Net asset value
 Share classes
 Turnover

** Fund types
Investment fund, often referred to as a fund

- Hedge fund ::  an investment vehicle open only to investors who are qualified in some way
-   Mutual fund ::  a specific type of investment fund which pools money from many investors to purchase securities
-   Sovereign wealth fund :: a state-owned investment fund

*** 指数基金(Index Fund)

标普500指数的指数基金
指数就是根据样本股票的价格统计出来的数据，用来衡量整个股票市场的价格波动情形。

指数基金就是以指数成份股为投资对象的基金，目标是取得与指数大致相同的收益率。简单地说，它买的不是某一只股票，而是买的一揽子股票来跟踪对应的指数。

指数基金可以分为两类：一类是被动指数型基金，另一类是增强指数型基金。被动指数型基金的策略是买指数里面的全部股票，希望获得和指数一样的收益。而增强指数型基金则是买指数里的大部分股票，同时挑选一些其它的股票搭配，希望获得比指数更高的收益。

基金市场上，风险由高到低依次是：股票型＞指数型＞混合型＞债券型＞货币型。



*** QDII
buy
T+2，份额会到账，那么是按照哪天的净值给你算的份额呢？当然是你申购的那天了，正常算你的交易所属交易日，那个交易日的净值就是咯。比如说9月19日14点申购某纳指QDII基金，21日份额到账，会按照19日的净值算。要注意的是19日的净值是20日晚上公布的。要注意净值对应的日期。
https://finance.qq.com/a/20160921/025722.htm

*** 封闭式基金(Closed-end Funds
折价指的是二级市场的价格小于基金的份额净值。
溢价指的是二级市场的价格大于基金的份额净值。
招商双债增强分级B基金(150127）
基金类型：契约型封闭式

（1）根据基金单位是否可增加或赎回，可分为开放式基金和封闭式基金。     
 开放式基金不上市交易，通过银行、券商、基金公司申购和赎回，基金规模不固定；（我们平时所投资和谈论的基金一般为开放式基金）    

  封闭式基金是指事先确定发行总额，在封闭期内基金单位总数不变，基金上市后投资者可以通过证券市场转让、
买卖基金单位的一种基金。封闭式基金有固定的存续期，投资者通过二级市场买卖基金单位。
- ETF就是一只被动的、可以在二级市场买卖的开放鸡！
- ETF就不止可以在二级市场上买卖，也可以在场外申购和赎回，而且只要是交易时间内都可以。但是少于30万份，对不起，概不受理！！又击碎了一颗散户的玻璃心。
- ETF鸡的涨跌停板是从上市交易第一天就开始生效了。而封闭鸡的上市第一天是没有涨跌停板限制的，封闭鸡的涨跌停从第二个交易日开始。
- 封闭式基金属于信托基金
- 如果你要在一级市场申购和赎回ETF鸡，这样“专业”的业务，也不是所有的券商都可以办理的。要提前关注看养鸡场(基金管理人）发的公告。上面会有能够办理这只鸡的申购和赎回的券商的名单。你们不要到时候想买鸡都找不到经销商哦

作者：李忠文
链接：https://zhuanlan.zhihu.com/p/33853727

*** 分级基金
（一般情况）分级基金的母基金可以分成两个部分，分别是分级A和分级B。不分拆的母基金就相当与普通的基金。分级A不享受基金的投资收益，也不承担投资风险，只是定期获得基金合同约定的收益。分级B承担基金的全部风险的同时也获得基金的全部收益。所以分级基金就相当于，分级B的投资者向分级A的投资者借钱来进行投资，盈亏都算我的，反正我给你利息就是了。

作者：及时晴
链接：https://www.zhihu.com/question/30549213/answer/62934295
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

*** 债券基金
recommend: 指数债券

types:
1.标准债券型基金——俗称“纯债基金”，只能投债券普通债券基金
2. （一级）——俗称“一级债基”，可投债券+在股市一级市场打新股；即前文讨论的基金类别普通债券基金
3. （二级）——俗称“二级债基”，可投债券+在股市二级市场投资

为何不要买二级债基（也就是普通债券基金（二级）），有三个原因。
- 其一，投资者如果想要从股票中获利，可以自己配置股票基金，其比例及股票的种类皆可自定；
- 其二，投资股票不是债券基金经理的专长，即使债券基金经理是对一家公司有深入的研究，
但这家公司所发行的债券与股票的估值方法是很不同的，债券基金经理未必可以对股票做出最优投资决策；
- 其三，历史业绩也证明了二级债基的收益不如一级债基，2006~2013年间，所有二级债基年化收益率排名前3的为8.96%、 7.83%与5.48%；所有二级债基年化收益率平均值为1.90%，中位数为2.09%，年化收益率超过3%的二级债基仅21只，而总数为78只——所有数据都落后于一级债基

作者：runze Zheng
链接：https://www.zhihu.com/question/23028671/answer/24293138

**** 如何判断债基是纯债基还是一级债基或者二级债基？
纯债基金：仅投资与固定收益类金融工具，不能投资于股票市场，专门投资债券的基金。

一级债基：在80%投资于债券的纯债基金的基础上可以打新股的基金。

二级债基：在一级债基的基础上，可以投资于二级市场股票，但投资比例不能超过20%的基金。 



login [[http://www.cninfo.com.cn ][巨潮资讯 ]]--中国证监会指定信息披露网站，所有公开发行的股票、债券和基金都需在巨潮资讯上定期披露信息。要判断一只债券型基金是哪一种，上这个网站查即可。


输入你想查看的基金（也可以是股票和债券）代码、名称或简称，如下图。
在此输入题主举例问的——
161010，选中“富国天丰” -- 一级债基

- check 说明书>> 基金的投资 >> 投资范围
https://www.zhihu.com/question/31142500



**** 指数债券


*** FOF（Fund of Funds
http://fund.jrj.com.cn/2017/07/14144622749945.shtml

*** Mutual Fund(US)
fidelity

*** 公募基金 ([[https://en.wikipedia.org/wiki/Mutual_fund][Mutual Fund]])

mutual funds include open-end funds, unit investment trusts, and closed-end funds

Mutual funds are also classified by their principal investments as:
-  money market funds, bond 
-  fixed income funds, stock 
-  equity funds
- hybrid funds



- 公募基金 (China) :: 指由国内基金公司发行的基金，在国内注册，以国内投资人为销售对象，受到国内相关法律监督的基金。投资标的市场则主要是 *中国股市* ，也有小部分基金通过QDII等渠道投资海外股.

- 海外的共同基金则是指海外基金管理公司所发行的基金，由该基金公司的基金经理管理并投资于全球的证券市场，主要针对全球的投资者。


- 公募基金 (China) :: 指由国内基金公司发行的基金，在国内注册，以国内投资人为销售对象，受到国内相关法律监督的基金。
作者：蔡华
链接：https://www.zhihu.com/question/56159750/answer/151167537
https://www.fidelity.com/learning-center/investment-products/mutual-funds/what-are-mutual-funds

1、海外基金市场发展成熟国外的基金从18世纪60年代就开始发展起来，到现在已经一两百年的历史，发展相对要成熟、稳定。
国内的基金，受限于股票市场发展较晚，到现在为止只有20年的时间。
发展程度的不同决定了两者之间的很多不同。首先，海外基金一般都有的较长的历史业绩数据，
投资者可以参考基金的业绩数据进行投资决策。而国内的基金一般成立时间不久，过往业绩历史较短，
没有经历过市场周期的考验。因而投资者难以判断基金是否能够创造持续稳定的收益。其次，投资策略和投资团队的稳定性。海外基金历史悠久，一般都是一致连贯的投资策略。有很多超过上百年管理投资经验的海外投资管理公司，能够给投资者提供双重保障。投资团队也非常稳定。比如美国，它的基金经理的平均任期时间是5.7年，最长任期是48.5年。而国内的基金，基金经理平均任期时间只有1年。差距很明显。2、海外基金品种较为丰富基金一般可以根据投资标的所在的市场、类型和所属行业进行分类。由于每类基金的风险收益特征存在差异性，投资者筛选基金的第一步应是对基金类别的选择。我国基金产品的分类方法众多，没有统一标准，且缺乏细分。另外，如统一将主要投资股票的产品归纳为股票型基金，不再根据市值或风格等进行细分，投资者将无法充分了解自身投资标的的特征。相比之下，美国基金的分类较为清晰且有迹可循。其大多数产品基于投资标的特征，先以资产属性，再以地区、持股市值（大/中/小盘），最后以投资风格逐级进行分类，不少产品也会按照这个顺序冠名。投资者可以一目了然。3、投资范围不同一般国内的基金投资者在购买基金时会发现，国内的基金主要分为股票型、债券型、货币型、还有混合型。国外的基金除了这些基金外，还有很多投资于商品、能源、黄金和衍生品等的基金。国内基金现在基本上只能投资在国内的市场，但是国外基金，可以在全球范围内投资，基金经理可以在全球范围内寻找表现最好的市场。由于同一时期各个国家和地区的投资回报表现各不相同，如果投资范围不仅仅限于某个单一市场，而是更广一点，就可以合理的在不同市场之间切换，追踪投资回报高的热点市场。4、相对收益vs绝对收益海外基金一般都会有一个投资基准。基金经理的目标是通过专业的管理能力为提供投资者超过基准的收益。比如说投资于美国大盘蓝筹股的基金以标准普尔500指数作为参考基准。该策略的经理人都会力求能够提供超越基准的超额收益。举例说如果标准普尔500指数在过去一年的收益是10%，该基金的收益为15%，那么超过的5%的部分就是基金经理所创造的超额收益。如果市场不景气，基准指数下跌10%，如果通过经理人的风险控制最终基金收益为-5%。为投资者减轻了损失，所创造的超额收益也是5%。当相似的投资策略均以同一个指数作为基准时，提高了产品之间的可比性。基准还有助于衡量基金是否坚持一致的策略，并且可以衡量基金经历的创造超额收益的能力。而由于国内投资者更看重绝对收益。期望在市场上涨中获得更高收益，在市场下跌中能够幸免，甚至要求必须为正收益。国内投资者的对投资及基准的认识比较模糊，也很少关注产品的超额收益。同时，一些基金公司并没有引导投资者培养正确的投资理念，而是一味地迎合投资者的心理，在设计产品中对基准的设立较为随意。5、换手率海外基金的换手率较低，基金投资者也偏好持有换手率低的基金。美国投资业协会数据显示，近35年来，权益类共同基金换手率的平均值仅为61%，其中2014年为43%，且约一半投资者持有的基金换手率低于30%。这意味着，这些基金的平均持仓时间在3年以上。低换手率除了能有效降低运作成本外，也意味着对挑选股票的要求更高。基金经理在选股时更看重个股的长期投资价值，这需要对公司的竞争优势，持续成长前景，财务情况和管理层水平等基本面的了解更为深入，要求更加严格。相比而言，国内基金的换手率相对较高。这些基金的投资操作风格具有散户化的倾向，在投资理念上热衷于短炒，较为忽略价值和估值，人为增加了基金的运作成本。6. 汇率风险除了市场的系统性风险和股票的个体风险以外，投资海外基金还存在一定的汇率风险。因为大部分海外基金都是用外币计价，以美元、欧元等货币为主。如果人民币对外币长期贬值，赎回基金时就会额外收益；相反，如果人民币对外币长期来看是升值的，当赎回基金时本金就存在额外的损失。不过在实际投资中，基金管理者会通过将资产投资到不同的海外市场，所以币种之间可能存在贬值和升值相抵消的情况。另外有些基金会做货币对冲以消除汇率风险。
*** fixed-income funds
Access to the bond market and the opportunity for a regular income.

    Designed to try to generate a consistent income
    Good for diversifying your portfolio
    Often used to achieve longer-term goals
    Income levels cannot be guaranteed – fixed-income funds will create variable levels of income


*** sector funds
Invest in companies that operate in particular industries or sectors – including commodity funds.

    Chance to invest in a single sector
    A selection to suit your strategy
    Leverage specialist knowledge in target sectors
    Less diversified than other funds, so may be more volatile than other options


*** Momey Market funds
A shorter-term investment option that may carry a lower risk with higher interest rates than savings accounts.

    Diverse portfolios to select to suit your risk profile
    Experienced fund managers


*** Equity funds

** 大型基金公司
- 易方达
- 南方基金
- 汇添富
- 广发
- 华夏
- 嘉实
http://fund.eastmoney.com/company/default.html

** 主动型基金如何选择？
被动型(指数型)基金

- 主动型基金不刻意去做指数化投资，以超越市场基准为目标
- 主动型基金即主动管理型基金，是指募集后有基金经理操盘，把资金投资于他所偏爱的股票，债券等，以期获得超越市场基准的收益的基金

- 指数增强型基金 :: 

富国沪深300指数增强

广发纯债A


股债1:1动态再平衡
- 逢股票资产涨，卖出一部分并买入固定收益类资产——逢高自动锁定收益。逢股票资产跌，卖出一部分固定收益资产并买入股票资产——逢低自动买入捡便宜货。
- 战胜人性，不贪不恐
  + 在疯涨时渴望再涨，在暴跌时担忧还跌，这就是人性当中的恐惧与贪婪。巨亏者往往在大众贪婪时更疯狂，在大众恐惧时更惶惶，总是高买低卖，傻事做尽。
- 一年只交易1-2次

第一步，用晨星基金网的晨星股票风格箱选出价值/平衡/成长三类基金当中，三年/五年评级四星、五星的基金
第二步，从这些基金当中找寻高阿尔法系数、高夏普比率、低晨星风险系数的基金。
第三步，从这些基金当中找基金经理在任稳定，没有频繁变更基金经理的基金
第四步，翻看基金的季度十大重仓股，看基金的季度报，看基金经理是不是风格保持一致
第五步，排除一些媒体过度曝光，各路资金纷纷申购的基金，排除最近几个季度规模暴涨的基金，股票型基金排除规模50亿以上的
第六步，按照各种基金的风格或者投资的标的建立相应的基金池。
第七步，定投或持有之后考察业绩变动，若长期跑不赢基金业绩基准则考虑从基金池中找寻替补基金去替换。 

股票指数永远长寿，有推陈纳新的机制，只要一国经济向好发展，股票指数永远看涨。而指数增强型基金比传统的指数ETF有很强的超额收益，是被动投资与主动投资的良好结合。

即再乐观的时候持有股票的仓位不要高于投资总资产的75%，再悲观的时候股票仓位的占比不要低于25%，投资者可以在股债3:1，股债1:3之间调整自己的投资组合以期获得良好的收益。

基金投资需要持续学习，作为投资者在投资基金前一定要阅读基金招募书，其中必看的部分是“基金的投资”这一章，不看这一章就好比吃药不看药物说明书，危害巨大！

** Where to buy?
- 基金自营
- taobao

** References
展恒基金研究中心
wind

** Fund types
Investment fund, often referred to as a fund

- Hedge fund ::  an investment vehicle open only to investors who are qualified in some way
-   Mutual fund ::  a specific type of investment fund which pools money from many investors to purchase securities
-   Sovereign wealth fund :: a state-owned investment fund

*** FOF（Fund of Funds
http://fund.jrj.com.cn/2017/07/14144622749945.shtml

*** Mutual Fund(US)
fidelity

*** 公募基金 ([[https://en.wikipedia.org/wiki/Mutual_fund][Mutual Fund]])

mutual funds include open-end funds, unit investment trusts, and closed-end funds

Mutual funds are also classified by their principal investments as:
-  money market funds, bond 
-  fixed income funds, stock 
-  equity funds
- hybrid funds



- 公募基金 (China) :: 指由国内基金公司发行的基金，在国内注册，以国内投资人为销售对象，受到国内相关法律监督的基金。投资标的市场则主要是 *中国股市* ，也有小部分基金通过QDII等渠道投资海外股.

- 海外的共同基金则是指海外基金管理公司所发行的基金，由该基金公司的基金经理管理并投资于全球的证券市场，主要针对全球的投资者。


- 公募基金 (China) :: 指由国内基金公司发行的基金，在国内注册，以国内投资人为销售对象，受到国内相关法律监督的基金。
作者：蔡华
链接：https://www.zhihu.com/question/56159750/answer/151167537
https://www.fidelity.com/learning-center/investment-products/mutual-funds/what-are-mutual-funds

1、海外基金市场发展成熟国外的基金从18世纪60年代就开始发展起来，到现在已经一两百年的历史，发展相对要成熟、稳定。
国内的基金，受限于股票市场发展较晚，到现在为止只有20年的时间。
发展程度的不同决定了两者之间的很多不同。首先，海外基金一般都有的较长的历史业绩数据，
投资者可以参考基金的业绩数据进行投资决策。而国内的基金一般成立时间不久，过往业绩历史较短，
没有经历过市场周期的考验。因而投资者难以判断基金是否能够创造持续稳定的收益。其次，投资策略和投资团队的稳定性。海外基金历史悠久，一般都是一致连贯的投资策略。有很多超过上百年管理投资经验的海外投资管理公司，能够给投资者提供双重保障。投资团队也非常稳定。比如美国，它的基金经理的平均任期时间是5.7年，最长任期是48.5年。而国内的基金，基金经理平均任期时间只有1年。差距很明显。2、海外基金品种较为丰富基金一般可以根据投资标的所在的市场、类型和所属行业进行分类。由于每类基金的风险收益特征存在差异性，投资者筛选基金的第一步应是对基金类别的选择。我国基金产品的分类方法众多，没有统一标准，且缺乏细分。另外，如统一将主要投资股票的产品归纳为股票型基金，不再根据市值或风格等进行细分，投资者将无法充分了解自身投资标的的特征。相比之下，美国基金的分类较为清晰且有迹可循。其大多数产品基于投资标的特征，先以资产属性，再以地区、持股市值（大/中/小盘），最后以投资风格逐级进行分类，不少产品也会按照这个顺序冠名。投资者可以一目了然。3、投资范围不同一般国内的基金投资者在购买基金时会发现，国内的基金主要分为股票型、债券型、货币型、还有混合型。国外的基金除了这些基金外，还有很多投资于商品、能源、黄金和衍生品等的基金。国内基金现在基本上只能投资在国内的市场，但是国外基金，可以在全球范围内投资，基金经理可以在全球范围内寻找表现最好的市场。由于同一时期各个国家和地区的投资回报表现各不相同，如果投资范围不仅仅限于某个单一市场，而是更广一点，就可以合理的在不同市场之间切换，追踪投资回报高的热点市场。4、相对收益vs绝对收益海外基金一般都会有一个投资基准。基金经理的目标是通过专业的管理能力为提供投资者超过基准的收益。比如说投资于美国大盘蓝筹股的基金以标准普尔500指数作为参考基准。该策略的经理人都会力求能够提供超越基准的超额收益。举例说如果标准普尔500指数在过去一年的收益是10%，该基金的收益为15%，那么超过的5%的部分就是基金经理所创造的超额收益。如果市场不景气，基准指数下跌10%，如果通过经理人的风险控制最终基金收益为-5%。为投资者减轻了损失，所创造的超额收益也是5%。当相似的投资策略均以同一个指数作为基准时，提高了产品之间的可比性。基准还有助于衡量基金是否坚持一致的策略，并且可以衡量基金经历的创造超额收益的能力。而由于国内投资者更看重绝对收益。期望在市场上涨中获得更高收益，在市场下跌中能够幸免，甚至要求必须为正收益。国内投资者的对投资及基准的认识比较模糊，也很少关注产品的超额收益。同时，一些基金公司并没有引导投资者培养正确的投资理念，而是一味地迎合投资者的心理，在设计产品中对基准的设立较为随意。5、换手率海外基金的换手率较低，基金投资者也偏好持有换手率低的基金。美国投资业协会数据显示，近35年来，权益类共同基金换手率的平均值仅为61%，其中2014年为43%，且约一半投资者持有的基金换手率低于30%。这意味着，这些基金的平均持仓时间在3年以上。低换手率除了能有效降低运作成本外，也意味着对挑选股票的要求更高。基金经理在选股时更看重个股的长期投资价值，这需要对公司的竞争优势，持续成长前景，财务情况和管理层水平等基本面的了解更为深入，要求更加严格。相比而言，国内基金的换手率相对较高。这些基金的投资操作风格具有散户化的倾向，在投资理念上热衷于短炒，较为忽略价值和估值，人为增加了基金的运作成本。6. 汇率风险除了市场的系统性风险和股票的个体风险以外，投资海外基金还存在一定的汇率风险。因为大部分海外基金都是用外币计价，以美元、欧元等货币为主。如果人民币对外币长期贬值，赎回基金时就会额外收益；相反，如果人民币对外币长期来看是升值的，当赎回基金时本金就存在额外的损失。不过在实际投资中，基金管理者会通过将资产投资到不同的海外市场，所以币种之间可能存在贬值和升值相抵消的情况。另外有些基金会做货币对冲以消除汇率风险。
*** fixed-income funds
Access to the bond market and the opportunity for a regular income.

    Designed to try to generate a consistent income
    Good for diversifying your portfolio
    Often used to achieve longer-term goals
    Income levels cannot be guaranteed – fixed-income funds will create variable levels of income


*** sector funds
Invest in companies that operate in particular industries or sectors – including commodity funds.

    Chance to invest in a single sector
    A selection to suit your strategy
    Leverage specialist knowledge in target sectors
    Less diversified than other funds, so may be more volatile than other options


*** Momey Market funds
A shorter-term investment option that may carry a lower risk with higher interest rates than savings accounts.

    Diverse portfolios to select to suit your risk profile
    Experienced fund managers


*** Equity funds
*** 指数基金(Index Fund)

标普500指数的指数基金
指数就是根据样本股票的价格统计出来的数据，用来衡量整个股票市场的价格波动情形。

指数基金就是以指数成份股为投资对象的基金，目标是取得与指数大致相同的收益率。简单地说，它买的不是某一只股票，而是买的一揽子股票来跟踪对应的指数。

指数基金可以分为两类：一类是被动指数型基金，另一类是增强指数型基金。被动指数型基金的策略是买指数里面的全部股票，希望获得和指数一样的收益。而增强指数型基金则是买指数里的大部分股票，同时挑选一些其它的股票搭配，希望获得比指数更高的收益。

基金市场上，风险由高到低依次是：股票型＞指数型＞混合型＞债券型＞货币型。

** 大型基金公司
- 易方达
- 南方基金
- 汇添富
- 广发
- 华夏
- 嘉实
http://fund.eastmoney.com/company/default.html

** 主动型基金如何选择？
被动型(指数型)基金

- 主动型基金不刻意去做指数化投资，以超越市场基准为目标
- 主动型基金即主动管理型基金，是指募集后有基金经理操盘，把资金投资于他所偏爱的股票，债券等，以期获得超越市场基准的收益的基金

- 指数增强型基金 :: 

富国沪深300指数增强

广发纯债A


股债1:1动态再平衡
- 逢股票资产涨，卖出一部分并买入固定收益类资产——逢高自动锁定收益。逢股票资产跌，卖出一部分固定收益资产并买入股票资产——逢低自动买入捡便宜货。
- 战胜人性，不贪不恐
  + 在疯涨时渴望再涨，在暴跌时担忧还跌，这就是人性当中的恐惧与贪婪。巨亏者往往在大众贪婪时更疯狂，在大众恐惧时更惶惶，总是高买低卖，傻事做尽。
- 一年只交易1-2次

第一步，用晨星基金网的晨星股票风格箱选出价值/平衡/成长三类基金当中，三年/五年评级四星、五星的基金
第二步，从这些基金当中找寻高阿尔法系数、高夏普比率、低晨星风险系数的基金。
第三步，从这些基金当中找基金经理在任稳定，没有频繁变更基金经理的基金
第四步，翻看基金的季度十大重仓股，看基金的季度报，看基金经理是不是风格保持一致
第五步，排除一些媒体过度曝光，各路资金纷纷申购的基金，排除最近几个季度规模暴涨的基金，股票型基金排除规模50亿以上的
第六步，按照各种基金的风格或者投资的标的建立相应的基金池。
第七步，定投或持有之后考察业绩变动，若长期跑不赢基金业绩基准则考虑从基金池中找寻替补基金去替换。 

股票指数永远长寿，有推陈纳新的机制，只要一国经济向好发展，股票指数永远看涨。而指数增强型基金比传统的指数ETF有很强的超额收益，是被动投资与主动投资的良好结合。

即再乐观的时候持有股票的仓位不要高于投资总资产的75%，再悲观的时候股票仓位的占比不要低于25%，投资者可以在股债3:1，股债1:3之间调整自己的投资组合以期获得良好的收益。

基金投资需要持续学习，作为投资者在投资基金前一定要阅读基金招募书，其中必看的部分是“基金的投资”这一章，不看这一章就好比吃药不看药物说明书，危害巨大！

** Where to buy?
- 基金自营
- taobao
** 如何选基金？

选择的标准是：

- 支持T+0快速赎回。
- 知名[[大型基金公



** References
展恒基金研究中心
wind

** index
*key terms*

 Average annual total return
 Market capitalization
 Net asset value
 Share classes
 Turnover

** Fund types
Investment fund, often referred to as a fund

- Hedge fund ::  an investment vehicle open only to investors who are qualified in some way
-   Mutual fund ::  a specific type of investment fund which pools money from many investors to purchase securities
-   Sovereign wealth fund :: a state-owned investment fund
- ETF :: Ｅｘｃｈａｎｇｅ　Ｔｒａｄｅｄ　Ｆｕｎｄ, a marketable security that tracks an index, a commodity, bonds, or a basket of assets like an index fund
- [[https://www.investopedia.com/terms/m/marketablesecurities.asp][Marketable securities]] :: are liquid financial instruments that can be quickly converted into cash at a reasonable price. 

- QDII ::    Qualified domestic institutional investor  
*** FOF（Fund of Funds
http://fund.jrj.com.cn/2017/07/14144622749945.shtml

*** Mutual Fund(US)
fidelity

*** 公募基金 ([[https://en.wikipedia.org/wiki/Mutual_fund][Mutual Fund]])

mutual funds include open-end funds, unit investment trusts, and closed-end funds

Mutual funds are also classified by their principal investments as:
-  money market funds, bond 
-  fixed income funds, stock 
-  equity funds
- hybrid funds



- 公募基金 (China) :: 指由国内基金公司发行的基金，在国内注册，以国内投资人为销售对象，受到国内相关法律监督的基金。投资标的市场则主要是 *中国股市* ，也有小部分基金通过QDII等渠道投资海外股.

- 海外的共同基金则是指海外基金管理公司所发行的基金，由该基金公司的基金经理管理并投资于全球的证券市场，主要针对全球的投资者。


- 公募基金 (China) :: 指由国内基金公司发行的基金，在国内注册，以国内投资人为销售对象，受到国内相关法律监督的基金。
作者：蔡华
链接：https://www.zhihu.com/question/56159750/answer/151167537
https://www.fidelity.com/learning-center/investment-products/mutual-funds/what-are-mutual-funds

1、海外基金市场发展成熟国外的基金从18世纪60年代就开始发展起来，到现在已经一两百年的历史，发展相对要成熟、稳定。
国内的基金，受限于股票市场发展较晚，到现在为止只有20年的时间。
发展程度的不同决定了两者之间的很多不同。首先，海外基金一般都有的较长的历史业绩数据，
投资者可以参考基金的业绩数据进行投资决策。而国内的基金一般成立时间不久，过往业绩历史较短，
没有经历过市场周期的考验。因而投资者难以判断基金是否能够创造持续稳定的收益。其次，投资策略和投资团队的稳定性。海外基金历史悠久，一般都是一致连贯的投资策略。有很多超过上百年管理投资经验的海外投资管理公司，能够给投资者提供双重保障。投资团队也非常稳定。比如美国，它的基金经理的平均任期时间是5.7年，最长任期是48.5年。而国内的基金，基金经理平均任期时间只有1年。差距很明显。2、海外基金品种较为丰富基金一般可以根据投资标的所在的市场、类型和所属行业进行分类。由于每类基金的风险收益特征存在差异性，投资者筛选基金的第一步应是对基金类别的选择。我国基金产品的分类方法众多，没有统一标准，且缺乏细分。另外，如统一将主要投资股票的产品归纳为股票型基金，不再根据市值或风格等进行细分，投资者将无法充分了解自身投资标的的特征。相比之下，美国基金的分类较为清晰且有迹可循。其大多数产品基于投资标的特征，先以资产属性，再以地区、持股市值（大/中/小盘），最后以投资风格逐级进行分类，不少产品也会按照这个顺序冠名。投资者可以一目了然。3、投资范围不同一般国内的基金投资者在购买基金时会发现，国内的基金主要分为股票型、债券型、货币型、还有混合型。国外的基金除了这些基金外，还有很多投资于商品、能源、黄金和衍生品等的基金。国内基金现在基本上只能投资在国内的市场，但是国外基金，可以在全球范围内投资，基金经理可以在全球范围内寻找表现最好的市场。由于同一时期各个国家和地区的投资回报表现各不相同，如果投资范围不仅仅限于某个单一市场，而是更广一点，就可以合理的在不同市场之间切换，追踪投资回报高的热点市场。4、相对收益vs绝对收益海外基金一般都会有一个投资基准。基金经理的目标是通过专业的管理能力为提供投资者超过基准的收益。比如说投资于美国大盘蓝筹股的基金以标准普尔500指数作为参考基准。该策略的经理人都会力求能够提供超越基准的超额收益。举例说如果标准普尔500指数在过去一年的收益是10%，该基金的收益为15%，那么超过的5%的部分就是基金经理所创造的超额收益。如果市场不景气，基准指数下跌10%，如果通过经理人的风险控制最终基金收益为-5%。为投资者减轻了损失，所创造的超额收益也是5%。当相似的投资策略均以同一个指数作为基准时，提高了产品之间的可比性。基准还有助于衡量基金是否坚持一致的策略，并且可以衡量基金经历的创造超额收益的能力。而由于国内投资者更看重绝对收益。期望在市场上涨中获得更高收益，在市场下跌中能够幸免，甚至要求必须为正收益。国内投资者的对投资及基准的认识比较模糊，也很少关注产品的超额收益。同时，一些基金公司并没有引导投资者培养正确的投资理念，而是一味地迎合投资者的心理，在设计产品中对基准的设立较为随意。5、换手率海外基金的换手率较低，基金投资者也偏好持有换手率低的基金。美国投资业协会数据显示，近35年来，权益类共同基金换手率的平均值仅为61%，其中2014年为43%，且约一半投资者持有的基金换手率低于30%。这意味着，这些基金的平均持仓时间在3年以上。低换手率除了能有效降低运作成本外，也意味着对挑选股票的要求更高。基金经理在选股时更看重个股的长期投资价值，这需要对公司的竞争优势，持续成长前景，财务情况和管理层水平等基本面的了解更为深入，要求更加严格。相比而言，国内基金的换手率相对较高。这些基金的投资操作风格具有散户化的倾向，在投资理念上热衷于短炒，较为忽略价值和估值，人为增加了基金的运作成本。6. 汇率风险除了市场的系统性风险和股票的个体风险以外，投资海外基金还存在一定的汇率风险。因为大部分海外基金都是用外币计价，以美元、欧元等货币为主。如果人民币对外币长期贬值，赎回基金时就会额外收益；相反，如果人民币对外币长期来看是升值的，当赎回基金时本金就存在额外的损失。不过在实际投资中，基金管理者会通过将资产投资到不同的海外市场，所以币种之间可能存在贬值和升值相抵消的情况。另外有些基金会做货币对冲以消除汇率风险。
*** fixed-income funds
Access to the bond market and the opportunity for a regular income.

    Designed to try to generate a consistent income
    Good for diversifying your portfolio
    Often used to achieve longer-term goals
    Income levels cannot be guaranteed – fixed-income funds will create variable levels of income


*** sector funds
Invest in companies that operate in particular industries or sectors – including commodity funds.

    Chance to invest in a single sector
    A selection to suit your strategy
    Leverage specialist knowledge in target sectors
    Less diversified than other funds, so may be more volatile than other options


*** Momey Market funds
A shorter-term investment option that may carry a lower risk with higher interest rates than savings accounts.

    Diverse portfolios to select to suit your risk profile
    Experienced fund managers


*** Equity funds
*** 指数基金(Index Fund)

标普500指数的指数基金
指数就是根据样本股票的价格统计出来的数据，用来衡量整个股票市场的价格波动情形。

指数基金就是以指数成份股为投资对象的基金，目标是取得与指数大致相同的收益率。
简单地说，它买的不是某一只股票，而是买的一揽子股票来跟踪对应的指数。

指数基金可以分为两类：一类是被动指数型基金，另一类是增强指数型基金。
被动指数型基金的策略是买指数里面的全部股票，希望获得和指数一样的收益。而增强指数型基金则是买指数里的大部分股票，同时挑选一些其它的股票搭配，希望获得比指数更高的收益。

基金市场上，风险由高到低依次是：股票型＞指数型＞混合型＞债券型＞货币型。


** 大型基金公司
- 易方达
- 南方基金
- 汇添富
- 广发
- 华夏
- 嘉实
http://fund.eastmoney.com/company/default.html

** 主动型基金如何选择？
被动型(指数型)基金

- 主动型基金不刻意去做指数化投资，以超越市场基准为目标
- 主动型基金即主动管理型基金，是指募集后有基金经理操盘，把资金投资于他所偏爱的股票，债券等，以期获得超越市场基准的收益的基金

- 指数增强型基金 :: 

富国沪深300指数增强

广发纯债A


股债1:1动态再平衡
- 逢股票资产涨，卖出一部分并买入固定收益类资产——逢高自动锁定收益。逢股票资产跌，卖出一部分固定收益资产并买入股票资产——逢低自动买入捡便宜货。
- 战胜人性，不贪不恐
  + 在疯涨时渴望再涨，在暴跌时担忧还跌，这就是人性当中的恐惧与贪婪。巨亏者往往在大众贪婪时更疯狂，在大众恐惧时更惶惶，总是高买低卖，傻事做尽。
- 一年只交易1-2次

第一步，用晨星基金网的晨星股票风格箱选出价值/平衡/成长三类基金当中，三年/五年评级四星、五星的基金
第二步，从这些基金当中找寻高阿尔法系数、高夏普比率、低晨星风险系数的基金。
第三步，从这些基金当中找基金经理在任稳定，没有频繁变更基金经理的基金
第四步，翻看基金的季度十大重仓股，看基金的季度报，看基金经理是不是风格保持一致
第五步，排除一些媒体过度曝光，各路资金纷纷申购的基金，排除最近几个季度规模暴涨的基金，股票型基金排除规模50亿以上的
第六步，按照各种基金的风格或者投资的标的建立相应的基金池。
第七步，定投或持有之后考察业绩变动，若长期跑不赢基金业绩基准则考虑从基金池中找寻替补基金去替换。 

股票指数永远长寿，有推陈纳新的机制，只要一国经济向好发展，股票指数永远看涨。而指数增强型基金比传统的指数ETF有很强的超额收益，是被动投资与主动投资的良好结合。

即再乐观的时候持有股票的仓位不要高于投资总资产的75%，再悲观的时候股票仓位的占比不要低于25%，投资者可以在股债3:1，股债1:3之间调整自己的投资组合以期获得良好的收益。

基金投资需要持续学习，作为投资者在投资基金前一定要阅读基金招募书，其中必看的部分是“基金的投资”这一章，不看这一章就好比吃药不看药物说明书，危害巨大！

** Where to buy?
- 基金自营
- taobao
** 如何选基金？

选择的标准是：

- 支持T+0快速赎回。
- 知名[[大型基金公司]]的产品。
- 基金的规模（A+B合计）不低于100亿。
- 基金具有较低的运作成本，且具有较高的平稳收益。
- 不是买大盘指数基金，而是蓝筹指数基金
- 可以通过基金排行，筛选出近五年、近三年、近一年、近半年等阶段，业绩表现排名前列的基金
- 成立时间2年以上、
- 成立以来年化收益20%以上、
- 成立以来最大回撤20%以内 。
- 为了使数据更加透明，淘汰在基金业协会查不到详细备案的产品；
- 每位基金经理只选一个产品，因为他的多个产品，收益曲线几乎相同，相关系数太高，不利于多元化的资产配置（淘汰54个产品）
；最后，需从任意时间起一年，盈利不低于银行固定存款利率



分级基金A份
 examples:
易方达现金增利B和南方天天利B

基金的年报、季报、半年报

https://mp.weixin.qq.com/s/88jJfqiIeTmQLonAzJqyAA?
https://www.zhihu.com/question/19801437/answer/86930353

*** 蓝筹指数基金


** 定投基金
- 价值型,沪深300指数增强、中证红利指数增强
- 成长型, e.g. 中证500指数
- 指数增强型

** 基金分红
 按照《证券投资基金管理暂行办法》的规定：基金分红
每年至少一次，基金分红主要有两种方式：一种是现金分红，一种是红利再投资。
　　一般来说，基金分红需要满足以下原则：
　　1.基金当期收益先弥补上期亏损后，方可进行当期收益分配；
　　2.基金收益分配后每份基金份额的净值不能低于面值；
　　3.如果基金当期出现亏损，则不进行收益分配。
** 如何阅读上市公司的年报？
** 招募说明书?
* 天使投资（Angel Investment）、VC（Venture Capital）和PE（Private Equity）的主要区别在于投资介入的阶段不同。
angle investment >> venture capital >> PE >> IPO

（1）天使投资主要投资早期创业公司；

（2）VC投资中期高速发展型创业公司；

（3）PE介入即将上市或被兼并收购的成熟企业。

可以说，VC接天使投资的盘，PE接VC的盘，IPO（上市）接PE的盘。

投资阶段的不同决定了他们以下不同的特性：
https://zhidao.baidu.com/question/2268408655584943668.html

* TODO  holding funds
** 嘉实原油(QDII-LOF)(160723)
业绩比较基准	100%WTI原油价格收益率k

other oil index:
north america >> WTI
British >> Brent
Middle east >> Dubai and Oman


* TODO Reading
彼得·林奇（Peter Lynch

- 优质公司的股东

* snowball

**  long term 
小小辛巴
雷公资本
https://www.zhihu.com/topic/19661150/top-answers

CPA( certified public accountant) 考试会计、财务管理、公司战略
Warren Buffett’s annual letter
http://www.berkshirehathaway.com/letters/letters.html

供给侧改革
- 需求侧改革 :: 投资、消费、出口
- 供给侧 :: 劳动力、土地、资本、制度创造、创新等要素。

《经济学原理》，《货币银行学》、《资本论》、《国富论》
SSW.N, Seaspan Corp
Seventeen Contradictions and the End of Capitalism
 the pursuit of political-economic self-interests under the veil of "universal values



one up on wall street
Big Money
common stocks and Uncommon Profits and Other Writings, Philip A.Fisher

* TODO 风险投资(VC)基金
基本上是对经济最敏感的行业
* propeous jobs in the next 20-30 years
** technology drived
1. AI
** spending drived
1. light luxury
2. education
3. medicine
4. entertainment
steam教育、留学后服务、教育技术化


* Softwares
** [[http://tushare.org/index.html#id4][tushare]]--open source fiancial tool (Python)
* 宏观经济学

可汗学院公开课：宏观经济学
* Real estate in China
file:finance/RealEstate.org
* Bitcoin
key idea : Denationalization of Money
http://nakamotoinstitute.org/bitcoin/
* stocks
file:finance/stock.org
* Trust
https://trust.ecitic.com/ 
 trust-信托
** 信托公司的运作方式是怎样的？投资项目同信托公司之间是什么关系？
https://www.zhihu.com/question/20851621/answer/16396917
** 信托公司没有自己的销售吗？要靠银行渠道？
主要是靠银行渠道，银行掌握着大量的客户资源。其次应该是第三方理财机构，最后才是信托公司自身。 部分信托公司也有自己的营销部门和队伍，但是在行业来讲不普遍。

** 为什么在业界，信托被认为不是个“乖孩子”？
信托几乎可以开展除了存款以外的所有业务，这一制度优势使得信托公司总是去干一些不符合国家政策的事情，不听国家的话。比如这几年银行这个乖孩子已经听国家的话不向房地产企业放贷了，信托公司这个时候却逆势而为为地产公司融资。国家又不能下令不允许这个坏孩子停止这些业务的开展，因为这个坏孩子的行为是符合“家规”的，符合国家的法律法规。


* annual income 100W+ RMB
科锐的薪酬报告
robertwalters的薪酬报告
mercer

1. 工作行业, e.g. IT
2. 岗位, e.g. a)销售总监, b)法务, general counsel没有年薪低于100万,c)财务和hr
3. 咨询业, e,g mckinsey，Boston


1.凭时间和体力算钱的，例如：

在以BAT为代表的科技公司，工作5-8年的技术岗位

在以MBB为代表的外资咨询公司，工作3-5年的咨询顾问

在一线城市大医院，工作10-20年的核心科室的医生



2. 靠管人或管钱挣钱的，例如：

- 以宝洁、通用、壳牌为代表的大型企业，工作7-15年的中层管理人员

- 以券商为代表的行研部门，工作5-8年的研究员，或者刚升的基金经理



3. 搞关系和资源去换钱的，例如：

a. 各种券商、基金、内资咨询的销售实权部门

b. 占了国企改制份股票的，股票账面随便上亿

c. 胆子大不怕死的副处级以上干部


comments:

比较清高，不太会虚情假意的，可以选第一类的职业。

比较能混，但还是有一点底线的，可以选第二类职业。

毫无底线，完全可以不要脸的，可以选第三类职业。


一般第一类的到200-300w就很难再往上了；能一年挣上千万及以上的，大多都在第三类，sad。




ref:
斯坦福大学的人生设计课
https://www.zhihu.com/search?type=content&q=%E5%B9%B4%E8%96%AA%E7%99%BE%E4%B8%87

* Financial status - kaiming
file:financial_status.org


* Note
** 兴业银行暂停一切房地产开发相关贷款的规定是真实的吗？
https://www.zhihu.com/topic/19592950/top-answers
作者：si se


各方力量博弈的结果。房产市场牛市时期，推动房产价格上涨的各力量之间利益是一致的，首先是地方政府，土地财政是基石，然后是投机资本，不惜倾家荡产作抵押也要投资，第三是房地产商，惜售捂盘大幅宣传，第四是银行，一边赚开发商的贷款利息一边赚房贷利息，第五连老百姓都自发加入买房行列，以房产自封身价。总的来说，房价持续上涨对于以上各方来说是双赢的，多赢的，因此各方对于房产市场都进行了切实的付出，以对自身影响来看，从五到一依次排列。所有力量共同作用下，房价必然会被推高到顶点，透支所有购买力，举例如果甲有400万不去买房而借给乙，乙会立即用这400万买房并将升值部分据为己有，于是甲就倾向于自己买房而不是出借，直买到无钱可买为止。当购买力被充分释放，楼市价格出现顶部波动时，各方力量从前期的团结一致开始发生利益背离，于是利益集团内部博弈。博弈中，对利润和风险最为敏感的投机资本首当其冲跑在最前面，如果能够成功撤资抛楼就完整保留了前期所有涨幅，打了一个大胜仗，但这样就伤害了船大难掉头的地方政府的利益，为了阻止游资率先跑路，政府就祭出了二手房交易税，有针对性地利用特权，将高位接盘的买房力量从游资的二手房里抢走，引导入自家的一手房市场。这里要说明的是，任何一个市场要维持长期牛市，都需要源源不断的资金注入，牛市前期我们看到的五组力量里有任何一方停止注资，那么另外几方可不是傻子。这时就要八仙过海各显神通，政府有政策托底，投机资金早已盆满钵满割一些肉无关疼痒，房地产商大不了出售牌照出国旅行，到最后你会发现最无计可施的就是银行，这也是美国房产市场波动后最先倒闭的为什么是房二美。更为欺负人的是，不仅大家用房贷将银行牢牢绑架在楼市中做垫背，一旦缺乏新鲜血液注资房产市场，大家第一个想到的有钱人还是银行。银行可不是傻子，它当然知道别人争相往外跑却要拿它的钱当垫脚石是什么意思。我朝的银行到底和美国不同，而一旦连银行都坐不住了那就是娘家这回也不给兜底了，同是娘家人还有亲疏之分，兴业这种股份制银行自然最先坐不住。如果说中央财政会给楼市托底的话，一经注入流动性，银行是再乐意不过把到手的钱投给房地产商再转给地方土地财政，把经济过热和实体经济倒挂的烂摊子丢给政府去伤脑筋的，问题是后者的脑筋已经伤够了，它发现再这样下去相当于中央财政流出的钱最终都贴给了地方政府，流动性养肥了老虎，还要辛苦去打，不打它吞进去的好处就不肯吐出来了，回想前任敞开国库大门各方利益均沾，这等好事再不会有了。---补充一下关于地方城商行，由于关系复杂不易理顺，可以简单地理解为地方政府自制了一台ATM机推到马路中央，储户把钱存进去-银行把钱优先贷给房产商-房产商¥给地方土地财政-买房人¥给房地产商-房产商¥还给银行-银行¥给储户。这样一条链，可以看到真实的两端是买房人-地方财政，银行与房地产商只是起到一个套利的作用，套利的的费用也在买房人这端。当买房人买不起，链条左端断裂，那么银行还不出给储户，最终就要链条右端的地方政府怎么吃进去的怎么吐出来。中央收紧流动性的最终结果就是这个。因此在没把握时，地方一般鼓励开发商不要找自家兜底的城商行来借，找个好欺负的借，卖不掉还不出大不了就赖着，资金进了地方财政的口袋，一般别想它掏出来。明确了这一点，如果碰巧贵行既不是城商行，又不是四大，那么相当于地方和中央之间一个姥姥不疼另一个舅舅不爱，这时贷款给开发商是没有任何一个亲戚肯给撑腰的。----更新。题主更新了问题，初始表述是如何看待兴业喊停这一现象。更新答案。题目附上的这张实际上并不是决策文件，而是执行通知，相当于是发给银行基层，重点在于告诉基层员工该怎么做，不需与之探讨缘由。为了凸显任务执行的必要性，通常会给出一些比较直观简单拍脑门的因果，起到师出有名的作用，如原文中三点（但在经济下行、资产泡沫、政策收紧云云..）。可以理解为＂为了迎接新一年，我们要如何＂类因果模式，不必深入。这次暂停是不是真的，是真的。以这样一张基层通知受众之广，绝称不上机密，内容之普通，都不能算业内先行---居然能够让市场闻风破位关键是利空出尽二次下行！证券从业人员不是第一趟进银行的刘姥姥，市场对这种不是新闻的新闻平白无故有这么大反应，如果被行业基层理解为＂咱见过的绝密文件这回也给市场开了眼界＂未免呵呵。想一想银行在这个时间节点认可传闻相当于公开表态，市场的连挫，将这个表态解读为2会前央行手握流动性紧箍咒，直指房产-地方财政这条产业链，吹的什么风

** 国家大力扶持中小微企业发展
** 实体店是不是越来越难赚钱了？
no, big fish eat small fish
- 难赚钱的不是实体店，只是小个体户而已。
- 网店冲击的就是小业主

** 基金经理和股票操盘手 VS 散户？
大多数人买股票都是看报纸，听新闻，听朋友邻居推荐，从来不自己研究，我只想问一句，那些推荐你的人靠股票赚了大钱吗？
你听不懂股票的人推荐，不亏才有鬼！其次，散户太喜欢短线跟技术分析，这跟我们媒体也有关系，媒体也好，电视上的分析师也好，
天天谈技术面，技术面有没有用，当然有用，但是不是那么用的，买股票说白了是 *买公司* ， *买行业* ，举个例子，2000年你随便买个跟外贸，地产相关的股票，那么到2010年你肯定是赚的
但是2010年后你买任何地产相关，外贸相关的股票，除非之后重组转型了，否则一定跑输指数！
- 其实股票是买公司，买行业，选对行业，选对行业里的龙头，不断跟踪才是王道
- ！2002年以后去买互联网股大多数是赚的，但是到底买新浪赚得多，还是腾讯赚得多，还是网易赚得多只有天知道了，所以需要不断跟踪，指望买完就不看，长期持有的根本不是价值投资
- 阿里够强大了，12年还差点因为微信被颠覆，所以如果有人告诉你买个低估值股票然后一辈子不用看那人一定不懂股票
- 希望要入股市的朋友好好读读各种书，不只是巴菲特的书，国内有把巴菲特理论庸俗化的倾向，认为只要买低估值的股票长期持有就是价值投资, 如果这么简单，何来巴菲特，随便找个小学生用加减乘除算
- 如果有人告诉你有个地方，你什么也不用做，进来就能捡钞票，你信么，既然你不信有这么好的地方，怎么现在又相信股市是可以什么也不学习就进来捡钱的呢？
- 观察政策，尤其货币政策，如果货币政策转向，同时指数的图形出现问题，那就是卖点了
- 中国经济就是个强周期股，导致必然熊长牛短，只有少数股票能长牛，而未来第三产业占GDP比重会越来越大，第三产业里必然出长牛，可以平抑A股波动，二是因为A股只能做多不能做空，导致牛市一来就价值透支，这点现在还没有改变，只有当A股有了做空机制，波动得到平抑之后可能才能出现长牛
- 巴菲特做的股票市场是由市场决定的，而a股是由政策决定的
- 中国行业很好选，国家领导人天天喊，2010年底韩把传媒产业建设成支柱产业，2014年底喊互联网+，另外就是多看书就知道全世界哪些是前沿的行业，谷歌，苹果，阿里，腾讯的触角在往哪儿伸，美国人在关注什么产业。至于轮动，我反正做不好，耐心拿最牛的行业就够了
- 股票大作手回忆录

作者：Qianyuan Xie
链接：https://www.zhihu.com/question/23180113/answer/46602427




- 每股盈利 :: 企业在过去12个月的净利润减去优先股股利之后除以总发行已售出股数。

每股净利润的方法有：
⒈全面摊薄法。全面摊薄法就是用全年净利润除以发行后总股本，直接得出每股净利润。
⒉加权平均法。在加权平均法下，每股净利润的计算公式为：每股净利润=全年净利润 /（发行前总股本数+本次公开发行股本数 * （12-发行月份）/ 12 + 回购股本数 * （12-回购月份）/ 12）。

股权质押

股权质押融资，是上市公司股东们的独门武器

股票质押式回购交易: 手中的股票向证券公司借钱。

任何借钱和抵押的形式，所借得款项都不会按照抵押物的市值来估计。比如用一只10万的劳力士去典当行借钱，那么你可能只借到4万，剩下的6万中包含折旧费用，绝当（逾期不还）后的资金沉淀成本以及周转率等等问题。股票质押的规则也如是，不过说法叫做质押率。质押率=初始交易金额/质押标的证券市值。对于流通股来说，通常主板股票质押率为55%，中小板50%，创业板45%。质押率会根据交易期限、是否限售股等条件进行调整。

除了质押率，另外一个保障证券公司利益的限制就是两线，即警戒线和平仓线。当质押股票市值/借款金额≤警戒线，则需要关注风险，及时要求资金融入方追加担保品。

警戒线一般被定在140%-150%。比方说，你用100万的股票质押，向证券公司借款50万，如果股票跌到只剩70万，50/70=140%，达到警戒线范围，这时候，就需要借款人继续质押股份或者用现金解押。

平仓线一般被定在120%-130%。当质押股票市值/借款金额≤平仓线，
资金融入方须于下一个交易日采取提前购回、追加担保品等履约保障措施，
使得履约保障比例恢复至警戒线水平及以上。达到平仓线，
且资金融入方无法提供相应的履约保证措施的，
证券公司将向交易所提交违约处置申报，
经交易所处理通过后，进行强制平仓处理。
违约处置所得资金优先偿还融出方，资金如有剩余，将返还给融入方。也就是说，一旦被平仓，很可能血本无归，而且公司都有可能不是自己的了。

*股票质押时间到了，没钱解押，也没有多余的股票质押，眼看着就要被强制平仓，怎么办？国家借给你*






杠杆: leverage 
用很小的启动资金，通过信贷（借钱）的方式，放大投资的结果

生活中我们常常用到杠杆，比如按揭买房，分期买车等等，虽然手头钱不够买车买房，但是我们可以用未来挣到的钱

业经营也会用到杠杆，向银行借贷更是司空见惯，如以杠杆著称的房地产业，负债率极高，因为那样可以借用杠杆提高企业的经济效益，获得更高的ROE，放大利润，快速扩大股东的利益

股市里有句话： “新手死于追高，老手死于抄底，高手死于杠杆。”如果说你投资能力很强，买入一只10元的股票，你相信它可以涨到20元，all-in，可以赚1倍。但是你决定上个十倍杠杆，准备赚它10倍，最后股价确实涨到20块了，但是你破产了。
1.炒股中有两个地方会要关注杠杆问题：一是所买公司的财务杠杆，二是自己融资买股票的杠杆比例；

2.对于你所买的公司，务必关注杠杆过高的风险，尤其是现金流糟糕情况下的高杠杆；

3.对于个人用杠杆做投资，务必计算你能亏得起多少，再考虑借钱。
https://www.zhihu.com/question/20979324/answer/136807763

股市在中国只是一个融资市，并不是经济的晴雨表

- 正回购 :: 持有债券，抵押给交易所，向你借钱的人

国海债券门事件，本质上就是“债券代持”业务在高杠杆下的风险爆发。
** 财务指标
* yahoo finance
** fund
利用晨星基金网选择晨星评级三年、五年的五星或四星基金，并从中找寻高夏普比率，高阿尔法系数，低晨星风险系数的基金；进一步考察基金经理的变动情况，找寻基金经理稳定且基金规模适中的基金。进一步利用晨星股票投资风格箱，做好资产配置，大盘、中小盘、平衡型基金各自优选。”并据此长期投资华安逆向策略、长信系量化基金、兴全轻资产及其场内双胞胎基金合润B、中欧潜力价值（将其视为中欧价值发现的双胞胎基金）等基金。
https://mp.weixin.qq.com/s/3KAUcRLo_JDyBFWJ9C2qBQ

价值型基金
公募基金经理有
曹名长
、丘栋荣、林鹏、周可彦四位

recommended
中欧价值发现混合A(166005
  + 　业绩比较基准：80%×沪深300指数+20%×上证国债指数

** New Retails
** [[https://help.yahoo.com/kb/finance-for-web/started-yahoo-finance-sln3642.html?impressions=true][Getting started with yahoo finance]]

* Glossary
- 一级市场（Primary Market / New Issue Market） :: 是筹集资金的公司或政府机构将其新发行的股票和债券等证券销售给最初购买者的金融市场。

* Cryptocurrencies


Lloyds BankLloyds Bank


There has been a great deal of coverage recently about Bitcoin, “blockchain” and other elements of cryptocurrencies. This raises many questions about what these things are, how they work and whether or not investors should consider them as part of their portfolios.
** Conventional currency

To understand what a cryptocurrency is, we first need to look at more conventional currencies, and then consider the differences.

If you look at a £5 note, written on the side that has the Queen’s head are the words, 
“I promise to pay the bearer on demand the sum of five pounds”. 
This harks back to how cash as we understand it today, evolved. 
An individual would trade for goods with gold often being used as a commonly accepted payment.

Simplifying history somewhat, rather than carrying gold around all of the time, people would place it with someone who had sufficient means to keep it safe; an early form of bank. That “bank” would give the depositor a receipt confirming how much gold had been deposited.

These receipts had to be fairly durable, and difficult to forge. This enabled traders to pay for goods with receipts rather than bits of gold. The gold stayed in safe storage and people exchanged bits of paper instead.

It was a relatively short step from this to an official form of money governed by a central bank. The central bank would hold huge amounts of gold to act as collateral for the receipts/ cash that was flowing around in trade.

Over time, the “gold standard” as it was called, became obsolete as the central bank was able to print new money should it need to and everyone (in most countries) had sufficient trust in the currency for it to be widely accepted as a form of payment. This sort of money is known as fiat money, taken from the Latin “fieri” meaning arbitrarily decided or chosen by decree.

Jump forward in time a little further and the vast majority of money is not in paper cash form, but in numbers held on computer: salaries transferred, bills paid, and savings all held on electronic accounts with the understanding that the currency is backed by the central bank.
Central bank power

This puts central banks in a position of both great responsibility and great power. As well as controlling how much cash is printed, they act as the lender of last resort, i.e. the bank that lends to all the commercial banks.

The Bank of England can increase or reduce the interest it charges commercial banks in order to discourage or encourage borrowing and spending respectively. By working with government policymakers, the Bank of England can help to guide the country through economic ups and downs, as we have seen in the lowering of interest rates and electronic printing of money (i.e. “quantitative easing”) since the financial crisis 10 years ago.

The key point for an investor is that, as well as an economic guardian, the Bank of England also oversees the value of the pound.
Cryptocurrencies - outside of central bank control

Cryptocurrencies don’t have a central bank or an underlying asset. They are, in effect, just a number on a computer screen that, in theory, anyone can buy with dollars, pounds, euros or whatever.

If enough people want to buy them, then their value will rise, if not, it will fall. There is no central bank to step in and try to influence the cryptocurrency’s value.

This is also seen as one of the major advantages of a cryptocurrency: its value cannot be influenced or interfered with (depending on your perspective) by any national authority such as a central bank.
** So who does control it?

From this point on, the article will address the points to Bitcoin as that is the 
best-known of the numerous cryptocurrencies.

Bitcoin is run as a peer-to-peer network that everyone can contribute to, but no one owns. 
Software programmers can download the coding that supports the exchange of Bitcoins 
and offer improvements. There are thousands of contributors these days, 
all of whom have fairly equal status in that they all hold the same software and contribute to the same network.

Think of it like the Internet; anyone can use it, but no one owns it out-right. 
There are lots of different software types being used on the Internet, 
the most efficient and successful such as HTML or PERL are widely adopted 
because they work fairly well in delivering websites and services. 
But neither of them changes the basic structure or existence of the Internet itself, 
and both of them are “open source”, i.e. 
freely available to anyone to use as they wish without restriction.
** Who created Bitcoin?

The person accredited with creating Bitcoin is referred to as *Satoshi Nakamoto*, 
though the veracity of that name and the person’s true identity are clouded in mystery. 
According to Bitcoin.org, Nakamoto came up with a Bitcoin specification and proof of concept in 2009, 
before “leaving the project in 2010 without revealing much about himself”. 
Since then, much as has been the case with Sir Tim Berners-Lee’s invention, 
the World Wide Web, countless developers have descended on Bitcoin to bring it to where it is today.
** Blockchain security

This might lead one to question the security of such a system, 
but it is this very trait that affords cryptocurrencies such a relatively high level of security.

Imagine you have a shopping list held online. 
On its own, it’s vulnerable to hackers and other ne’er-do-wells. 
Such people might break through the security barriers and mess around with your shopping list.

To prevent this, you could have everyone in your family keep an online copy of the shopping list in 
completely different locations on the Internet. 
The different shopping lists can be compared against each other so that 
if a lorry-load of marzipan suddenly appears on one of the lists, 
then that is obviously a result of unwelcome interference. 
It is removed and the shopping lists all tally.

In short, it’s simple for a hacker to corrupt one or two versions of the shopping list, 
but the more copies of the shopping list there are, the harder it is to corrupt all of them consistently and thereby overcome the process in which the different shopping lists are compared and corrected.

With Bitcoin, the ledger of every transaction that has taken place is recorded 
and that record, the ledger, is duplicated thousands of times across Bitcoin users the world over, 
making it far more trouble than it’s worth for a hacker to try to corrupt. This ledger history and comparison system is referred to as “Blockchain”.
A user’s place in the network

Users get hold of Bitcoins by installing an application (i.e. computer programme) on their phones or computers, or by creating an account online. This application is called a “Wallet” for obvious reasons.

The wallets have been created by the computer programmers mentioned above. They are free to download and access.

A typical installation process takes a couple of minutes, requires an email address, password (measured for how difficult it would be for someone to guess) and a PIN code (i.e. four-digit identification number).

Once that’s done, the user can upload fiat money (pounds, dollars, euros etc.) to the wallet and use that to buy Bitcoins from another wallet owner whom they know has Bitcoins to sell, or through an exchange.

It takes an average of 10 minutes for the purchase (or sale) of Bitcoins to be confirmed as this allows time for various other copies of the Blockchain to confirm that they’ve recorded the transaction, making it difficult to reverse i.e. cheat the system.
What’s in it for the software providers?

To begin with, Bitcoins, after that, fees.

The system is set up so that the people who provide software services either in the form of wallets, exchanges or online storage, can earn the odd Bitcoin here and there once they’ve delivered a prescribed amount of service. This process is called mining (you can probably guess why).

As the system matures, and increasing numbers of “miners” contribute, it becomes more difficult to earn Bitcoins through this process. That’s deliberate as it offered a greater incentive to contribute when the system was embryonic and in need of software support.

The miners can, however, continue to earn fees by charging for their services, though competition is steep and that has helped to keep fees down to date.

In theory fees could be avoided altogether by users writing the software to create their own wallets, or by finding someone with whom they can trade and avoid most of the online services that the contributors provide. But that would mean being a computer software engineer and partaking in the equivalent of a private trade which might not be at as favourable a price as one that might have been achieved by using an exchange.
How many Bitcoins will be produced?

The maximum number will be 21 million, but with the current number in circulation close to 17 million, and the rate at which they are being added having slowed (as was intended from the original design), it is likely to be years before the maximum is reached.

Before then, Bitcoins can be divided down to 0.00000001 of a Bitcoin. At the time of writing, that equates to around one millionth of a US cent, in theory affording this cryptocurrency plenty of scope to deal with rising value.
But cryptocurrencies are not invulnerable

There is potential weakness in the exchanges where people deposit money and trade Bitcoins. Hackers have managed to break through the security systems of these exchanges and steal money or Bitcoins.

The most notorious instance was that of “Mt. Gox” from which $460m disappeared in 2014, sending the company into bankruptcy. While there was clearly some nefarious activity involved, the slapdash running of the company played a big part in its demise.

These exchanges have the equivalent assets and responsibilities of banks, so their security systems need to be just as robust. Mt. Gox was something of a wake-up call for cryptocurrency exchanges, and has led to improved security.
Down the back of the sofa

However, the most common form of loss, according to bitcoin.org, is that of people losing or forgetting their wallet details. Once that happens, there is no way that anyone can spend or sell the Bitcoins that are in the given wallet, so they effectively drop out of circulation permanently.
Why is Bitcoin so highly valued?

Bitcoin’s original value was based on its inherent quality of being international and out of the reach of central banks. It created a currency by the people, of the people and that had been predicted in the 1997 book “The Sovereign Individual”, by William Rees-Mogg and James Dale Davidson.

This initial attraction was overtaken by momentum in 2017 as more and more people saw the stratospheric rise of Bitcoin’s equivalent value in dollars, leading to a rush of people buying Bitcoins in the hope of multiplying their assets.

To say that this was a high risk strategy is a colossal understatement. Previous sharp rises along similar lines have included the housing bubble of 2007, internet bubble of 2001, the stock market bubble of 1929, the Mississippi property bubble of 1721, and the Tulip bubble of 1637.

But there is at least one difference between most of those rises and that of Bitcoin: the cryptocurrency’s rise has been far quicker and steeper.

While it might be tempting to regret having missed out on the value created out of thin air for holding such an asset, a similar thought could be applied to not betting on the winner of the 4.30pm at Catterick.

Sure enough, the risks of buying such a stratospherically rising asset proved to be a high-risk strategy to say the least. The dollar value of Bitcoin plummeted by more than 50% in the early part of 2018.
What are the risks?

Putting aside the sharp fall in dollar value of Bitcoin, cryptocurrencies have a number of vulnerabilities.

Firstly, they are fairly embryonic at the moment, so sharp movements in value are bound to occur, both down as well as up.

What’s more, as China demonstrated in September 2017, a country could ban the use of cryptocurrencies. At the moment this is easier for autocracies to implement, but that could change if cryptocurrencies lead to tax avoidance or evasion.

Should this happen, then it would not take a great stretch of the imagination to conceive of leading economic nations getting together to restrict the use of cryptocurrencies.

One organic restriction that has already begun is that of competition. The other cryptocurrencies being developed include Ethereum, Ripple, Litecoin, Dash, NEM, Monero and Zcash. As with all developing offerings, some will blossom or specialise, others will merge or fail.
Conclusion

So cryptocurrencies are just forms of money that only exist on computers. In this way, they are like most of the money that everyone deals with on a daily basis.

They are not subject to government interference, but are not immune to it, and that poses a huge potential risk to valuations and integrity.

Some people will have done very well out of Bitcoin if they bought at the right point and sold similarly. But without intrinsic value or the ability to project future growth, cryptocurrencies have a long way to go before they feature in our investment considerations.

The financial crisis ought to remain fresh in investors’ minds. In his excellent book on what happened, “The Big Short”, Michael Lewis related the story of a fund manager visiting regions of the US to see if there was a housing bubble. On one occasion he met a pole dancer who had borrowed money to buy four houses and a condominium. She was able to do this because house prices were rising very quickly, hence she felt she could always refinance. She was wrong.

In a post on Bloomberg just before the price of Bitcoin slumped from $17,000 high, Macro Strategist Mark Cudmore told of a pole-dancing instructor who was “focusing more of her time informing people how to ‘invest’ in Bitcoin”. He went on to quote her breathtakingly naïve claim, “The good thing is when it goes down, you can buy some more, and you know it’s going to go up at some point”.

She would have done well to read “The Big Short” not to mention the first sentence of our “Important information” below.




Forecasts of future performance are not a reliable guide to actual results in the future, neither is past performance a reliable guide to future performance.

The value of investments, and the income from them, may fall as well as rise and cannot be guaranteed. Any views expressed are our in-house views as at May 2018. Investment markets and conditions can change rapidly and the views expressed should not be taken as statements of fact nor relied upon when making investment decisions. This document may not be used, copied, quoted, circulated or otherwise disclosed (in whole or in part) without our prior written consent.

Lloyds Bank plc. Registered Office: 25 Gresham Street, London EC2V 7HN. Registered in England and Wales, number 2065. Authorised by the Prudential Regulation Authority and regulated by the Financial Conduct Authority and the Prudential Regulation Authority under number 119278.
Clock
Book an appointment

Get in touch with one of our Private Banking and Advice Managers.

The service is open to you if you have a minimum of £100,000 in savings, investments, and/or personal pensions, or a sole annual income of at least £100,000

No charges for the initial meeting to discuss your individual circumstances and objectives.

No obligation to take any of our services or products.

Before any services or products are provided to you we will explain what advice we can give and what products and services this covers, and any advice or product charges that apply and agree these with you.


**  Taxes for Capital Gains and Income
https://www.bitcoin.tax/
HMRC has warned that Bitcoin investors may need to pay Capital Gains Tax on their profits
http://www.alphr.com/cryptocurrency/1008865/bitcoin-tax-cryptocurrency-hmrc-capital-gains-ethereum

** Revenue and Customs Brief 9 (2014): Bitcoin and other cryptocurrencies 
-    *when Bitcoin is exchanged for Sterling or for foreign currencies* , such as Euros or Dollars, 
no VAT will be due on the value of the Bitcoins themselves

https://www.gov.uk/government/publications/revenue-and-customs-brief-9-2014-bitcoin-and-other-cryptocurrencies

*** Purpose of this brief

This brief sets out HM Revenue and Customs (HMRC) position on the tax treatment of income received from, 
and charges made in connection with, activities involving Bitcoin and other similar cryptocurrencies, 
specifically for VAT, Corporation Tax (CT), Income Tax (IT) and Capital Gains Tax (CGT).

*** Readership

Anyone making charges or otherwise receiving income, in whatever form, 
from activities involving Bitcoin (or other cryptocurrencies), including:

-    Bitcoin miners
-    Bitcoin traders
-    Bitcoin exchanges
    Bitcoin payment processers
    other Bitcoin service providers

*** Background

Bitcoin is seen as the world’s first decentralised digital currency, otherwise known as a ‘cryptocurrency’. 
The advent of cryptocurrencies such as Bitcoin is a new and evolving area 
and determining their legal and regulatory status is ongoing. 
Cryptocurrencies have a unique identity and 
cannot therefore be directly compared to any other form 
of investment activity or payment mechanism.

HMRC understands that Bitcoin operates via a peer to peer network, 
independent of any central authority or bank. 
All functions such as issue, transaction processing and 
verification are managed collectively by this network. 
All Bitcoin transactions are recorded in a shared public database 
called a ‘block-chain’. 
New Bitcoin is produced when a new block is attached to the chain. 
A new block can only be added to the chain when the 
answer to a complex cryptographic algorithm is solved. 
Participants in this activity are known as ‘miners’.

As well as mining, activities include the buying and selling of Bitcoin 
and providing exchange facilities for parties to trade Bitcoin with recognised currencies. Bitcoin may be held as an investment or used to pay for goods or services at merchants where it is accepted. In the UK, there are already a number of outlets, including pubs, restaurants and internet retailers, that accept payment by Bitcoin.
VAT treatment of Bitcoin and similar cryptocurrencies

As an EU tax, the VAT treatment for cryptocurrencies adopted 
by the UK must be consistent with any treatment that may eventually be implemented across the EU.

Given this, the evolutionary nature of these cryptocurrencies and the legal 
and regulatory environments in which they currently operate, 
this brief outlines HMRC’s provisional VAT treatment pending further developments; 
in particular, in respect of the regulatory and EU VAT position. 
Taxpayers can rely on the VAT treatment outlined below unless and until HMRC announces any changes. 
Any changes will not apply retrospectively.

For VAT purposes Bitcoin and similar cryptocurrencies will be treated as follows below, 
this in no way reflects on how they are treated for regulatory or other purposes:

-    income received from Bitcoin *mining activities* will generally be outside the scope
 of VAT on the basis that the activity does not constitute an economic activity for VAT purposes 
because there is an insufficient link between any services provided and any consideration received
-    income received by miners for other activities, such as for the provision of services 
in connection with the verification of specific transactions for which specific charges are made, 
will be exempt from VAT under Article 135(1)(d) of the EU VAT 
Directive as falling within the definition of ‘transactions, including negotiation, concerning deposit and current accounts, payments, transfers, debts, cheques and other negotiable instruments’
-    *when Bitcoin is exchanged for Sterling or for foreign currencies* , such as Euros or Dollars, 
no VAT will be due on the value of the Bitcoins themselves
-    charges (in whatever form) made over and above the value of the Bitcoin for 
arranging or carrying out any transactions in Bitcoin will be exempt from VAT under Article 135(1)(d) 
as outlined at 2 above

However, in all instances, VAT will be due in the normal way from suppliers of any goods or services 
sold in exchange for Bitcoin or other similar cryptocurrency. 
The value of the supply of goods or services on which VAT is due will be the sterling value
 of the cryptocurrency at the point the transaction takes place

*** CT, IT and CGT treatment of Bitcoin and similar cryptocurrencies

As with any other activity, whether the treatment of income received from,
 and charges made in connection with, activities involving Bitcoin and other similar
 cryptocurrencies will be subject to CT, IT or CGT depends on the activities and the parties involved.

Whether any profit or gain is chargeable or any loss is allowable will
 be looked at on a case-by-case basis taking into account the specific facts. Each case will be considered on the basis of its own individual facts and circumstances. The relevant legislation and case law will be applied to determine the correct tax treatment. Therefore, depending on the facts, a transaction may be so highly speculative that it is not taxable or any losses relievable.. For example gambling or betting wins are not taxable and gambling losses cannot be offset against other taxable profits.

For *businesses which accept payment for goods or services in Bitcoin* 
there is no change to when revenue is recognised or how taxable profits are calculated.

    CT - the profits or losses on exchange movements between currencies are taxable. For the tax treatment of virtual currencies, the general rules on foreign exchange and loan relationships apply. We have not at this stage identified any need to consider bespoke rules. For companies, exchange movements are determined between the company’s functional currency (usually the currency in which the accounts are prepared) and the other currency in question. If there is an exchange rate between Bitcoin and the functional currency then this analysis applies. Therefore no special tax rules for Bitcoin transactions are required. The profits and losses of a company entering into transactions involving Bitcoin would be reflected in accounts and taxable under normal CT rules
    IT - the profits and losses of a non-incorporated business on Bitcoin transactions must be reflected in their accounts and will be taxable on normal IT rules
    Chargeable gains: CT and CGT - if a profit or loss on a currency contract is not within trading profits or otherwise within the loan relationship rules, it would normally be taxable as a chargeable gain or allowable as a loss for CT or CGT purposes. Gains and losses incurred on Bitcoin or other cryptocurrencies are chargeable or allowable for CGT if they accrue to an individual or, for CT on chargeable gains if they accrue to a company.

*** Future implications

The tax treatments outlined in this brief are for tax purposes only. 
They in no way reflect on the treatment of cryptocurrencies for regulatory or other purposes.

Given the evolutionary nature of these cryptocurrencies, HMRC will issue further guidance as appropriate.

Issued 3 March 2014


* References
[[https://program-think-mirror.github.io/][编程随想的博客]]

BT Sync 的同步密钥是 B7P64IMWOCXWEYOXIMBX6HN5MHEULFS4V
国富 论 An Inquiry into the Nature and Causes of the Wealth of Nations 
short name: the wealth of nations

经济学	Economics	(美) 保罗·萨缪尔森
(美) 威廉·诺德豪斯	简体PDF(第18版 扫描版)	2014-02-13	简介
经济学原理	Principles of Economics	(美) 格里高利·曼昆	简体PDF(微观分册 第5版 扫描版)
简体PDF(宏观分册 第5版 扫描版)
简体EPUB(微观分册 第3版 插图版)
简体MOBI(微观分册 第3版 插图版)
简体TXT	2013-02-22
2013-02-22
2015-02-14
2015-02-14
2016-05-02	简介
宏观经济学	Macroeconomics	(德) 鲁迪格·多恩布什	简体PDF(第7版 扫描版)	2015-07-12	简介
高级宏观经济学	Advanced Macroeconomics	(美) 戴维·罗默	简体PDF(第2版 扫描版)
英文PDF(第1版 扫描版)	2014-07-15
2018-06-23	简介
中级微观经济学
——现代观点	Intermediate Microeconomics
——A Modern Approach	(美) 哈尔·范里安	简体PDF(第8版)
英文PDF(第8版)	2015-07-12
2018-06-23	简介
微观经济分析	Microeconomic Analysis	(美) 哈尔·范里安	简体PDF(第3版)	2014-07-15	简介
就业、利息和货币通论	The General Theory of Employment, Interest, and Money	(美) 约翰·梅纳德·凯恩斯	简体PDF
简体MOBI	2014-02-22
2015-02-14	简介
人的行为
——经济学专论
其它中文名：
人类行为的经济学分析	Human Action
——A Treatise on Economics	(奥) 路德维希·冯·米塞斯	英文EPUB	2018-09-15	简介
个人主义与经济秩序	Individualism and Economic Order	(英) 弗里德里希·哈耶克	简体PDF
简体EPUB
简体MOBI	2013-04-10
2013-09-13
2015-02-14	简介
经济发展理论	The Theory of Economic Development	(奥) 约瑟夫·熊彼特	简体TXT	2016-05-17	简介
企业的性质
其它中文名：
公司的本质	The Nature of the Firm	(英) 罗纳德·科斯	英文PDF	2018-09-18	简介
社会成本问题	The Problem of Social Cost	(英) 罗纳德·科斯	英文PDF(扫描版)	2018-09-19	简介
市场经济
——大师们的思考	The Market Economy
——A Reader	(美) 詹姆斯·多蒂
(美) 德威特·李	简体PDF(扫描版)	2013-04-09	简介
以自由看待发展	Development as Freedom	(印度) 阿马蒂亚·森	简体PDF(扫描版)	2013-04-09	简介
短缺经济学	Economics of Shortage	(匈) 雅诺什·科尔奈	简体PDF(扫描版)	2015-01-11	简介
经济学原理	N/A	杨小凯 (原名：杨羲光)	简体PDF(扫描版)	2015-07-12	简介
经济学原理
其它中文名：
国民经济学原理	Principles of Economics	(奥) 卡尔·门格尔	简体PDF(扫描版)
英文PDF	2018-09-15
2018-09-15	简介
自然价值	Natural Value	(奥) 弗里德里希·冯·维塞尔	英文PDF	2018-09-15	简介
资本与利息	Capital and Interest	(奥) 欧根·冯·庞巴维克	繁體PDF(第1卷 掃描版)	2018-09-05	简介
利息与价格	Interest and Prices	(瑞典) 克努特·维克塞尔	英文PDF(扫描版)	2018-09-19	简介
卡尔·马克思及其体系的终结	Karl Marx and the Close of His System	(奥) 欧根·冯·庞巴维克	英文PDF(扫描版)	2018-09-22	简介
资本论	Capital	(德) 卡尔·马克思	简体PDF(大字版)	2018-09-05	简介


集思录
[[中证指数有限公司]]
https://www.lixinger.com/


经济学原理》，《货币银行学》、《资本论》、《国富论》
《K线基础教程》，《外汇交易三部曲》,《道氏理论》《索罗斯》
The Inner Voice Of Trading
财经国家周刊

中国经济周刊


财经新世纪周刊

证券市场周刊

股市动态分析

互联网周刊

IT时代周刊
经理世界
https://www.imf.org/en/Publications/WEO/Issues/2018/07/02/world-economic-outlook-update-july-2018
* 资产证明
* 旅游签证资金证明
英国旅游签证一般最少需要多少的存款证明?

如果这样的话5-10W就够了。 至于存款问题，最好是存在自己名下的账户里。
旅游签证不要求定期存款，但最好能提供3-6个月的银行对账单。

问： *学生* 申请英国旅游签证的资产证明问题?

答：出示父母财产作为资产证明递交使馆时一定要注意，你的户口一定要和父母在同一本户口本上，如果不是，就需要做公证了。

问： *学生* 去英国旅游签证需要资产证明吗

答：要父母的在职与财产证明

- bank statements 银行对账单

- building society book 房屋互助协会存折

- proof of earnings such as a letter from employer confirming employment details (start date of
employment, salary, role, company contact details) 收入证明比如工作证明确认工作详细信息
(入职日期、工资、职位、公司联系信息)

- where a third party (who is either in the UK or who will be legally in the UK at the time of your
visit) is providing financial support to you e.g. a business, a friend or a relative, documents to
show they have sufficient resources to support you in addition to themselves and any
dependant family should be provided 如果第三方(在英国或您赴英期间在英国合法停留的
个人或机构)为您提供资金支持,比如公司、朋友或亲戚,需要提供材料显示他们有充足
资源支持您以及他们自己和任何由其供养的家人

* 跨境人民币汇款
优汇通BOC
- 投资移民和海外购房置业

https://www.zhihu.com/topic/19629503/top-answers

*美国寄到中国：*
transferwise
（按成本排序）
1. 跟需要美金交学费的同学直接换，帮国内朋友免费买东西（友情提示美国不退税）
2. citi卡存美金拿回中国atm取人民币
3. 纽约中行汇回国
4. 写一张check拿回国换 需要一个月左右
5. 其他美国的银行汇回国
6. xoom, 即时到账， 每天限额$2999（最新最方便）
7. 西联汇款

*中国寄到美国：*
1. 支付宝汇款（推荐）
2. 中国的银行汇款


链接：https://www.zhihu.com/question/22702514/answer/71979669
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
** 结汇

1易结汇
2义乌个体户结汇
3招行香港一卡通结汇
4香港离岸帐号结汇
5用直系亲属的额度结汇
补充一下，据说现在用直系亲属结汇会在某些地区出问题，所以一般人方便起见我建议办理招行香港一卡通，办理完成后收款，可以在招行把外币刷回国内
** Send money across the world, Paypal UK
https://www.paypal.com/uk/webapps/mpp/send-money-abroad

* 杠杆类的投资
如白银、黄金、外汇、期货
* 晨星公司 (Morningstar)
主要客户分为四大类:
1. 理财顾问:晨星给理财顾问提供软件，最主要的产品就是Morningstar Advisor Workstation。
通过晨星，理财顾问可以给客户模拟投资组合，构建投资组合，做投资决策，甚至招揽客户。

2. 资产管理: 顾名思义，这是为买方服务，包括资产管理公司，基金公司等等。晨星主要为买方提供研究成果，主要产品为Morningstar Data和Morningstar Direct。
3. 养老金：和为买方提供的服务类似，晨星为养老金（主要是美国的401(k)养老金计划）提供投资方案，帮助管理养老金。主要产品包括Retirement Solutions和Investment Advisory services。
4. 独立投资者：主要给独立投资者提供的就是晨星的官网，官网有免费可供浏览的内容，但大部分只向会员开放。

Morningstar最受欢迎，也是最赚钱的产品和服务前三名分别是

- Licensed Data就是Morningstar收集和标准化的各种金融数据。包括上司公司财务报表和非财务报表数据，基金，指数，衍生品等。数据非常广泛，几乎已经涵盖了世界上绝大部分的市场。其实Google Finance, 还有windows 8/10里面那个财经小磁铁里的东西都是Morningstar的数据。
- Advisory Workstation就是给专业的个人理财顾问或者投资顾问使用的一个软件，可以构建portfolio啦，筛选投资工具。这个软件更多的在美国使用。
- Morningstar Direct则是一般给机构投资者准备的，应该是内容最丰富的一个产品了。不仅有上面提到的数据，还有研究报告，分析工具，是一个全方位的平台。

作者：Leo同學
链接：https://www.zhihu.com/question/23585167/answer/28573142

** 基本面分析
- 分析方法 & 评级方法
股票: 巴菲特的护城河理论

* Banks
五大国有银行：中国银行、农业银行、工商银行、建设银行、交通银行；
四家股份制银行：浦发银行、招商银行、兴业银行、平安银行；
三家城市商业银行：上海银行、杭州银行和北京银行
** BOC
*** [[http://www.boc.cn/ebanking/bocmbs/mbs1/201804/t20180423_12061379.html][中银慧投]]--个人智能投资顾问

产品介绍

中银慧投根据投资者的风险承受能力、预期投资期限等要求，运用一系列智能算法、投资组合优化模型等，为个人客户提供智能化和自动化的资产配置建议。

中银慧投包括两大服务:
- 定制智能组合: 结合个人客户风险偏好和流动性偏好，为每一个客户构建个性化的标准智能基金组合；
- 存量资产诊断: 对个人客户存量资产进行诊断，给出调整优化建议。
**** 产品特点

1.服务大众

通过先进智能化科技手段，降低投资者门槛，提供普惠式的投资顾问服务，首次申购起点金额10000元人民币，追加起点金额2000元人民币。

2.严守风险收益匹配原则

以科技手段固化风险适配规则，始终只向客户提供与其风险识别能力和风险承担能力相适应的资产配置服务。

3.个性化服务

通过人工智能技术，坚持“了解客户”和 “了解产品”，为每一位客户量身定制个性化的资产配置方案。

4.全天候服务

支持7X24小时不间断服务。

5.交易渠道便捷

客户可通过中国银行手机银行渠道随时、随地办理中银慧投业务。

服务渠道与时间

中银慧投交易渠道为手机银行，交易时间支持7X24小时不间断服务。
*** 中银理财
**** 服务对象

1.在我行金融资产总额达到 *20万元人民币* 以上（包括本、外币存款、各类理财产品、债券、基金、保险、纸黄金、一对多理财专户、证券集合资产管理计划、客户集合信托、证券第三方存管保证金余额以及在我行开立存管账户的证券公司中证券资产的月末市值等）
2.使用我行 *信用卡* 年累计消费额 *5万* 人民币以上（不包括购房、购车、装修等大额刷卡消费和零折扣率商户的消费）；
3.在我行办理各类 *个人贷款* 余额累计达到50万元人民币以上，纳入统计的贷款金额均为正常类余额。
**** 服务内容

- 专业客户经理的“一对一”服务
训练有素、经验丰富的客户经理，通过“一对一”的当面沟通，根据您的理财需求，
为您办理各项银行业务，并依托强大的专家队伍及专业的市场分析，为您定制个人理财计划，分析专业投资产品。

- 多元化的投资理财产品
凭借强大的外汇资源优势、国际市场运作经验优势、专业人才优势，洞悉先机，为您度身定制
、开发和提供多个系列、不同领域稳健获益的投资理财产品，助您获取最大收益。

- 资深专家团队的顾问支持
由外汇、证券、基金、保险、黄金、法律、财务等领域的精英组成的专业投资顾问团队，
吸取国际先进经验，应您长、中、短期的投资需要，设计丰富多样的理财方案并提供顾问服务，助您早日实现投资目标。

- 深入及时的理财资讯
根据您的投资情况，通过多种渠道为您优先提供国内外经济金融信息，市场动态及我行最新产品、服务和业务资讯，并做出深入的分析与探讨。

- 享受优惠服务
享受汇款、托收、银行卡、保管箱、贷款等数十项银行业务的费率优惠。
中银理财合作商户的消费折扣优惠（具体的特约商户和优惠项目请咨询当地中国银行理财中心）。

- 跨区域的至尊礼遇
国内数百家理财中心共同为您提供优先优越的贵宾服务。一切从您出发，无处不在的中银理财服务，与您的生活紧密相连。

- 全球化的服务网络
遍布全球6大洲26个国家和地区的680多家分支机构的服务网络，为您提供商务、留学、旅游等全面周到的国际金融服务。

- 分行特色服务内容
如机场贵宾服务、免费泊车服务、生日关怀、客户沙龙、联谊活动等，满足您的多元化的生活与社交需求。

 

** 全币种国际芯片卡威士金卡
- 出境支付需求的人士
- 仅限中国境外及中国港澳台地区使用。 
- EMV芯片标准，具有存款有息、循环信用、分期付款、全球交易人民币自动购汇等金融功能，
更有优惠便捷的超值礼遇，让您一卡在手、走遍全球。

发行范围：全国

基本功能

全币种国际芯片卡是符合EMV标准芯片卡产品，采用芯片与磁条复合卡，支持存款有息、透支享受免息期，
主附卡账单合并、统一还款，支持附属卡流量控制。贴身交易短信提醒、丰富多彩电子账单。

特色服务

1.畅游世界一卡无忧

    无论何时、何地、何种货币，持卡出境消费或者取现，减免跨境交易货币兑换手续费，优惠力度为交易金额1.5%。
    持全币种国际芯片卡白金卡可享受境外消费双倍积分、并且积分永久有效，点滴累积、惠享缤纷盛礼。
    无论您在世界何处，持卡进行的外币交易，都可自动转换为人民币入账，
您只需轻松归还人民币欠款，免除繁琐的购汇手续。
您可登陆网银或致电4006695566开通全球交易人民记账服务，
如您希望以美元进行跨境消费与还款则建议关闭该项功能。 

2.五重保障安全便捷

    采用国际通行EMV芯片标准，有效降低被伪冒与欺诈风险。
    信用卡丢失或被盗，请立即拨打40066-95566进行挂失。在办妥挂失手续后，相应风险与责任由银行承担。
    您可选择凭"签名"或者凭"签名+密码"刷卡消费，让您用卡更放心。
    为您提供实时交易短信提醒服务，确保您随时掌控用卡情况。
    当您用卡发生大额或非正常交易时，我们将第一时间向您确认，解除您的后顾之忧。 

3. 服务升级优惠更多

    借贷合一、使用随心：全币种国际芯片卡融合了储蓄卡和信用卡的优势，
让您在享受存款有息的同时，还可畅享透支消费和免息还款期的便利。
- 便捷自动还款：该卡开通自动还款服务，无需前往银行网点排队等候，还款后更有贴心短信提醒。
-    多种账单、任您选择：您可选择纸质或电子对账单，更有丰富多彩的彩信账单和Push-mail手机账单。E时代轻松理财，尽在掌握。
-  主附卡账单合并、统一还款：主卡持卡人可自主定义其项下每张附属卡在一个账单周期内可交易金额，并对其进行限制和管控，主卡还可选择同时接收附属卡交易通知短信。
-  购物分期、理财便利：中国银行为您推出"分期轻松购"卡户分期与账单分期，还有商户分期、邮购分期、大额分期等服务。轻松理财、享受生活！
-  终身免年费：2018年12月31日前办理全币种国际芯片卡可享受无限期豁免年费的优惠。 

4.中行服务全球畅享

-    环球优惠商户：精选酒店、餐饮、娱乐、购物、休闲，更有港澳及海外精品优惠商户，让您随处畅享专属礼遇。
-    中文服务、四海如一：中国银行在海外32个国家和地区拥有900多家分支机构，
即使您身在异国他乡，也能享受四海如一的贴心服务。 

5.白金品质彰显尊贵

-    中国银行特为全币种国际芯片卡白金卡持卡人设立专门客服热线40066-95569,让您尽享一对一体贴周到的专线服务。

- 全币种国际芯片卡白金卡可根据您提供的资信材料、提供更符合您经济实力与消费习惯的高额授信额度，
让您尽享透支消费便利服务。
-   中国银行为出行在外的您提供全面高额保险，保障您的出行安全，全方位呵护您的用卡生活。 

6、特色返现一卡尽享

全币种国际芯片卡持卡人可参加以下返现活动：

    环球精彩 一卡尽享"境外消费返现6%，新客户享境外首刷礼（超链接：http://www.boc.cn/bcservice/bi3/bi31/201804/t20180428_12162751.html）
    环球精彩 一卡尽享"全币种国际芯片卡境外线上消费返现5%（超链接：http://www.boc.cn/bcservice/bi3/bi31/201804/t20180428_12219570.html） 

温馨提示

-  该卡开通自动还款服务，您只需提供本人名下中国银行长城电子借记卡、长城信用卡或者储蓄存折，
拨打中国银行24小时客户服务热线或者登录中国银行网上银行即可开通自动还款服务。
另外，您还可以通过中国银行网上银行、手机银行、电话银行、ATM自助机具等自助转账还款。
- 按照监管要求，银行发行的VISA、万事达、JCB等单标识外币信用卡使用范围明确如下：
仅限中国境外及中国港澳台地区使用。 
http://www.boc.cn/bcservice/bc1/201306/t20130609_2307142.html

** 长城冰雪借记卡
一、金融权益

1.多币卡权益：19种币种存款理财、支付交易，无需进行货币转换，免除汇率波动风险，有效降低境外交易的汇率转换成本；

2.银联白金卡权益；

3.免首年年费；

4.短信通知费减免最长6个月，具体详询当地网点；

5.每月免前3笔跨行ATM取现费；

6.免境外本行ATM查询费，每月免第1笔境外本行、境外跨行ATM取现费；

7.定期发行长城冰雪借记卡专属存款、理财产品；

二、运动权益

1.万龙滑雪场

长城冰雪借记卡享有河北崇礼万龙滑雪场、北京万龙八易滑雪场的雪票、餐饮、教练培训消费等专属优惠：
项目 	河北崇礼万龙滑雪场 	北京万龙八易滑雪场
雪票 	85折 	88折
住宿 	85折 	-
餐饮 	95折（快餐除外） 	95折
温泉SPA 	85折 	-
教练培训 	买十送一 	买十送一

2.万达集团旗下滑雪场

2018年全年，长城冰雪借记卡享有哈尔滨万达城以下优惠权益：

①万达•宝马娱雪乐园，全球最大的室内滑雪场，滑雪门票74折起；

②万达茂-喜悦滑冰场，门票75折；

③万达电影乐园，《飞跃龙江》门票56折。

3.百动运动

长城冰雪借记卡可享有百动运动提供的权益：

① 滑冰、滑雪场优惠权益，涵盖北京、上海、广州、深圳4省市10个滑冰场，河北、北京、辽宁、吉林、黑龙江5省市10个滑雪场，包括冬奥会的主滑雪场崇礼云顶滑雪场，优惠权益包括两人同行一人半价、三人同行一人免单等；

② 其它运动权益，持卡客户预定大众游泳、健身、羽毛球、室内外网球等运动场馆，预定高尓夫果岭、高尓夫练习场，享百动优惠价，最低6折起；预定高端酒店游泳健身、酒店自助餐、SPA，享门市价8折优惠；购买运动装备，最低6折起。

4.第五频道

长城冰雪借记卡可享有第五频道提供的以下权益：

① 4折购买第五频道推出的全民运动卡（价值168元），享有数百家体育娱乐、运动休闲、亲子游玩、运动健身机构的数百项免费体育权益和消费折扣；长城冰雪借记卡发卡前三个月购买，特享专属1折优惠价；

② 持长城冰雪借记卡在全民运动卡的商户消费再享专属折扣价；

③ 每年可以折扣价报名参加第五频道组织的冰雪项目冬令营、亲子夏令营、品牌体娱活动。

三、运动保障

1.安踏运动装备

持长城冰雪借记卡登录安踏官方商城注册会员并绑定该卡卡号，即可享受以下权益：

① 购买安踏运动装备，可享折上88折优惠，即渠道优惠的基础上，再叠加优惠折扣；

②可优先购买安踏的奥运限量产品。

2.伊利牛奶

持长城冰雪借记卡，在“公益中国”APP—>“善源商场”等渠道购买伊利奶制品，可享88折优惠。

3.途牛旅游

持长城冰雪借记卡在途牛旅游网中行冰雪旅游专区，预定指定冰雪主题类跟团线路，可享受95折专属优惠；长白山和松花湖度假区酒景套餐产品，享每满1000元优惠50元，上不封顶。
** [[http://www.bankofchina.com/uk/cn/pbservice/pb4/201107/t20110715_1578396.html][长城环球通借记卡]]
产品名称
 Great Wall International Debit Card
http://www.boc.cn/uk/pbservice/

长城环球通借记卡

产品说明

    使用中国银行（英国）有限公司长城环球通借记卡，您可以：
    在英国境内和全球范围大多数取款机上免费取款，取款金额上限为每日200英镑或等值当地货币，*
    在英国境内部分超市使用Cash Back服务支取现金，
    在英国境内和全球范围有VISA 标志的商户处消费，包括商店、餐馆、超市等等
【英国大多数高等院校接受使用中国银行（英国）有限公司长城环球通借记卡支付学费及相关费用】，
    在线消费和电话购物。

产品特色

    受芯片及4位密码保护的VISA英镑借记卡
    开卡无需任何手续费用，无年费
    卡片支持在英国境内任何带有VISA标志的提款机上免费进行查询余额及密码服务（修改密码/密码解锁）
    提供24小时中英文双语挂失服务
    在中国境内的中国银行网点和ATM可享有更高的每日取现额度**

适用客户

居住在英国境内的中国银行（英国）有限公司个人账户持有者

申请条件

借记卡申请者须为年满18周岁的个人

办理流程

1. 如果您还未开立中国银行（英国）有限公司个人账户，
请下载、完整填写并签署《个人账户开户申请表》，同时选择《申请表》内借记卡申请选项。
您还可以从中国银行（英国）有限公司网点索取该表格。

如果您已经持有中国银行（英国）有限公司个人账户，
请前往任何一家中国银行（英国）有限公司分行填写并签署适用的申请表格。


2. 请携带《申请表》和其他申请材料，前往任何一家中国银行（英国）有限公司网点办理开户手续。

提交证件

您的有效身份证明一份（如护照或英国驾照）；

您的地址证明一份（如最近3个月的水、电、煤气账单，银行或信用卡对账单等）。


温馨提示

如果您的长城借记卡丢失或被盗，或您怀疑有其他人知道您的个人密码，或您发现银行对账单上显示未经您授权的借记卡交易，请尽快拨打卡中心电话：020 7282 8763 （如果您在海外，请拨打：+44 20 7282 8763）。

*部分取款机可能对取现进行收费，请在取现之前仔细阅读提款机上显示的收费提示信息。

**在中国境内的中国银行网点柜台和中国银行自助取款机取现每日最大额度共为等值于500英镑的人民币。

** tips
一旦发现或者怀疑自己被盗刷了卡，马上打电话给客服，只要你在结算阶段之前销户，就不会被收取费用。
但错过这一期限，一旦出现未授权盗刷情况，也可以申请退款。
异地消费的话最好去旁边任意消费，或者去附近的网点存一块钱，
以此来证明卡在自己身上，保留单据，万一日后银行和你扯皮时候可以拿来举证，
否则极有可能被银行拒绝赔付全款，这点在国内大银行身上比较多。
还有刚才说的，开通交易短信提醒也非常重要

卡不离身，不要把卡交给服务人员，让他去帮你刷
银行所提供的失卡保障，大多针对的是没有设置交易密码，仅凭客户签名进行交易的信用卡客户。

银行方面希望设置密码，是因为可以把原本该由银行承担的风险转嫁给用户。

链接：https://www.zhihu.com/question/51932825/answer/128197182


* Stocks US market
http://www.e-investingguide.com/
** open account



*** Brokerage
- 佣金低的开户门槛高，门槛低的佣金高。
- 费用最高——中资券商
- 费用中等——传统美股券商
  + [[https://www.fidelity.com/][Fidelity]] (recommended)
  + sogotrade
- 费用便宜——互联网券商

- *Robinhood* : open to USA and Australia citizen

- Ameritrade
-[[https://www.interactivebrokers.com/en/home.php][InteractiveBroker]]
  + 月平均净资产额大于100,000美元，

  + 月佣金达到10美元。

- Charles Schwar
- E*Trade


Brokerage for Low cost investment：
- 第一理财


特点：交易费很低，起步价少。一般3-8美元/单，首次最低充值500美金就可以了
功能：功能限制，如融资、期权、做空等都有限制，另外还有T+N的限制，也就是当天买入的不能当天卖什么的。
但日常操作足够了


- 国内用户炒美股的资金都在海外券商的账户，而券商的资金都有SIPC保险的保护

Barron's online broker ranking
Stockbrokers: Broker reviews
https://www.stockbrokers.com/compare
[[https://www.stockbrokers.com/compare][Broker comparison]]
https://www.zhihu.com/question/20498523/answer/121324974
https://www.sec.gov/reportspubs/investor-publications/investorpubsbegfinstmtguidehtm.html
http://www.nasdaq.com/
https://www.zhihu.com/question/19575320
https://seekingalpha.com/
https://www.bls.gov/cpi/
From <http://www.multpl.com/sitemap/world-economic-stats/china> 

From <https://www.zhihu.com/question/20498523/answer/121324974> 

**** InteractiveBroker
Personal Information for account
- 身份证正反两面复印件。

[[https://www.interactivebrokers.com.hk/cn/index.php?f=2356&p=funds][fee]]


**** Fidelity
***** Fee

*No account fees, no minimums*
  + No account fees and no minimums to open a retail brokerage account, including IRAs.1

*Great value for trades*
  + Get unlimited online US equity trades for the low price of $4.95.2

*Zero expense ratio index funds*
  + Introducing the industry's first Zero expense ratio index mutual funds offered directly to investors.

https://www.fidelity.com/why-fidelity/pricing-fees

** Where to deposit your money?
Do you need a non-Chinese Visa debit card to receive your money

** Time
 3月初-11月初采用夏令时。

11月初-3月初采用冬令时
 美夏令时：北京时间（21：30-次日4：00）

美冬令时：北京时间（22：30-次日5：00） 
** study
- 优质股票、集中投资，长期持有
- 多学习，多研究熟悉的行业、不熟悉的个股千万别碰，摸透一个行业，才能知道股票什么时候买/卖。
*** interest quantities
- 现金/企业价值
- long term investment
** company analysis
- 公司的商业模式
  + 驱动因素,KPI
  + 盈利模式、管理层团队、股权结构、财务报表
  + market share
  + new/old market?
  + leader/team of the company?
  + K线走势
  + 行业地位
  + 资产负债表

- 年报，看财报会的记录
- comparing similar companies
- 多找人聊聊，可以是别的投资者
- 我的目标买入价和卖出价是多少？
- 购买有很大安全边际的优质公司，集中投资，并且长期持有。
*** examples
中国有很多的公司在美国上市，如：百度、阿里巴巴、京东、新浪、微博、网易、搜狐、唯品会等
网易的盈利模式：“广告+在线网游”，来自游戏、广告和短信收入，加上收费邮箱、个人主页的补充
** 交易规则
January Effect Hypothesis.说的是一月份的美股都是有季节性的增长，也就是到了一月份，
开盘时间，分为夏令和冬令两个时节，9.30-4.00或者10.30-5.00
** exchange platform
IB、嘉维证券、socttrade
** 基础知识
10K、10Q、424B、13F
- Form 10-K :: an annual report
- Form 10-Q :: much briefer, is filed after each of the three quarters that do not have a 10-K filing

*** References
Introduction to Financial Accounting, Horngren Sundem Elliott Philbrick编写的。选用GAAP版本的，不要看IFRS因为美股，美股，美股。
Intermediate Accounting, Donald E. Kieso. ISBN-13: 978-1118743201

Intelligent Investor
Benjamin Graham的Security Analysis

Financial Statement Analysis and Security Valuation,


衍生品和债券
，衍生品方面的教材，比较通用的就是John C. Hull的Options, Futures, and Other Derivatives.当然去Youtube看加拿大的Meldrum讲的视频衍生品课和这个教材配合起来

Frank J Fabozzi教授的Fixed Income Analysis和The Handbook of Fixed Income Securities,

Day Trading & Swing Trading the Currency Market, Kathy LienTechnical Analysis of the Currency Market, Boris SchlossbergISBN-13: 978-1119108412ISBN-13: 978-0471745938

One Good Trade.这个适合心理素质非常好的短线投机交易者

Thomas’ Calculus和Jim Pitman的Probability  irrational exuberance, Robert Shiller

** Reference 信息查询
[[https://www.sec.gov/edgar/searchedgar/companysearch.html][
US Securities and exchange commission]]
http://www.meiguwiki.com/
* Credit card
在线下吃喝玩乐较多的，可以选择招行的卡，

很多餐厅都有招行卡周二半价的优惠；

如果喜欢淘宝购物，可以选择中信、平安的淘宝联名卡，用支付宝快捷支付有积分；

经常去沃尔玛购物的，可选择交行的沃尔玛卡，周五购物能返现 5 个点；

有车的可以申领各行的车友卡或者中石油 / 中石化的联名卡，加油有折扣
招行 [[http://market.cmbchina.com/ccard/2012car/?WT.mc_id=][CarCard汽车信用卡（全国版]]

http://chuansong.me/n/1556428

* 国泰君安 
点击银证转账，选择转入，输入转账金额，提交即可
注意：需要在交易日, 9AM-16pm
** 天汇宝
- 债券质押式报价回购
- 公司以债券质押，每日统一报出各期限品种的利率，客户接受报价，并将资金融给公司，到期获取稳定的收益

** 债券质押式报价回购
《质押式报价回购交易及登记结算业务办法》及其有关事项的通知（沪市）

* 定投10年的好基金
http://blog.sina.com.cn/s/blog_6524e14b0102x7rf.html
指数基金，比如创业板的159915，中小板的159902，医药的159929，军工的512660，有几个原因：


1、投资指数不会踩个股地雷。

2、指数本身就能跑赢60%以上的股民

3、选的都是成长性比较有保障的行业、板块指数，确保长线（3年以上）整体趋势向上。

 基金A，沪深300指数增强基金

基金B，中证500指数增强基金

但其实有比投资指数更好的选择，就是*指数增强型*基金，这些基金每年可以跑赢指数10%以上，厉害的单年可以跑赢20%，原先你只能跑赢60%股民，
不吹牛逼，买这些基金能跑赢80%+的股民。

* P2P
** platform:
陆金所、
人人贷
宜人贷
、开鑫贷、微贷网、投哪网、拍拍贷、搜易贷。
安邦金融


**  陆金所 [[https://www.lu.com/about/introduction.html][慧盈−安e]] 
安e变成安e+后，将 *担保* 变成 *保险* 
担保责任在法律上远远强过保险责任，
比如：保险拥有众多免责条款，可轻易逃避债权。
担保在破产清算中债权受偿优先级更高等等。所以我坚决不买安e+，只在转让区选安e。
https://www.zhihu.com/search?type=content&q=%E9%99%86%E9%87%91%E6%89%80%20e


***  担保公司
[[https://www.tianyancha.com/company/220001425][平安融资担保（天津）有限公司]]
法定代表人：刘光强
注册资本：1.25 亿人民币

平安普惠融资担保有限公司
法定代表人：YONG SUK CHO
注册资本：55321.908万美元

*** 风险等级
P2P，即使是陆金所这种龙头发行的，虽然收益不低，但陆金所实际是通过SPV
（特殊目的机构，证监会的官方翻译好像？还真是字面翻译）做P2P的。
简单来说，陆金所的债务和平安集团理论上是完全切割出去的。
平安只是名誉隐性担保，但无实质法律和经济上的责任。

作者：李元霸
链接：https://www.zhihu.com/question/21855830/answer/101479873


所有慧盈-安e均由中国平安旗下担保公司承担担保责任。
若借款方未能履行还款责任，担保公司将对未被偿还的剩余本金
和截止到代偿日的全部应还未还利息与罚息进行全额偿付。


* Case studies
**  7-11 全家
* Population 
https://www.populationpyramid.net/china/2016/

* 外汇  Foreign exchange
platform
[[https://www.metatrader4.com/en][Metatrader4]]


http://www.safe.gov.cn/


1 GBP = 8.588 CNY

keywords: Travel money, foreign currency exchange , travel money

中国有要求从境外带人民币回国的话最多每人不能超过2万，
如果你要换的英镑金额大，最好直接 *国际汇款* 回国。


** Platform
pos office money
Travelex
Thomas Cook

https://cityforex.co.uk/index.php
https://travelmoney.moneysavingexpert.com/holiday-money/
https://www.travelex.co.uk/
https://www.bestforeignexchange.com/Exchange-rates-check-exchange-rates.php
Euro Exchange
money shop
https://www.bangli.uk/post/264810

** Pound to RMB
手头有些英镑想换成人民币回国用。有如下方案：
1.直接将卡上的英镑在银行换成人民币（LLoyds银行卡）
2.取出，在英国机场换人民币
3.取出，回国后用英镑现钞在中国银行换成人民币
4.国际汇款到国内的中国银行卡上 (recommended)

tips: 
- 最好是直接在银行转换成人民币
- *现汇* 买入价和 *现钞* 买入价是不一样的
https://www.zhihu.com/question/21982881/answer/67158932

** international payment (lloyds)
fee: 
9.5 >> lloyds bank
20  >> Bank of China

[[https://www.lloydsbank.com/online-banking/benefits-online-banking/international-payments.asp#collapse1-1438975317838][How do I send money abroad online?]]

If you have a current account with us and you’re registered for Internet Banking, you can log on to send money abroad.

You’ll need to have the following information to hand:

-    the recipient's name and address (exact full name or company name)
-    the recipient's IBAN (International Bank Account Number) or account number
-    the name and address of recipient's bank - including the BIC (Business Identifier Code) / SWIFT code / clearing code




* 麻辣烫
brands: 杨国福、张亮

* TODO fiance
depost- hammands 1.5 month
Deposit- yanyan £350
Deposit - CSC 2W RMB
* 生鲜电商有成功案例吗
Ocado
CFC，Customer Fulfillment Centre）
会员制
1. 解决了消费者购买随意性的问题，不由消费者选择，由厂商统一搭配配送。
2. 解决了保质期短，散装问题，定时定量配送。
3. 顾客稳定，下次送货可回收上次送货包装，进一步降低成本，顾客也愿意配合。
4. 会员制的模式真正筛选出了，愿意为电商带来的便利而付出溢价的客户。


链接：https://www.zhihu.com/question/24338193/answer/32859373
* 农民
很多人对农民的印象是：淳朴
很多人对农民的印象是：贪财

其实绝大多数农民都非常非常非常的看重钱，但大多数情况下会表现得非常非常非常淳朴
* journal and web
- the economists
- [[https://www.bloomberg.com/asia][Blomberg]]
- Harvard Business Review
- MIT Sloan Management Review
- California Management Review
- 财经
- [[https://www.barrons.com/][Barron's]]

* delivery
中国快递业最大的优势是人口密度
* online-shopping China
** densely populated
- low delivery fee per person

** 基础设施
交通系统, internet, 4G 
** payment method 
中国城市人口没有像西方那样经历信用卡和支票时代，一步从现金时代跨到支付宝和微信支付，便捷性的落差很大，也是移动支付扩张迅速的重要原因
** low crime rate
no non-go zone
** made and sale in China
One language
生产，销售，物流

* Interest rate
4%-5%：1、货币基金；2、银行保本理财

5%-6%：1、银行非保本理财

6%-7.5%：
 1、信托；
 2、证券公司资产管理计划；
 3、p2p（信托和资产管理计划有购买门槛，p2p如果真的要买就买大型的，购买金额不要太多，以短期1-3个月为主）

7.5%以上：
 1、股票型基金或者混合型基金；
 2、股票二级市场；
 3、私募基金；
 4、股权投资；
 5、股债结合的信托等；
小于7.5%的产品基本上是固定收益的，但是大于7.5%的基本是权益性的。



如果期望比余额宝收益高一点点，比如5%，可能纯债基金就可以满足需求。
如果追求10%可能需要将偏股型、债券型基金搭配投资即可实现，
而如果追求15%—20%的收益率那可能要大比例投资偏股型基金。
嗯，不要幻想20%+的年化收益率了，那是巴菲特等人的业绩。
莫要低估复利效应，年化收益能有20%，坚持个二三十年财务自由可期。

作者：书剑笑傲
链接：https://www.zhihu.com/question/56417264/answer/151138426
** 融资成本
银行给企业的贷款一般是7到8个点左右， 那么P2P的一年期收益率就最好不要超过这个数的上浮1到2个点，
也就是不超过9%-10%

* country side 
温铁军
- 各种原本属于地方ZF，属于开发商，源自银行的负债，也一定会想方设法的转移到优质刚需
- 经济基本面数据可以关注统计局网站；土地成交信息（位置及价格）可以上当地国土局网站看，每天都有更新
住房成交信息可以上住建局网站看。
至于，网上的新闻，还是少信为好。

    《三农问题：世纪末的反思》
    《解构现代化》
    《中国农村基本经济制度研究》
    《我们到底要什么》
    《认识与实践的对话》
    《八次危机》

* Chinese Bank
体制来讲是国有垄断、政治上来看是吸血的资本家
* China import and export
http://atlas.cid.harvard.edu/explore/?country=43&partner=undefined&product=undefined&productClass=HS&startYear=undefined&target=Product&tradeDirection=import&year=2016



* delivery
中国快递业最大的优势是人口密度* 如何选基金？
可以通过基金排行，筛选出近五年、近三年、近一年、近半年等阶段，业绩表现排名前列的基金
基金的年报、季报、半年报
* bitcoin
install bitcoin core
https://www.linuxbabe.com/ubuntu/install-bitcoin-core-wallet-ubuntu-16-04-16-10
* 如何挑选合适的基金产品做基金定投？
                               
成立时间2年以上、
                                      
成立以来年化收益20%以上、
                                      
成立以来最大回撤20%以内 。
https://www.zhihu.com/question/19801437
* 生鲜电商有成功案例吗
Ocado
CFC，Customer Fulfillment Centre）
会员制
1. 解决了消费者购买随意性的问题，不由消费者选择，由厂商统一搭配配送。
2. 解决了保质期短，散装问题，定时定量配送。
3. 顾客稳定，下次送货可回收上次送货包装，进一步降低成本，顾客也愿意配合。
4. 会员制的模式真正筛选出了，愿意为电商带来的便利而付出溢价的客户。


链接：https://www.zhihu.com/question/24338193/answer/32859373
* 农民
很多人对农民的印象是：淳朴
很多人对农民的印象是：贪财

其实绝大多数农民都非常非常非常的看重钱，但大多数情况下会表现得非常非常非常淳朴
* journal and web
- the economists
- [[https://www.bloomberg.com/asia][Blomberg]]
- Harvard Business Review
- MIT Sloan Management Review
- California Management Review
- 财经
- [[https://www.barrons.com/][Barron's]]

* 证券
证券市场基础知识（必考）
证券投资基金
证券交易
[[http://www.sac.net.cn/][中国证券业协会]]

* Futures (期货)
期货和现货最大的区别在于
• 保证金
• 保证金即日结算
• 到期后通常不用实物交割
只要记住这三点就可以很好地理解期货了。
* 理财

理论
宏观经济学，微观经济学，会计学，财务管理（公司金融）
理财提示


*第一， 理财永远只有锦上添花而非雪中送炭，手头没钱的时候关键是努力工作积累原始资本*
手头也就几万块钱，想靠理财来一夜暴富那是不现实的。
风险可控的理财产品、基金、债券什么的的最多也不能给你超过年8%的收益水平；
股票能赚50%你已经是股神了，但亏损50%是轻轻松松的事情；
炒期货什么的有机会能翻个好几倍，但小散户经常摆脱不了强制平仓的厄运。
手头没钱的时候要获得财富增长，最好的办法就是好好工作，拼命工作，积累原始资本！
试想就算把你放到2005年以前，如果你连买个小房子的资金都拿不出来，
即使判断对了房价行情那也必然会错失房地产的投资机会。
所以先得积累原始资本，等积累到一定程度了，通过理财、投资是有可能带来比工资更高的收益，
那个时候可以获得锦上添花的体验了，所以有必要清醒地认识一个人在不同阶段需要关注的重点。
第二，一定不要沉迷于理财，对大部分人来说花同样的时间学习比花同样的时间理财收获要大得多。主要是针对还未获得原始资本积累的人群，其实也是大部分人的状况。我经常发现周围有人在上班时间看股票，在休息时间讨论股市，特别是一些八竿子打不着的比如工程师、老师、程序员等等，花100个小时盯着大盘和花100个小时学习一门新技能或者把工作做到极致，哪个效用更大？除非你以后就想从事证券投资的工作，否则对于大多数人来说后者的效用要大得多，能够带来长期的超预期的回报！
第三，理财不等于投资，理财包含的范围要广得多。大家有时候容易把理财理解得过于狭隘，认为资产的保值增值——投资就是理财的全部，但理财规划远不止如此。一个人的理财规划应该匹配自己对未来生活的规划，利用合适的产品将资金保值增值的同时逐步实现生活规划，比如旅行计划、买房买车计划、子女教育和自身再教育计划等等。
第二部分，几个理念
明确了上面三条理念就可以开始谈谈如何理财了。这里我还是从理念谈起，我认为如果理念不明确就去做规划和执行，很容易迷失方向，耗费时间和经历却达不到预期的效果。
第一，理财要与生活规划结合起来，不要盲目理财。
你要时时明白，你不是为了理财而理财，你是为了实现更好的生活而理财！所以理财之前你至少要有一个大概的生活规划，然后按照生活规划来制定自己的理财计划。比如何时买车，买什么价位的车；何时买房，计划买多大的房；何时婚育；何时想做大额的投资；何时想出来创业等等。有了规划你才能最有效地为自己理财，记住理财是为生活服务的！
第二，选择符合自身风险承受能力的理财方式。
一个刚踏上工作岗位一年多的未婚小伙和一个上有老下有小的中年大叔必然适合不同的理财模式，因为自身的风险承受能力不同：未婚小伙没有太多生活压力，可能家里还有一定支持，可以冲一冲收益较高的产品，反正还年轻，输了可以重来；中年大叔需要考虑家庭的稳定，不可能允许理财失败影响家庭安定，所以更倾向于稳健性的理财手段。生活中我们也常见一些不顾自身风险承受能力，卖车卖房子去放高利贷、炒期货、投一些收益高风险高的项目，最终落得个家破人亡的下场。引以为戒！
第三，理财贵在坚持。在确定了自己的理财规划以后，要坚持下去，不要因为一时的冲动（比如购买大金额奢侈消费品等）而打破了原有的计划。在坚持一段时间以后，你一定能够看到自身财务状况的改变，也能够因此获得一定的成就感和满足感，这样你就更有动力坚持下去。
第三部分，如何做好理财规划
第一步，认清自身状况。
认清自己是最基本的要求，自身资产负债情况主要考虑以下问题：1、目前有多少资产，各类固定资产（如房产、汽车等）、金融资产（存款、证券、理财产品等）的存量；2、未来的预期收入如何，正常情况下收入会以何种趋势增长；3、负债情况如何，有多少房贷、分期付款、其他借款等；4、自己的合理消费需求如何。把这四点理清楚了就大概能算出自己能拿出来进行理财的资金了：每月产生的可理财资金=劳动收入+资产收入-个人消费-债务清偿。总的可理财资金=已持有的金融资产+每月可产生的理财资金。
第二步，评估个人风险偏好。
很多人会忽略这一步，但不可否认评估风险偏好是必须。严格讲，个人风险偏好不等于个人风险喜好，在考虑风险喜好的同时还要考虑自己风险承受能力。网上有一些测试风险偏好的工具，大家可以作为参考，比如宜信财富的（宜信财富_在线工具）。当然，最重要的是做好自我评估，做到心中有数，下面我列几条对风险承受能力有明显影响的特点，供参考。承受更高风险的：年轻、未婚未育、父母收入稳定有保障、自己收入较高、已有一定财富积累、具备较强投资能力；承受更低风险的：中年、已婚已育、父母无保障、收入偏低、财富积累较少、投资能力较差。确定好风险偏好才能明确哪些理财手段是适合自己的。
第三步，明确理财目标。
有目标了你才知道自己需要如何行动。要根据自己对于生活的规划制定理财的目标，而且目标最好要能够比较明确或者量化。举个例子，一个不好执行的理财目标：30岁前买房买车。虽然时间、物质等要素都包含了，但太笼统，不具有指导性。一个好执行的理财目标：28-30岁时，能买一套100平米的商品房，首付30%左右；30-31岁时，能买一辆16万左右的车；有一定教育基金供小孩读书用，同时家庭还能保持一定的流动资产以备不时之需。总之确定一个比较明确而且可行的目标，然后朝着目标努力，同时不要忘记，大部分时候理财只是达到目标的辅助手段，努力工作赚钱才是王道。
第四步，进行资产配置。
资产配置是实现理财目标和控制风险的关键。这里谈两个问题，一是有哪些可以选择的资产，二是我们如何做到合理配置资产。
普通大众都能选择的产品很多，按风险大致可以分类如下：
低风险：国债、保险、存款、银行理财产品、货币基金。一般来说国债、存款、货币基金基本没什么风险，放心把钱投进去就行了。保险类产品分为投资连接型（分红型）的和纯保障型的,建议不要想着利用保险赚太多钱，保险的收益一定低于理财收益，要买就买纯保障型的。保险产品容易被很多人忽略，但是在一个合理的理财计划中保险一定是不能少的，他能为你有效避免“黑天鹅”事件的发生。银行理财产品有保本、非保本、浮动收益、保证收益，开放式的、半开放式的，可以根据自己的需要去选择，一般风险较低。
中低风险：债券型基金、基金定投。基金定投在目前整体估值偏低的情况下可以适当介入，长期定投一是可以强制将资金积少成多，二是能够平滑收益的波动，享受股市整体上升的红利。对于每月有固定收益的人群，可以多考虑基金定投。
中等风险：股票型基金、P2P理财、信托理财、黄金、房地产。股票型基金具有有一定的市场波动性，适合具有市场投资经验的人参与。P2P理财等互联网金融可以适当参与以获得较高的收益，但一定要寻找正规的、有保障的平台，切忌盲目追求高收益！信托理财之前一直是刚性兑付，而且收益较高，年收益9%上下的都有，但是信托动辄上百万的投资门槛还是比较高的，且最近几起违约事件打破了刚性兑付，存在一定的投资风险。炒黄金，有投资基础的能看懂世界经济走势特别是美国经济和美元走势的人，可以做一做，一般人不建议投资。房地产在中国曾经是一类高收益低风险的资产，但是时过境迁了，在一些泡沫比较大的城市，其风险不可忽视。
高风险：股票、外汇、期货、股权类投资。这四类投资都需要较高的市场水平，一般人切忌配置过大的比例在这上面。股票、外汇相对来说风险还稍低一点，期货和股权类投资则风险很高，如果行情没看准或企业看错了，很可能本金一分不剩。但不可否认，高水平的投资人也完全可以靠这个赚到第一桶金，能力不同。这里再给互联网金融打个广告，有些类似于股权众筹的项目，有一点闲钱的可以适当参与。
了解了可以选择的资产池子，现在就可以配置资产了。在做资产配置的时候我们需要综合考虑以下几个问题：第一，自身的特定需求，比如买房、教育、保险等。第二，自身风险偏好和风险承受能力。第三，自身投资能力和经验。第四，所投资资产的收益、风险和流动性。在以上四点的基础上再做资产配置决策。
简单概括一下：我们根据一个人的综合状况，可评定为激进型（风险偏好，风险承受能力强）、稳健增长型（有一定风险承受能力，追求资产增值）、保守型（厌恶风险或风险承受能力低，追求稳定）。以下数据只是举个例子，实操是需要考虑具体情况：

激进型：高风险45%，中等风险30%，中低和低风险20%，最后5%存款、货币基金保证流动性。
稳健增长型：高风险20%，中等风险20%，中低和低风险50%，存款、货币基金10%。
保守型：高风险0%，中等风险20%，中低和低风险70%，存款、货币基金10%。
第五步，根据变化做出调整。
理财计划不可能一成不变，生活中总会遇到一些突发事件需要你用钱摆平，或者有在理财计划执行一段时间以后你可能会发现对自己的认识存在偏差，以前的规划做得并不合适；亦或你的股票操作并不理想，遭受了损失，打乱了原有的计划，等等。这其实就是一个对原有计划的检验过程，检验之后如果发现了问题需要及时调整，最终目标是让自己的理财规划匹配自身状况和生活规划。
最后，案例分析：
简单的案例，做了一些简单的假设，后面算账的时候写得有点复杂，可以忽略，但思路基本上是如此。在真实的理财规划中，随着外界环境和自身想法的变化，是存在比较大调整的空间。案例主角不是本人，本人已婚。
男，26岁，未婚未育，研究生毕业1年，二线城市，月收入1万，未来预期收入会逐年稳步增加15%；无房无车无债务，有金融资产20万，懂金融有过股票投资经历，风险偏好型；生活月开销4000。父母健在，农民出生收入较低，无养老保障。计划1年后买车（12万），4年后买房（全价150万）。
自身情况上面表述比较明确，已有20万金融资产，每月结余6000，一年7.2万。无债务负担，但父母需要养老保障。综合上述情况，自身属于风险偏好型，收入较高，具有一定的投资经验，但考虑到父母的因素，其能够承担的风险有限，可定位为稳健增长型-激进型之间。
再来看理财目标：27岁买车，4年以后买房，短期内资金压力较大。所以理财计划需要做到以下几点：第一，给自己和父母做好保障。第二，资金增值，一年后能有12万左右资金买车；4年后拿出45万首付。第三，为成家做一定的准备。
给出的理财规划如下：第一，以保险的方式为父母提供保障（养老保险、意外伤害、疾病保险等，预计每年支出10000），避免父母的一些意外给家庭造成过大的压力。第二，为自己购买额外的意外、疾病等险种，消除后顾之忧，预计年支出3000。第三，利用自己的专业优势投资一定比重的股票、股票型基金等高收益产品，博取较高的收益，配置6万左右资产（看情况增减，保持在20%-30%水平）。第四，配置一些中等风险的比如P2P产品等2万（10%左右的比例），收益保障。第五，配置较高比例的银行理财产品、货币基金，10万左右（保持50%左右的比例，收益5-6%）。最后，手头预留3000左右流动资金以备不时之需，流动资金不需太多，一是货币基金可以随时转换，二是可以有效利用信用卡。
按上述计划：工资收入12万-消费支出4.8万=7.2万的工资收入+工资收入的增值部分（大概0.25万）；一年后保险支出1.3万；理财和货币基金收入0.5万，P2P收入0.2万，股票收入乐观估计0.6万-1.2万。一年后有27.5万-28万的资产。完全可以拿出12万购车，剩余16万资产。
工资每年保持15%左右的增长水平，后3年共拿到48万左右工资，考虑到买车后，3年总消费增至15万左右，共有33万净增收入，平均下来3年能有3.5万增值。原有16万资金投入理财，平均下来3年能有3.4万增值；另年付保险费1.3万每年共3.9万，最终积累55万左右金融资产。买房45万首付完全没问题，首付以后剩余金融资产10万，且第5年月薪超过2万，房贷无压力，生活已然走上了稳步上升通道。
总结：再次强调，理财只有锦上添花而非雪中送炭的作用，在资本积累的初期，通过努力工作赚钱才是真正的出路。等资本具有一定的积累以后则可以选择不同的理财路径，高手可以通过资本投资来获得高额回报，走向财务自由；我等不具备此能力的普通大众也可以在理财的帮助下早日过上幸福生活。

** references

* House market 
短期看金融，中期看土地，长期看人口。

Land: only from government
household register: city and country side
Finance system: 分享红利
社会化租赁:地价 税收
* 普通人可以从什么渠道获得专业靠谱的理财规划或者建议？
bank
stock market
    应该拿多少钱投资？
    投资资产的分配如何？
    在具体的一类投资中，选择哪些品种？
    选择的各品种何时买，何时卖？
第一个原则是：
1. 不要找产品生产方，要找第三方
挑有专业资质的顾问（比如国际上的AFP、CFP，国内的ChFP等）
挑能够定期review的理财顾问。

机构不够独立客观：银行、券商、保险、信托等传统金融机构是以营销为导向来实现盈利的，理财经理、投资顾问更多的是产品的推销员，
重任在肩，利益攸关，真正从客户角度出发去为客户做资产配置、财富管理的很少


资产配置方案包括8个方面，分别是：1、投资规划；2、风险管理规划；3、现金规划；4、消费支出规划；5、教育规划；6、养老规划；7、税收规划；8、财富传承与遗产规划

人脉，门路，咨询，资金，技术
** references:
Unconventional Success
* 理财类产品
分两类：1.动产 2.不动产
 1.收益 2.风险 3.流动性
从活期到定期、债券、保险、基金、股票、信托等，风险逐渐升高可能收益也逐渐升高
** risk
平台风险、投资风险
平台风险：现在挺火的P2P、一些贵金属、大宗商品交易公司（平台跑路）
** 信托产品
由信托公司发行，类似银行理财，收益更高，但门槛更高，100万元起，年化9%-11%
