* 慢性咽喉炎
枇杷叶10g
冬桑叶10g
甘草6g
薄荷叶5g
https://www.zhihu.com/question/51119704

* Lower back 
Right posture

Leave your seat every hour

Cardio exercise 30 minutes

Lower back exercise

Physiotherapy: Lower Back Pain - Part 1 

From <https://www.youtube.com/watch?v=Sap7IcypH0I> 
Yoga For Lower Back Pain 

From <https://www.youtube.com/watch?v=XeXz8fIZDCE> 
* 咳嗽的诊断与治疗指南（2015）
化痰
1.乙酰半胱氨酸

2.性药物通常可以选用「盐酸氨溴索」
* teeth -- dental
** tips
Brush at least twice a day. The best time to brush teeth is after meals. Choose a toothbrush with a small head for better access to back teeth. Soft bristles are kinder on your gums.
Use fluoridated toothpaste. Fluoride helps to harden tooth enamel and reduces your risk of decay.
Brush thoroughly. Tooth brushing should take between two and three minutes.
Floss your teeth daily. Use a slow and gentle sawing motion.
Limit acidic drinks like soft drinks, cordials and fruit juices. Food acids soften tooth material and dissolve the minerals in tooth enamel, causing holes (cavities or caries). In severe cases, teeth may be ‘eaten’ right down to the gum.
Limit sugary foods. Bacteria in dental plaque change sugars into acids.
Protect your teeth from injury. Wear a mouthguard or full-face helmet when playing sports.
Try to save a knocked out tooth. If possible, hold the tooth back in place while you seek immediate dental advice. If this is not possible, wrap the tooth in plastic or place it in milk and seek dental advice immediately.
Avoid using your teeth for anything other than chewing food. If you use them to crack nuts, remove bottle tops or rip open packaging, you risk chipping or even breaking your teeth.
See your dentist for regular check-ups. You should also visit your dentist if you have a dental problem such as a toothache or bleeding gums.

牙龈炎的病损局限于牙龈，无深部牙周组织的破坏，在去除局部自己因素后，牙龈的炎症约在一周后消退，破坏了的胶原纤维可新生，牙龈的色、形、质及功能均能完全恢复正常，预后良好。但如果患者不能有效地控制菌斑和定期复查，导致菌斑在此大量聚集，牙龈炎是很容易复发的。
1、习惯早晚刷牙及使用牙线清洁牙缝，尤其是在睡前，可以清除牙菌膜，减少在睡觉时牙菌膜的积聚。每6个月至1年，定期往牙科医生处清洁牙齿，预防牙菌膜变成牙石，及清除在牙齿上已形成的牙石。
2、使用软毛牙刷：用软毛牙刷刷牙龈及舌头，对牙龈很有好处。刷牙龈边缘：刷牙时不要忽略容易堆积牙垢的牙龈边缘，将牙刷倾斜45度角，由内向外刷，清除食物残渣尽量不碰伤牙龈，如此可预防牙龈发炎。轮流使用两只牙刷：轮流使用两支牙刷的好处在于可以使另一只有时间完全风干，从而减少细菌滋生的几率，这对牙齿的健康非常重要。
3、给牙齿补钙：牙骨疏松容易导致牙龈炎，可以多吃含有钙质的食物，来强化骨骼。
4、经常使用漱口水：漱口水可以帮助你清除牙垢，对牙齿健康很有帮助，建议每次吃东西后一定要漱口。
5、戒烟、戒酒：烟和酒会流失保持口腔健康所需的维生素及矿物质，要想有健康中药的牙齿，必须戒烟和酒。
6、多吃生蔬菜：生蔬菜含有很多纤维素，能帮助清洁及刺激牙齿及牙龈以避免牙龈炎。
7、危险讯号：牙龈痛、牙龈流血、长时间口臭、牙齿松动、都是牙龈炎的征兆。若置之不理将信心可能导致更严重的牙周病，所以必须尽快看牙医。

** Teeth grinding (bruxism)
** dental hospitals
*** 全国口腔医院排行榜
1、北京大学口腔医院

2、四川大学华西口腔医院

3、上海交通大学附属第九人民医院

4、第四军医大学附属秦都口腔医院

5、武汉大学附属口腔医院

6、中山大学附属光华口腔医院

7、首都医科大学附属北京口腔医院

8、中国医科大学附属口腔医院

9、南京医科大学附属口腔医院

10、南京市口腔医院
华东地区

1、上海交通大学医学院附属第九人民医院

2、南京医科大学附属口腔医院

3、南京市口腔医院

4、浙江大学医学院附属口腔医院

5、同济大学附属口腔医院


华南地区

1、中山大学光华口腔医学院附属口腔医院

2、广东省口腔医院

3、广西医科大学口腔医学院附属口腔医院

4、南方医科大学南方医院

5、广州医科大学附属口腔医院


西南地区

1、四川大学华西口腔医院

2、重庆医科大学附属口腔医院

3、昆明医科大学附属口腔医院

4、遵义医学院附属口腔医院

5、贵阳市口腔医院


西北地区

1、第四军医大学口腔医院

2、西安交通大学口腔医院

3、兰州大学口腔医院

4、新疆医科大学附属口腔医院

5、银川市口腔医院


华北地区

1、北京大学口腔医院

2、首都医科大学附属北京口腔医院

3、天津市口腔医院

4、天津医科大学口腔医院

5、河北医科大学口腔医院


东北地区

1、中国医科大学附属口腔医院

2、吉林大学口腔医院

3、哈尔滨医科大学附属口腔医院

4、大连市口腔医院

5、大连医科大学口腔医学院附属口腔医院


华中地区

1、武汉大学口腔医院

2、中南大学湘雅口腔医院

3、河南省口腔医院

4、华中科技大学同济医学院附属同济医院

5、长沙市口腔医院


https://zhuanlan.zhihu.com/p/22129523

*** 杭州十大公立口腔医院排行榜：

1、杭州市人民医院口腔科

2、浙江大学医学院附属第二医院口腔内科

3、浙江省口腔医院口腔综合科

4、杭州师范大学附属医院口腔科

5、浙江省人民医院口腔科

6、杭州美中宜和妇儿医院口腔科 

7、浙江大学医学院附属邵逸夫医院牙科

8、杭州口腔医院综合科 

9、浙江大学附属医院口腔医疗

10、杭州市人民医院城北院区口腔科

二、杭州口碑较好的专业私立牙科医院有哪些？

1、杭州美奥口腔连锁医院

2、杭州市口腔医院

3、杭州牙科医院

4、杭州拜博口腔

5、杭州格莱美齿科

6、杭州市康源口腔

7、杭州雅正口腔

8、杭州艾维口腔

9、杭州美莱整形口腔中心

10、杭州绿城口腔医院
https://www.kelete.com/

** swollen gum-- gingivitis
https://www.nhs.uk/conditions/Gum-disease/
- 当你刷牙开始出血时，说明牙齿的健康问题已经很堪忧
牙石- calculus
* piles
上班族要如何科学预防痔疮呢？
1、一定要多活动
不要久站久坐，坐45分钟起来活动5分钟，完全可以有效地减轻痔疮症状。
2、切忌久蹲
尤其不要一边上厕所一边看书读报。因为蹲厕时保持的姿势，可以促使痔静脉从充血 ，影响静脉血液回流，引起或加重痔疮症状。
3、便后记得清洗干净
痔疮病人便后使用柔软的卫生纸擦干净，有些卫生纸过分粗糙，有些卫生纸还含有荧光剂化学剂等，市民要注意分辨。有条件的话，最好用水清洗，帮助肛门清洁。
4、早晚做提肛运动
早晚做提肛运动可以缓解痔疮，也是常用的痔疮预防方法。
5、在办公室里多喝水、多吃纤维粗的食物
喝水可以软化肠道里的大便，粗纤维的食物可以促进肠蠕动，都可以帮助排便。比如蔬菜、水果以及未经精加工的谷类和薯类等，有助于痔疮预防。
6、饮食调理
日常要注意有规律、合理的饮食，避免偏食；少吃辛辣刺激性食物，多吃含纤维素蔬菜，多喝水。大便情况发生变化时，要及时改变饮食来调理。
7、防止便秘 
日常可通过饮食及药物来调理，也可将中药决明子单味药用开水冲泡代茶饮用，或用肉苁蓉、何首乌等水煎后加入蜂蜜 服用。一定要注意防止便秘的发生。
8、养成良好的排便习惯
预防肛肠疾病，还要做到每日定时排便；不在厕所里长时间蹲坐；排便不要看书、看报；是不费力气、用最短时间排出不便，以减少局部刺激。
9、注意劳逸结合
预防肛肠疾病，日常还要注意不要长久站立和蹲坐，也不要长时间骑自行车。
* workout
　不管你是在健身房、竞技场、还是在家里或是在办公室，你所吃的食品决定着你的表现。搭配合理的食品能获得更好的锻炼效果。下面是一些饮食和锻炼的搭配小窍门。

　　1、关键的碳水化合物

　　碳水化合物是人体为体力活动准备的优先的燃料来源，也是运动员的训练计划中必不可少的组成部分。面包、米饭、谷类食品、面食、水果和蔬菜为肌肉提供了高能量燃料，可以在锻炼后加快肌肉燃料的重新储备。

　　如果你摄入的碳水化合物不够多，就会更容易疲劳。具体需要多少量的碳水化合物，这取决于个体的训练和个人要求。对训练量很大的运动员而言，每天需要的碳水化合物是每公斤体重6克到10克。譬如说，如果体重为60公斤的运动员每天训练2到4小时，那么他每天大约需要360克到600克的碳水化合物。

　　2、高效补水饮料

　　要获得良好的锻炼效果，饮料必不可少。在高强度活动期间，体内流质减少会增加中暑性痉挛、中暑衰竭或者中暑的可能性。锻炼之前、期间及之后要喝饮料，并把这作为锻炼计划的一部分。要养成多喝饮料的习惯，哪怕在不锻炼的日子也是这样。

　　水、运动型饮料、水果、蔬菜汁或者矿泉水都是不错的选择。建议在锻炼、训练及比赛期间饮用冷水或者运动型饮料。酒精和咖啡因会导致人体脱水，因而算不上是补充水分的饮料。锻炼前2小时喝400毫升到600毫升饮料，锻炼期间每隔15分钟到20分钟就喝150毫升到350毫升。

　　3、安排饮食时间

　　如果你即将参加跑步比赛或者其他竞赛，应当在赛前两三个小时，来一顿低脂肪、高碳水化合物的饭菜。吃些你所熟悉、又易于消化的食品。水果、酸奶、硬面包圈、或者一碗谷类食品都是良好的选择。

　　如果你在运动期间胃里有食品，血液就会从消化道改流到锻炼中的肌肉，从而导致胃部痉挛和滞胀感。如果你在早上空腹锻炼，就要有前一天储备下来的足够能量来维持60分钟到90分钟的锻炼。要是你觉得一大早锻炼之前吃早餐不方便，可以在前一天晚上上床前，来些富含碳水化合物的点心。

　　如果你在当天晚些时候锻炼，而且离上一餐过了4小时以上，那么应当在开始锻炼前45分钟到60分钟来些点心。你的食品选择和偏好可能会有不同，这取决于你锻炼的时间、从事的运动以及运动强度。你很快会知道哪些食品组合最适合自己。

　　4、为耐力赛准备补充碳水化合物

　　补充碳水化合物适合于参加马拉松、铁人三项赛或者长距离自行车比赛的运动员。如果比赛是不间断地持续不到90分钟，普通的高碳水化合物饮食就够了。补充碳水化合物需要在比赛前三四天，稍微减少训练量，并在这段期间，把碳水化合物的比例增加到全部热量的70%到80%。

　　5、补充及恢复

　　锻炼之后，补充肌肉中的糖原很重要。应当在锻炼之后30分钟内吃些富含碳水化合物的饮食或者点心。这时候，人体肌肉对摄入的碳水化合物最容易吸收。如果你在一天内要参加两次或者更多次活动，那么在大运动量锻炼后1小时到4小时内吃些富含碳水化合物的食品显得特别重要。

　　像硬面包圈、水果、谷类食品这些食品易于食用。要是你对非流质食品没有胃口，果汁和运动型饮料是锻炼后立即补充碳水化合物的理想来源。它们还有助于你补充水分。

　　6、补充流失的钠和钾

　　锻炼期间流失的这两种元素可以通过食品来补充。应当吃些富含钾元素的水果和蔬菜，譬如香蕉、橙子、甜瓜和西红柿。锻炼后往饮食中稍稍添加一些盐，即可补充因出汗而流失的钠。

　　7、维生素和矿物质

　　体力活动可能会加大人体对某些维生素和矿物质的需要。不过，如果你摄入的热量足够多，满足得了体力活动的要求，而热量又来自营养食品，那么恐怕不需要服用任何补充剂。营养补充剂不能为你提供额外的能量，除非你一开始就缺少某种营养成分。

　　8、不需要更多的蛋白质

　　蛋白质是很重要，因为它有助于增强及修复人体组织和肌肉。许多运动员认为：因为肌肉是由蛋白质组成的，所以摄入大量的蛋白质食品会有助于增强肌肉。但事实并非如此。刺激肌肉增长的最有效途径是培训，而不是蛋白质补充剂。

　　运动员对蛋白质确实有比较大的需要，不过这可以通过精心规划、搭配合理的饮食来满足。增强肌肉的最佳办法就是摄入足够的食品，以补充当天消耗的能量。

　　对耐力运动员而言，建议每天摄入的蛋白质为每公斤体重1.2克到1.4克，而对接受阻力训练和力量训练的运动员而言，每天可能高达每公斤体重1.6克到1.7克。 
赞同
3
配制合理的饮食就是要选择多样化的食物，使所含营养素齐全，比例适当，以满足人体需要。 
1．粗粮、细粮要搭配：粗细粮合理搭配混合食用可提高食物的风味，有助于各种营养成分的互补，还能提高食品的营养价值和利用程度。 
2．副食品种类要多样，荤素搭配：肉类、鱼、奶、蛋等食品富含优质蛋白质，各种新鲜蔬菜和水果富含多种维生素和无机盐。两者搭配能烹调制成品种繁多，味美口香的菜肴，不仅富于营养，又能增强食欲，有利于消化吸收。 
3．主副食搭配：主食是指含碳水化合物为主的粮食作物食品。主食可以提供主要的热能及蛋白质，副食可以补充优质蛋白质、无机盐和维生素等。 
4．干稀饮食搭配：主食应根据具体情况采用干稀搭配，这样，一能增加饱感，二能有助于消化吸收。 
5．要适应季节变化：夏季食物应清淡爽口，适当增加盐分和酸味食品，以提高食欲，补充因出汗而导致的盐分丢失。冬季饭菜可适当增加油脂含量，以增加热能 配制合理饮食的方法: 
①根据具体情况（如性别、年龄、劳动强度），确定每日总热能及营养需要量。 
②根据碳水化合物（占60％～70％）、脂肪（占20％～25％）、蛋白质（占10％～15％）所占一日总热能的比例，分别计算其需要量。 
③确定每日需用的营养素后，根据食物所含的营养素计划每日膳食。 
④根据经济及供应情况确定每日供给主食和副食的数量。 
⑤最后计算出全部食物的各种营养素含量，并与供给标准相对照。若相差在±10％幅度内，即符合要求。 

赞同
VS运动量 

1.少于1小时 

原则:不需要额外补充食物，但要补充水分。 

推荐:每15分钟喝150～300毫升水。 

2.1～3小时 

原则:中等时间的运动，最好及时给身体补充糖分以免出现低血糖。 

推荐:可以补充含糖饮料，如体饮等运动饮料。或者喝白水，但要备有能够让糖分快速被吸收的食品，如果酱夹心饼干，水果干，谷物营养棒，果冻。 

3.超过3小时 

原则:较长时间的运动，需要准备大量的水以及能提供慢糖的食物(即糖分消耗较慢，逐步释放热量的食物)。 

推荐:每小时补充0.5升水，以及小黄油饼干，杏仁糕，甜乳制品，新鲜水果等含慢糖的食物。 

VS运动时间 

1.清晨运动 

原则:根据个人喜好，可以空腹运动或正常进食，但需在运动前、中、后补充足够的水分。 

不发胖的选择:如果有点饿，可以喝些饮品，如牛奶、果汁、豆浆等补充水分，又有饱足感；加片含纤维丰富的饼干或面包也可以。 

2.下午运动 

原则:在运动前3小时完成午餐，并补充水分。 

不发胖的选择:米饭或其他谷物类含碳水化合物的食物，能使你运动时精力充沛。如果做的是肌力训练，则应多吃含蛋白质的食物，如海鲜或低脂酸奶，能帮助肌肉组织生长。 

3.晚间运动 

原则:饭后1小时内运动，容易感到疲劳，因为肌肉活动需要富含氧的血液，而此时血液都流往消化道了。晚餐后3小时再做运动比较好。可以在运动后适度补水，但不要再大量补充食品，以免影响消化及睡眠。 

不发胖的选择:晚餐时可以选择谷物类、新鲜水果、淀粉类蔬菜等能维持体力又不致发胖的食物。但饭量应控制，因为晚上新陈代谢率较低，很容易囤积多余的卡路里。如果晚餐吃得很少或没吃，可以补充一点葡萄干、麦片等，或者是酸奶、一小片低脂面包。 

VS运动前后 

1.运动前 

原则:以低脂的碳水化合物为主。这些食物很容易消化，又能提供糖类，作为运动时的能量来源。 

推荐:一道含淀粉的主菜(如米饭、通心粉、土豆)，或其他谷类食物；2个水果。 

2.运动后 

原则:补充碱性食品。因为运动后体内的糖、脂肪、蛋白质会大量分解而产生较多的酸，使人感到肌肉酸痛，疲劳倦怠。如果再吃肉类或喝可口可乐等含糖高的酸性食品，反而会增加血液中酸度，从而更为加重人体肌肉的酸痛程度，使疲劳更无法及时消除。 

推荐:饮料可选择牛奶、豆浆、茶水、果汁(不加糖)、矿泉水或白开水。豆类也是好的食物选择。 

VS体型 

1.A型：较瘦削，很少脂肪，肌肉不太发达。 

最适合运动:适合A型身材的运动是用哑铃锻炼，使其看上去结实。 

最MATCH饮食:无太多忌讳。可适当补充点含蛋白质丰富的食品来增强肌肉。 

2.B型：肌肉均匀，身段轮廓分明，只要做适量运动便能消耗体内多余的脂肪，让身段更加迷人。 

最适合运动:有氧运动，以消耗热量和增强耐力。运动量以每周3次，每次30分钟为宜。 

最MATCH饮食:应避免吃高脂肪食物，薯片、牛油类和甜品也少吃为妙。 

3.C型：看上去较健硕，但易发胖，必须努力保持体态，勿让身体积聚多余脂肪。 

最适合运动:每周3次，每次1小时的有氧运动，这样能消耗脂肪，令身体更苗条。此外还可以在做有氧运动的3个月后开始哑铃类练习。 

最MATCH饮食:少吃用油煎炸的食物和含脂肪高的肉类，宜多吃蔬菜和鱼类。 

2.肉排 

比起其他含蛋白质丰富的食品，肉排中的蛋白质更能增强负重能力并锻炼更多肌肉。 

3.杏仁 

杏仁中含有大量的镁。研究显示，增加镁的摄入所产生的力量要比服用其他补充剂的效果强20%。 

4.椰菜 

椰菜中维生素C的含量在蔬菜中是最高的。半棵椰菜含有60毫克维生素C。研究发现补充维生素C的运动者训练后遭受的肌肉损伤比服用其他补充剂的运动员少。 

5.糙米 

与精米相比，糙米含有更多的精氨酸和赖氨酸。 

6.低脂冰激凌 

冰激凌可提供钙，一块即可补充150～200毫克的钙。如果是含巧克力的冰激凌，还能补充镁。 
http://www.wellw.com/sport/5/1/413144324.htm
参考资料：http://www.aliyiyao.com/man/nxbj/ydjs/jsjj/71226.html 
* position in front of desktop
Working Safely with Video Display Terminals

US Department of Labor
Alexis M Herman, Secretary

Occupational Safety and Health Administration
Gregory R Watchman, Acting Assistant Secretary

OSHA 3092
1997 (Revised)

Material contained in this publication is in the public domain and may be reproduced, fully or partially, without permission of the Federal Government Source credit is requested but not required.

This information will be made available to sensory impaired individuals upon request.

Voice phone: (202) 219-8615; Telecommunications Device for the Deaf (TDD) message referral phone: 1-800-326-2577

Contents

Introduction

VDT Components

Health Effects
Visual Problems
Fatigue and Musculoskeletal Problems
Radiation

Interventions
Lighting
Work Station Design
VDT Design
Work Practices Job Organization 

Other Sources of OSHA Assistance
Safety and Health Program Management Guidelines
State Programs
Consultation Services
Voluntary Protection Programs
Training and Education
Electronic Information
Emergencies

Appendix

Selected Bibliography

OSHA Related Publications

States with Approved Plans

OSHA Consultation Project Directory

OSHA Area Offices

OSHA Regional Offices

Introduction

The applications of computer technology and the accompanying use of video display terminals (VDTs) are revolutionizing the workplaces of America, and their use will continue to grow in the future.

For example, in 1984 only 25 percent of the U.S. population used computers at work; in 1993, more than 45 percent of the population used computers at work and the number continues to grow. Also, more than 18 million workers are in jobs that often require intensive keying.

Along with this expanding use of VDTs have come reports about adverse health effects for VDT operators. To help inform employers and employees, this booklet briefly examines the potential hazards and interventions employers can use to prevent or reduce the potential harmful effects of working with VDTs.

Some of the most common stressors, their related health effects, and their means of prevention are discussed. A checklist to assess workstations also is included. (See Appendix.) 

VDT Components

VDTs -- comprised of a display screen, a keyboard, and a central processing unit -- have rapidly replaced the use of typewriters and other office machines.

The display screen is the output device that shows what the computer is processing. Display screens can be monochrome (green, white, or orange on a black background), or full color. The keyboard is the input device that allows the user to send information to the "brains" of the computer. Keyboards are commonly used for data entry and inquiry. The keyboard is similar to a standard typewriter keyboard but with additional special keys and functions.

The central processing unit is referred to as the "brains" of the computer. It is the center of operation for all the computer processing and performs calculations and organizes the flow of information into and out of the system.

The VDT operates at high voltages, but the power supplies generating these voltages produce very little current. All data processing equipment, including VDTs, must meet stringent international safety standards in this regard. 

Health Effects

In the wake of the expanding use of VDTs, concerns have been expressed about their potential health effects. Complaints include excessive fatigue, eye strain and irritation, blurred vision, headaches, stress, and neck, back, arm, and muscle pain. Research has shown that these symptoms can result from problems with the equipment, work stations, office environment or job design, or from a combination of these. Concerns about potential exposure to electromagnetic fields also have been raised.

Visual Problems
Visual problems such as eyestrain and irritation are among the most frequently reported complaints by VDT operators. These visual symptoms can result from improper lighting, glare from the screen, poor positioning to the screen itself, or copy material that is difficult to read. These problems usually can be corrected by adjusting the physical and environmental setting where the VDT users work. For example, work stations and lighting can and should be arranged to avoid direct and reflected glare anywhere in the field of sight, from the display screen, or surrounding surfaces. Many VDT jobs require long sessions in front of a display screen. Consequently, some people may need corrective lens to avoid eye strain and headaches. Vision examinations should, therefore, be conducted to ensure early detection and correction of poor vision. Eyecare specialists should be informed of computer use by VDT operators.

VDT operators also can reduce eyestrain by taking rest breaks, after each hour or so of operating a VDT.(*)

Changing focus is another way to give eye muscles a chance to relax. The employee needs only to glance across the room or out the window from time to time and look at an object at least 20 feet (6.096 meters) away.

Fatigue and Musculoskeletal Problems
Work performed at VDTs may require sitting still for considerable time and usually involves small frequent movements of the eyes, head, arms, and fingers. Retaining a fixed posture over long periods of time causes muscle fatigue and, if this practice is consistent, can eventually lead to muscle pain and injury.

VDT operators also are subject to a potential risk of developing various musculoskeletal disorders such as carpal tunnel syndrome, and tendonitis. Musculoskeletal disorders are injuries to the muscles, joints, tendons, or nerves that are caused or made worse by work related risk factors. Early symptoms of musculoskeletal disorders include pain and swelling, numbness and tingling (hands falling asleep), loss of strength, and reduced range of motion.

If workers have any of these symptoms, they should report them to their employers as soon as possible. If these symptoms are not treated early, they can result in loss of strength in affected area, chronic pain, or permanent disability.

Radiation
Another issue of concern for the VDT operator is whether the emissions from radiation, such as X-ray or electromagnetic fields in the radiofrequency and extreme low frequency ranges, pose a health risk. Some workers, including pregnant women, are concerned that their health could be affected by electromagnetic fields emitted from VDTs. The threat from X-ray exposures is largely discounted because of the very low emission levels. The radio frequency and extreme low-frequency electromagnetic fields are still at issue despite the low emission levels. To date, however, there is no conclusive evidence that the low levels of radiation emitted from VDTs pose a health risk to VDT operators. Some workplace designs, however, have incorporated changes -- such as increasing the distance between the operator and the terminal and between work stations -- to reduce potential exposures to electromagnetic fields.

Because the possible effects of radiation from VDTs continue to concern operators, the issue is still being researched and studied. NIOSH has a resource booklet entitled,NIOSH Publications on Video Display Terminals and continues to study the question of VDT operator risk from exposure to electromagnetic fields. 

Interventions

There are a variety of interventions that employers can implement to reduce or prevent harmful effects associated with VDT use.

Lighting
Light should be directed so that it does not shine into the operator's eyes when the operator is looking at the display screen. Futher, lighting should be adequate for the operator to see the text and the screen, but not so bright as to cause glare or discomfort (see Figure 1).

There are four basic lighting factors that must be controlled to provide suitable office illumination and avoid eyestrain: quantity, contrast, and direct and reflected glare.


Figure 1. Position of light source relative to the VDT.

Quantity. In most offices, light fixtures and daylight provide illumination for work surfaces (e.g., 50-100 foot-candles). High illumination "washes out" images on the display screen; therefore, if possible, where VDTs are used, illumination levels should be somewhat lower (i.e., 28-50 foot-candles are often satisfactory).

Contrast. Contrast is the difference in luminance or brightness between two areas. To prevent the visual load caused by alternate light and dark areas, the difference in illuminance between the VDT display screen, horizontal work surface, and surrounding areas should be minimized.

Most of the tasks associated with VDTs do not require precise visual acuity, and diffuse (indirect) lighting is appropriate. The advantages of diffuse lighting are twofold: There tend to be fewer hot spots, or glare sources, in the visual field; and the contrasts created by the shape of objects tend to be "softer." The result, in terms of luminous intensities, is a more uniform visual field. Where indirect lighting is not used, parabolic louvers on overhead lights are probably the next best way to ensure that light is diffused.

Glare. Glare is usually defined as a harsh, uncomfortably bright, light. Glare is dependent upon the intensity, size, angle of incidence, luminance, and proximity of the source to the line of sight. Glare may be the result of direct light sources in the visual field (e.g., windows), or reflected light from polished surfaces (e.g., keyboards) or from more diffuse reflections which may reduce contrast (e.g., improper task lighting). Glare may cause annoyance, discomfort, or loss in visual performance and visibility.

To limit reflection from walls and work surfaces visible around the screen, these areas should be painted a medium color and have a nonreflective finish. Work stations and lighting should be arranged to avoid reflected glare on the display screen or surrounding surfaces.

In many cases, the reorientation of work stations may help remove sources of glare out of the line of sight. The face of the display screen should be at right angles to windows and light sources. Care should be taken, particularly when terminals are installed within 20 feet (6.096 meters) of windows, to ensure that there is some method of blocking the sun's light, such as blinds or curtains.

The proper "treatment" for window glare includes baffles, venetian blinds, draperies, shades, or filters.

Screen glare filters that attach directly to the surface of a VDT screen can help reduce glare. Two types of filters are available: natural density filters, which scatter and diffuse some of the light reflected off the glass display screen, and micromesh filters, which not only scatter the light but also absorb most of the light reflected from the surface of the screen by means of an imbedded interwoven grid of dyed nylon fibers. These should be used as a last resort since filters can reduce visibility and legibility of screen. Filters should be cleaned regularly.

Work Station Design
Proper work station design will reduce visual and musculoskeletal discomfort associated with VDT use when the following work practices are observed:
Ensure that the operator has a comfortable sitting position sufficiently flexible to reach, use, and observe the display screen, keyboard, and document.
Provide posture support for the back, arms, legs, and feet as well as adjustable display screens and keyboards.
Ensure that VDT tables or desks are vertically adjustable to allow for operator adjustment of the screen and keyboard.
Ensure proper chair height and support to the lower region of the back.
Ensure that document holders are used to allow the operator to position and view material without straining the eyes or neck, shoulder, and back muscles.
The type of task performed at the VDT may also influence the development of fatigue. In designing a work station, the type of tasks involved should be considered when determining the placement of the display screen and keyboard. For example, if the job requires the operator to look mainly at the source document than the display screen, the source document should be in front of the operator and the screen may be to the side. (See Figure 2.)


Figure 2. Alternative VDT arrangements (depending on job task).

The employee must have adequate work space to perform each of the tasks required by the job. Individual body size must be considered and will influence the design of the work station and access to various accessories.

In general, VDT work stations should provide as many adjustable features as possible. Also, adequate legroom should be provided for the employee to stretch out and relieve some of the static load that results from sitting with the legs in a fixed position for long periods.

In the office environment, the work station consists primarily of a work surface, a chair, VDT equipment, and other related accessories (see Figure 3).


Figure 3. Proper user position and support.

Chairs. The chair can be a crucial factor in preventing back pain as well as in improving employee performance in office work. As the majority of office workers spend most of their time sitting, a properly designed and adjustable chair for comfort, efficiency, and for the task being performed is critical. All adjustments should easily be made from the seated position. Specific chair criteria are discussed in the following paragraphs.

Chair Height. When an employee spends from 6 to 8 hours in the chair, the height of the chair and the work surface are critical. The human body dimension that provides a starting point for determining correct chair height is the "popliteal" height. This is the height from the floor to the point at the crease behind the knee. The chair height is correct when the entire sole of the foot can rest on the floor or footrest and the back of the knee is slightly higher than the seat of the chair. This allows the blood to circulate freely in the legs and feet.

Seatpan Design. Size and shape are two factors to consider in the design of the seatpan of the chair. The seatpan should be slightly concave with a softly padded, rounded, or "waterfall" edge. This will help distribute the weight and may also prevent sliding forward in the chair. The angle of the seatpan should also be considered. Some options include a seatpan that slopes slightly down at the back or one that has a forward tilt that produces less stress on the lower region.

Armrests. Armrests should be low and short enough to fit under work surfaces to allow users to get close enough to the work surface. Chairs can be purchased with adjustable armrests.

Backrest. A proper backrest should support the entire back including the lower region. The seat and backrest of the chair should support a comfortable posture that permits frequent variations in the sitting position. The backrest angle and chair height should be easily adjustable.

VDT Design
Display Screen. Most new VDTs have separate, adjustable keyboards and display screens that allow both the keyboard and display screen to be positioned appropriately for the employee. This is important because VDT operators may spend a considerable amount of time looking at the display. Screens should have user controls for character brightness. Screens that swivel horizontally and tilt or elevate vertically enable the operator to select the optimum viewing angle.

The topmost line of the screen should not be higher than the user's eyes. The screen and document holder should be the same distance from the eye (to avoid constant changes in focus) and close enough together so the operator can look from one to the other without excessive movement of the neck or back. People who wear bifocals often have to tilt their head back to read through the bottom portion of their lenses. They should avoid tilting their head back by lowering the display or using single-lens glasses while using the VDT.

The preferred viewing distance for VDTs ranges between 18 and 24 inches (45.72 and 60.96 centimeters, respectively). To this distance must be added the depth of the display itself. Some displays are as much as 20 inches deep (50.80 centimeters). The best way to deal with this, other than increasing table depth, is to install a keyboard extender or tray underneath the desk.

Legibility is also a primary consideration in selecting a display screen. Legibility factors to be considered include symbol size and design, contrast, and sharpness.

Keyboard. The keyboard should be detachable and adjustable to ensure proper position, angle, and comfort for the operator. A lower-than-normal work surface may be required to keep the operator's arms in a comfortable position. This can be achieved by installing a keyboard extender or tray. The thickness and the slope of the keyboard are critical in determining the preferred height.

The preferred working position for most keyboard operators is with the forearms parallel to the floor and elbows at the sides, which allows the hands to move easily over the keyboard. The wrist should be in line with the forearm. A padded and detachable wrist rest for the keyboard can help keep the operator's wrists and hands in a straight position while keying.

Mouse. The mouse should be positioned at the operator's side with his or her arm close to the body for support, while maintaining a straight line between the hand and forearm. The upper arm should not be elevated or extended while using the mouse. The top surface of the wrist should also be flat, not angled. A mouse pad or rest can be used to help maintain straight wrists.

Work Practices Job Organization
Operating a VDT, like any form of sustained physical or mental work, may lead to visual, muscular, or mental fatigue. Rest pauses, as recommended by NIOSH to alleviate or delay the onset of fatigue, are necessary. Jobs should be designed so that the employees can vary VDT tasks with non-VDT tasks. In addition, open and positive working relationships between the worker and manager as well as involving employeees in workplace decisions and practices can be factors in reducing muscle tension and musculoskeletal disorders. 

Other Sources of OSHA Assistance

Safety and Health Program Management Guidelines
Effective management of worker safety and health protection is a decisive factor in reducing the extent and severity of workrelated injuries and illnesses and their related costs. To assist employers and employees in developing effective safety and health programs, OSHA published recommended Safety and Health Program Management Guidelines (Federal Register 54 (18): 3908-3916, January 26, 1989). These voluntary guidelines apply to all places of employment covered by OSHA.

The guidelines identify four general elements that are critical to the development of a successful safety and health management program:
management commitment and employee involvement,
worksite analysis,
hazard prevention and control, and
safety and health training.
The guidelines recommend specific actions under each of these general elements to achieve an effective safety and health program. A single free copy of the guidelines can be obtained from the U.S. Department of Labor, OSHA Publications, P.O. Box 37535, Washington, DC 20013-7535, by sending a self addressed mail label with your request.

State Programs
The Occupational Safety and Health Act of 1970 encourages states to develop and operate their own job safety and health plans. States with plans approved under section 18(b) of the Act must adopt standards and enforce requirements that are at least as effective as federal requirements. There are currently 25 state plan states: 23 of these states administer plans covering both private and public (state and local government) employees; the other 2 states, Connecticut and New York, cover public employees only. Plan states must adopt standards comparable to federal requirements within 6 months of a federal standard's promulgation. Until such time as a state standard is promulgated, federal OSHA provides interim enforcement assistance, as appropriate, in these states. A listing of approved state plans appears at the end of this publication.

Consultation Services
Consultation assistance is available on request to employers who want help in establishing and maintaining a safe and healthful workplace. Largely funded by OSHA, the service is provided at no cost to the employer. Primarily developed for smaller employers with more hazardous operations, the consultation service is delivered by state government agencies or universities employing professional safety consultants and health consultants. Comprehensive assistance includes an appraisal of all mechanical, physical work practices and environmental hazards of the workplace and all aspects of the employer's present job safety and health program.

The program is separate from OSHA's inspection efforts. No penalties are proposed or citations issued for any safety or health problems identified by the consultant. The service is confidential.

For more information concerning consultation assistance, see the list of consultation projects at the end of this publication.

Voluntary Protection Programs (VPPs)
Voluntary Protection Programs (VPPs) and onsite consultation services, when coupled with an effective enforcement program, expand worker protection to help meet the goals of the OSH Act. The three VPPs -- Star, Merit, and Demonstration -- are designed to recognize outstanding achievement by companies that have successfully incorporated comprehensive safety and health programs into their total management system. They motivate others to achieve excellent safety and health results in the same outstanding way as they establish a cooperative relationship among employers, employees, and OSHA.

For additional information on VPPs and how to apply, contact the OSHA area or regional offices listed at the end of this publication.

Training and Education
OSHA's area offices offer a variety of informational services, such as publications, audiovisual aids, technical advice, and speakers for special engagements. OSHA's Training Institute in Des Plaines, IL, provides basic and advanced courses in safety and health for federal and state compliance officers, state consultants, federal agency personnel, and private sector employers, employees, and their representatives.

OSHA also provides funds to nonprofit organizations, through grants, to conduct workplace training and education in subjects where OSHA believes there is a lack of workplace training. Grants are awarded annually and grant recipients are expected to contribute 20 percent of the total grant cost.

For more information on grants, training and education, contact the OSHA Training Institute, Office of Training and Education, 1555 Times Drive, Des Plaines, IL 60018, (847) 297-4810; (847) 297-4874 fax.

For further information on any OSHA program, contact your nearest OSHA area or regional office listed at the end of this publication.

Electronic Information
Internet -- OSHA standards, interpretations, directives, and additional information are now on the World Wide Web at http://www.osha.gov.

CD-ROM -- A wide variety of OSHA materials including standards, interpretations, directives, and more can be purchased on CD-ROM from the Government Printing Office. To order, write to Superintendent of Documents, P.O. Box 371954, Pittsburgh, PA 15250-7954. Specify OSHA Regulations, Documents and Technical Information on CD-ROM, (ORDT), S/N 729- 1300000-5. The price is $38 per year ($47.50 foreign); $15 per single copy ($18.75 foreign).

Emergencies
To report life-threatening situations, fatalities, or catastrophes, call (800) 321-OSHA. Complaints will go immediately to the nearest OSHA area or state office for help.

For further information on any OSHA program, contact your nearest OSHA area or regional office listed at the end of this publication.

For further information on VDTs, please consult the following sources:
Occupational Safety and Health Administration (OSHA)
U.S. Department of Labor
Technical Data Center, Room N2439
200 Constitution Avenue, N.W.
Washington, D.C. 20210

U.S. Department of Health and Human Services
Public Health Service
Center for Disease Control
National Institute for Occupational Safety and Health (NIOSH)
Robert A. Taft Laboratories
4676 Columbia Parkway
Cincinnati, OH 45226-1998

Appendix

Video Display Terminal (VDT) Checklist

Can the work station be adjusted to ensure proper posture by
adjusting knee and hip angles to achieve comfort and variability,     Yes   No
supporting heels and toes on the floor or on a footrest,     Yes   No
placing arms comfortably at the side and hands parallel to the floor, and     Yes   No
supporting wrist (nearly straight) on a padded surface?     Yes   No
Does the work area
provide enough clearance for the feet, knees, and legs relative to the edge of the work surface;     Yes   No
provide sufficient space for the thighs between the work surface and the seat;     Yes   No
include arm rests for intensive or long duration keying jobs; and     Yes   No
include headsets for use when frequent telephone work is combined with hand tasks such as typing, using a calculator, or writing?     Yes   No
Does the chair
adjust easily from the seated position,     Yes   No
have a padded seat pan,     Yes   No
have a seat that is approximately 18 inches wide (45.72 centimeters),     Yes   No
have a back rest that provides lumbar support that can be used while working,     Yes   No
have a stable base with casters that are suited to the type of flooring,     Yes   No
have different seat pan lengths (15 to 17 inches or 38.10 and 43.18 centimeters) with a waterfall design available, and     Yes   No
allow the seat pan to adjust for both height (minimum of 4 1/2 inches or 10.16-1.27 centimeters) and angle (plus or minus 5 degrees)?     Yes   No
Is the keyboard
height from the floor and the slope of the keyboard surface adjustable,     Yes   No
prevented from slipping when in use, and     Yes   No
detachable?     Yes   No
Are other inputs/devices (mouse, pointer, calculator)
at keyboard height?     Yes   No
Is the display screen
clean and free from flickering, and     Yes   No
able to swivel horizontally and tilt or elevate vertically?     Yes   No
Is the monitor situated so that
the work can be performed with the head in a neutral posture for most of the workshift,     Yes   No
it is between 18 and 30 inches (45.72 and 76.20 centimeters, respectively) away from the operator,     Yes   No
the top line of text is at or slightly below eye height, and     Yes   No
there is sufficient lighting without glare on the screen from lights, windows, or surfaces?     Yes   No
Does the monitor
have brightness and contrast controls?     Yes   No
Is the job organized so that
workers can change postures frequently,     Yes   No
workers can perform different job tasks to reduce intensive keying,     Yes   No
workers can leave their workstations for at least 10 minutes after each hour of intensive keying and for at least 15 minutes after every 2 hours of intermittent keying, and     Yes   No
the workers have received training in ergonomics and know how to make adjustments to their work stations, chairs, and other accessories?     Yes   No


Selected Bibliography

Arnt, R. "Working Posture and Musculoskeletal Problems of Video Display Terminal Operators: Review and Reappraisal." Am Ind Hyg Assoc J 44: 437-446, 1983.

Carter, J.B. and Banister, E.W. "Musculoskeletal Problems in VDT Work: A Review." Ergonomics 37(10):1623-1648, 1994.

Clift, Elayne. "Personal Computers -- User Friendly?" Gov Exe 21 (8):38-40. August 1989.

Grandjean, Etienne. Ergonomics in Computerized Offices. New York: Taylor & Francis, 1987. 227 Pp.

Kroemer, K.H.E. "Avoiding Cumulative Trauma Disorders in Shops and Offices." Am Ind Hyg Assoc J 53(9):596-604, 1992.

Murray, W.E.; Mass, C.E.; Parr, W.H.; and Cox, C. "A Radiation and Industrial Hygiene Survey of Video Display Terminal Operations." Hum Factors 23:413-420, 1981.

Pascarelli, E. and Quilter, Deborah. Repetitive Strain Injury -- A Computer User's Guide. John Wiley and Sons, Inc., New York, 1994.

Peterson, John E. "RMI: The Hazard of the 90s." Science/ Health Section. Marin Indep J:F6. July 30, 1989.

U.S. Department of Health and Human Services. National Institute for Occupational Safety and Health (NIOSH), Public Health Service. NIOSH Publications on Video Display Terminals (Revised). NIOSH, Cincinnati, OH, 1991.


OSHA Related Publications

A single free copy of the following materials may be obtained from the OSHA Publications Office, U. S. Department of Labor, 200 Constitution Avenue, N.W., Room N3101, Washington, DC 20210, (202) 219-4667; (202) 219-9266 (fax), or from the nearest OSHA regional or area offices listed at the end of this booklet. Please send a self-addressed label with your written request.
All About OSHA – OSHA 2056

Consultation Services for the Employer – OSHA 3047

Employee Workplace Rights – OSHA 3021

Ergonomics Program Management Guidelines for Meatpacking Plants – OSHA 3123

How to Prepare for Workplace Emergencies – OSHA 3088

OSHA Publications and Audiovisual Programs – OSHA 2019

Personal Protective Equipment – OSHA 3077
The following publications are available from the U.S. Government Printing Office, Superintendent of Documents, Washington, DC 20402, (202) 512-1800. Include GPO Order No. and make checks payable to Superintendent of Documents.
Ergonomics: The Study of Work
Order No. 029-016-00124-7. Cost: $1.00

Job Safety & Health Quarterly
Order No. JSH. Cost: $9.50/year (Foreign $11.90)

