#+SETUPFILE: theme-bigblow.setup
* Literature
- ojects
- methods
- Results

** marine(ocean) energy
- current :: motion of water
Marine energy – also referred to as ocean energy, ocean power and marine hydrokinetic energy (MHK) – *encompasses* various means through which energy can be harnessed from our oceans.[fn:emec]
 There are various types of marine energy, including wave, tidal stream, tidal range and offshore wind, as well as ocean thermal, ocean current, run-of-river and salinity. 
[fn:emec]http://www.emec.org.uk/marine-energy/

most interest marine energy
- wave 
- tidal 

At EMEC, we provide test sites for *wave and tidal stream energy convertors*, so when we refer to marine energy we are referring specifically to these two ocean energy sources.

Devices to harness wave and current energy

Tidal current electricity – sometimes known as tidal stream electricity - is clean, renewable, reliable and most importantly, predictable. Atlantis is a leading tidal power technology developer.
There is often confusion regarding the different types of tidal power, and indeed between tidal current power and wave power.  To summarise:

-	Wave energy converters: these harness the motion of waves, which are primarily generated by the wind
-	Tidal lagoons and tidal barrages: a barrage is constructed across a bay or inlet to create a captive reservoir.  
The rise and fall of the tides produces a difference in height between the reservoir and the open ocean and this is used to drive turbines fitted in the barrage

-	Tidal current or tidal stream: these turbines use the *kinetic* power of tidal currents /in the same way that/ wind turbines use the movement of air.  
This type of generation has lower capital cost and minimal environmental and visual impact.
 
Sea water is 832 times denser than air, giving ocean currents an extremely high energy density, 
which means that tidal turbines have a smaller rotor size than an offshore wind turbine of equivalent power rating. 
Tidal turbines require less seabed for an equivalent amount of installed generation capacity when compared to wind power, 
because tidal turbines can be installed closer together within each array. 
Unlike traditional hydro power or tidal barrage schemes, 
tidal current power does not require significant alternation of the natural environment 
and has the obvious advantage of minimal visual pollution when compared to offshore wind. 

#  tidal energy vs other energy, such as wind energy
Tidal energy’s greatest advantage over other alternative energy sources is that it is almost entirely independent of the weather and hence, 
although it is variable, it is also predictable.  Other variable renewables, including wind, wave, solar and hydroelectricity are affected, on varying timescales, by climatic fluctuations which can create challenges for the balancing of the transmission system.  Hydroelectricity is subject to seasonal changes and very vulnerable to droughts; available solar power varies at seasonal, daily and instantaneous timescales; and wind and wave climates fluctuate on both seasonal and very short term timescales.
As water covers over 70% of the Earth’s surface, the oceans represents a vast source of energy.  We have already identified 25GW of potential tidal stream resource, and other estimates are even higher. [fn:RenewableUK] 



[fn:RenewableUK] http://www.bwea.com/marine/index.html





>> report, Future Marine Energy results of the marine energy challenge cost competitiveness and growth of wave and tidal stream energy
** Devices to extract tidal energy
- Tidal basin 
- Tidal turbine
** Industrial report
http://www.emec.org.uk/marine-energy/industry-reports/

** Types, and catergories
- horizontal, vertical

- based on size
  + small model
  + large, prototypes
  + array

- based on number of turbines
  + islated turbine

  + dual rotors

  + turbine arrays

- Steady inflow vs Unsteady inflow
  + unsteady flow
    + yaw, device misalignment
    + high turbulence levels
    + velocity shear, such as surface wave
*** HAMCT VS VAMCT
% types of MCTs, HAMCT vs VAMCT
Hydro-kinetic turbines can come in several forms, and  two basic configurations are  the horizontal axis and  vertical axis turbine.

 The vertical axis turbine can be lift or drag based device. The drag-based device is typically limited to low tip speed ratio (\(TSR\)) and the lift-based device excels at high \(TSR\), where \(TSR=\omega R/V\),  \( \omega\) is the rotational speed of the turbine, e.g. round per minute (RPM), \(R\) is its radius and \(V\) is the incoming water velocity. The lift-based vertical axis turbine can produce a higher coefficient of power  \(C_P\) than the drag-based one, but it is still not as high of the horizontal axis turbine. This is because the blade profile is at the wrong angle of attack (\(AOA\)) during some of the the cycle of the vertical axis turbine \cite{korakianitis2015aerodynamics}. %(Korakianitis et al, 2015).
%pitch control
This can be partly mitigated using a variable pitch for the blades, setting the blade orientation during the cycle in order to place it in a way of producing high hydrodynamic efficiency (lift to drag ratio) most of the cycle. This method has gained good interest and  coupling this approach with computational fluid dynamics (CFD) design has been suggested \cite{quayle2007integrating}. % (Ouayle & Rennie, 2007).
However, it also leads to complexity in terms of additional machinery on the turbine and appropriate pitch-control which we try to avoid in this study. 

% passive control of VAMCT
Other methods that follow the spirit of simplicity as one would wish to find in small to medium low cost marine current turbines is passive control.  This can be achieved by maintaining the vertical axis turbine at high \(TSR\), but this may cause the turbine to miss the optimal coefficient of power  \(C_P\). One can try to delay stall on the turbines blades using a new profile design such as the presCrIbed suRface Curvature distribution bLade dEsign (CIRCLE) which seeks to remove curvature discontinuity and thus was shown to push the stall angle a few degrees by delaying the burst of the profile leading-edge septation bubble \cite{shen2017computational,shen2016experimental}.
%(Shen et al, 2017a,b). 
% Gurney flaps
One can also seek to add devices of adding high lift as Gurney flaps that were found to increase the hydrodynamic efficiency of a simple H vertical turbine, i.e. turbine with straight blades, but not to delay separation% (Yan et al, 2018). 
%%MVGs
Micro-vortex generators (MVGs) that seek to energise the boundary layer and thus avoid its separation are also a possible engineering solution \cite{heffron2016flow}. %.(Heffron et al, 2016). 
However, one should pay attention in this design that the suction and pressure surfaces of the profile switch places during the cycle and thus can affect the location and type of MVGs to be used. All these methods can be employed to try to boast the  \(C_P\) of the vertical axis turbine. However, they still cannot mitigate completely the problem that the profile's \(AOA\) keep changing during the rotation of the blade and thus the expected level of  \(C_P\) is still usually lower than that of the horizontal axis turbine that maintains a steady \(AOA\) for the blade profile for a steady incoming stream when it is properly positioned.


** pitch and yaw control in MCT
For a given rated power,
C_T(tidal turbine ) = 4 C_T(wind turbine )

- The strongly *bi-directional* nature of the flow encountered at many tidal energy sites  
may lead to devices employing zero rotor yaw control (Pascal,2011)

** wave current interaction
The co-existence of waves and currents is a common feature in the marine environment 
 Waves are strained and refracted by currents, causing exchanges of mass, momentum and energy to occur between the waves and mean flow [2]. The main energy in the coastal region can be attributed to tides, surges and wind waves. Interactions occur between these different ‘waves’ because the tides and surges change the mean water depth and current field experienced by the waves [3]. The usual approach to the interaction problem has been to ignore the interaction between waves and currents and simply add the two together (using their particle velocity vectors) so as to calculate the forces on a body [4].
Marine [fn:galloway2011experimental]

** Blade design
  + nubmer of blades
  + blade profiles
    - symmetric
    - unsymmetric profile
  + design methods
** Quantities of interst
  + power and thrust
  + wake
** Methods, mehodology

*** Experimental Study

**** small scale model
Bahaj 2007


**** On-site full scale
keywords:  Experimental study

1. Hydrodynamic loadings on a horizontal axis tidal turbine prototype
- lust, PhD Dissertation, 2017, Uni. of Maryland, USA
  + effect of sine surface wave effect on Turbine

2. Ouro, Pablo, et al. "Hydrodynamic loadings on a horizontal axis tidal turbine prototype." 
Journal of Fluids and Structures 71 (2017): 78-95.
  + in- house code, 

3. Experimental study of hydrodynamic performance of full-scale horizontal axis tidal current turbine
  ~\cite{jing2017experimental}

4. Milne  et al.2013 Characteristics of theturbulence in theflow at atidalstream power site. Phil Trans R Soc A 371: 20120196. http://dx.doi.org/10.1098/rsta.2012.0196
*** Numerical 
**** CFD
**** BEM
**** BEM-CFD
To limit the computational burden, CFD modelling of turbines is
often addressed using simplified models in which the blades are not explicitly solved as solid boundaries of the fluid domain but their effect is indirectly taken into account via suitable forcing terms in the momentum equations.
a.Day, 2015 ([[https://doi.org/10.1016/j.oceaneng.2015.05.036][A.H.Day, 2015 ocean engineering]])
** Tidal turbine

In the past decade, intensive research has been done on marine current turbine. Recently,
Kai-Wern Ng et al \cite{ng20132002} reviewed the research progress (2002-2012) in horizontal axis marine
current turbine which covers energy assessment, turbine design, wakes, generators, novel
modifications, environmental impact and future trends. The review provide an excellent
overview of research on horizontal axis marine current turbine and more than one hundred
references are cited.
** References

*** Reviews
- Ahmad 2017 Tidal power technology review with potential applications in Gulf Stream
- A. Day, Hydrodynamic modelling of marine renewable energy devices: A state of the art review

** wake behind a turbine

wake tidal turbine

effect of  submerged depth on the downstream wake structure and its recovery to the free-stream velocity  (zhang 2017, eergies)


Chamorro
 et al  (2013). On the interaction between a turbulent open channel flow and an axial-flow turbine. 
Journal of Fluid Mechanics, 658-670.

**  Wind turbine VS Tidal turbine
*Commons:*
Tidal turbine borrow a lot from wind turbine theories
 Much of the technology and modeling used for the marine current turbine (MCT) has been imported from the wind power industry which in turn has relied on aerospace technology developed  for propellers and fans. 


*Difference/Challenges*
\begin{itemize}
	\item Free surface, Gravity wave
	\item Cavitation
\end{itemize}

However, the free-stream MCT faces challenges different from its wind turbine counterpart. While the flow direction is well known in advance, it turns to the opposite direction during the day and flow unsteadiness can be enhanced by gravity waves as well as cavitation. The latter can occur for high flow velocities and when the blade passes near the free (water) surface reducing the static pressure below the threshold level. This is not common for MCTs~\cite{bahaj2007power}. However, the effect of gravity waves and particularly surface waves (i.e. maximum water displacement at the free surface) is more common and can degrade the turbine performance. 

** Results and discussion
quantites: CP, CT, wake, vorticity, pressure contour, velocity contour
?? what are pressure contour, velocity contour used for blade design?

*** Cp vs time

*** local AOA
Guntur_2014_An evaluation of several methods of determining the local angle of attack on wind turbine blades
2018 Eva Jost Angle of Attack (AoA), turbine,  Extracting the angle of attack on rotor blades from CFD simulations
2017 Jost, Eva, et al. "Extracting the angle of attack on rotor blades from CFD simulations." Wind Energy (2017).
2018 Rahimi, Hamid, et al. "Evaluation of different methods for determining the angle of attack on wind turbine blades with CFD results under axial inflow conditions." Renewable Energy 125 (2018): 866-876.
** Array

laterial spacing affects the wake recovery [fn:stallard2013interactions]
lateral spacing of 2D or less, adjacent wakes begin to merge within 2D downstream of the rotor plane and merge within 4D downstream.
[fn:stallard2013interactions] Stallard, T., et al. "Interactions between tidal turbine wakes: experimental study of a group of three-bladed rotors." Phil. Trans. R. Soc. A 371.1985 (2013): 20120159.
wake characteristics is an important parameters for array 

- 2016 Olczak, Alexander. The influence of waves on tidal stream turbine arrays. Diss. University of Manchester, 2016.
- Peter Stansby, 2016, Fast optimisation of tidal stream turbine positions for power generation in small arrays with low blockage based on superposition of self-similar far-wake velocity deficit profiles
- Nuernberg, M., and L. Tao. "Experimental Study of Wake Characteristics in Tidal Turbine Arrays." Renewable Energy (2018).

the effect of lateral and stream-wise turbine spacings , The staggered array with decreased streamwise spacing 
is shown to have the highest total power per 'footprint' area
- 2018  Sutherland et al, Experimental optimisation of power for large arrays of cross-flow tidal turbines
Three dimensional tidal turbine array simulations using OpenFOAM with dynamic mesh


** power coefficient

- flow separations
  + flow sepations must be avoided for best performance

# Definition of the power coefficient
a paper about the definition of the power coefficient for different types of turbine~\cite{li2014definition}.






\begin{equation}
   C_p=\frac{P}{P_ref}
\end{equation}
Where, $P$ is actual power output, $P_ref$ is reference power, which is used to nondimensionalize the actual power output.


Theoretically, for such an undisturbed free stream flow through $\frac{1}{2} \rho AU_ \infty ^2$ (where $\rho$, $A$ and $u_\infty$ denote the water density, the frontal area of the turbine and the far-field incoming flow velocity, respectively), we can have the maximum power output as$\frac{1}{2} \rho AU_ \infty ^3$
.
Reference power is 
\begin{equation}
P_{ref}=\frac{1}{2} \rho AU_ \infty ^3.
\end{equation}
thus power coefficient is
\begin{equation}
C_p=\frac{P}{\frac{1}{2}\rho AU_ \infty ^3}
\end{equation}


** Organization/company
https://www.atlantisresourcesltd.com/services/turbines/history/
European Marine Energy Centre

the european marine energy centre LTD

[[http://www.emec.org.uk/marine-energy/tidal-developers][a list of companies]]
[[https://www.atlantisresourcesltd.com/services/turbines/][atlantis]] RESOURCES LTD
company  country  device name device type
Andritz Hydro Hammerfest	Norway	HS1000	Horizontal Axis Turbine
Aquantis Ltd	USA	AQ Series	
Atlantis Resources Corp	UK	AR-1500	Horizontal Axis Turbine
Atlantis Resources Corp	UK	AR-1000	Horizontal Axis Turbine
Atlantisstrom	Germany	Atlantisstorm	Horizontal Axis Turbine
Balkee Tide and Wave Electricity	Mauritius	Tidal and Wave Power Electrical Generator (TWPEG)	Horizontal Axis Turbine
BioPower System Pty Ltd	Australia	bioStream	Other
Bluewater	Netherlands	BlueTEC (Bluewater Tidal Energy Converter)	Other
Bosch Rexroth	Germany		Horizontal Axis Turbine
Bourne Energy	USA	CurrentStar	Horizontal Axis Turbine
Bourne Energy	USA	TidalStar	Horizontal Axis Turbine
Bourne Energy	USA	OceanStar	Horizontal Axis Turbine
Centro Tecnologico SOERMAR	Spain	PROCODAC	
Cetus Energy	Australia	Cetus Turbine	Horizontal Axis Turbine
Current Power AB	Sweden	Current Power	Vertical Axis Turbine
Current2Current	UK	Tidal Turbine	Vertical Axis Turbine
Deepwater Energy BV	Netherlands	Oryon Watermill	Vertical Axis Turbine
EC-OG	UK	Subsea Power Hub	Vertical Axis Turbine
EEL Energy	France	EEL Energy	Oscillating Hydrofoil
Elemental Energy Technology Limited	Australia	SeaUrchin	Other
Flex Marine Power Ltd	UK	Swimmer Turbine	
Flumill	Norway	Flumill Power Tower	Archimedes Screw
Free Flow 69	UK	Osprey	Vertical Axis Turbine
Free Flow Power Corporation	USA	SmarTurbine	Horizontal Axis Turbine
GCK Technology	USA	Gorlov Turbine	Vertical Axis Turbine
Guinard Energies SAS	France	MagaWattBlue	
Hales Water Turbines Ltd	UK	Hales Turbine	Other
Hydra Tidal AS	Norway	Morild II	Horizontal Axis Turbine
Hydro Alternative Energy	USA	OCEANUS	
Hydro-Gen	France	Hydro-Gen	Horizontal Axis Turbine
HydroQuest	France	Hydroquest Tidal	Vertical Axis Turbine
Hydrovolts Inc	USA	C-12 Canal Turbine	Horizontal Axis Turbine
Hydrovolts Inc	USA	WF-10-15 Waterfall Turbine	Other
Hyundai Heavy Industries	Korea		
IHC Tidal Energy	Netherlands	OceanMill	Vertical Axis Turbine
InCurrent Turbines Ltd	Canada	Vortex Power Drive	
Instream Energy Systems	Canada	Vertical Axis Hydrokinetic Turbines (VAHT)	Vertical Axis Turbine
Integrated Power Technology Corporation	USA	TURBOFOIL	Oscillating Hydrofoil
Jupiter Hydro Inc	Canada		Archimedes Screw
Kawasaki Heavy Industries, Ltd	Japan		Horizontal Axis Turbine
Kepler Energy	UK	Kepler Turbine	Other
Leading Edge	US		Oscillating Hydrofoil
Lucid Energy Technologies	USA	Gorlov Helical Turbine (GHT)	Vertical Axis Turbine
Lunar Energy	UK	Rotech Tidal Turbine (LTT)	Enclosed tips (Venturi)
Magallanes Renovables	Spain	Magallanes Project	Horizontal Axis Turbine
Mako Tidal Turbines	Australia	MAKO Tidal Turbines	Horizontal Axis Turbine
Marine Current Turbines	UK	SeaGen S	Horizontal Axis Turbine
Marine Current Turbines	UK	SeaGen U	Horizontal Axis Turbine
Marine Energy Corporation	USA	Current Catcher	Horizontal Axis Turbine
Minesto	Sweden	Deep Green	Tidal Kite
Modec	Japan	Savonius Keel & Wind Turbine Darrieus (SKWID)	Other
Natural Currents	USA	Red Hawk	Other
Nautricity Ltd	UK	CoRMaT	Horizontal Axis Turbine
New Energy Corporation	Canada	EnviroGen/EnviroCurrent	Vertical Axis Turbine
Norwegian Ocean Power	Norway	H300	Vertical Axis Turbine
Nova Innovation Ltd	UK	Nova M100	Horizontal Axis Turbine
Ocean Flow Energy	UK	Evopod	Horizontal Axis Turbine
Ocean Renewable Power Company (ORPC)	USA	RivGen Power System	Horizontal Axis Turbine
Ocean Renewable Power Company (ORPC)	USA	TidGen Power System	Horizontal Axis Turbine
Ocean Renewable Power Company (ORPC)	USA	OCGen	Horizontal Axis Turbine
Oceana Energy Company	USA	TIDES	Horizontal Axis Turbine
Offshore Islands Ltd	USA	Current Catcher	Horizontal Axis Turbine
Open Ocean Energy Ltd	Ireland	Tidal Junior Flyer	
OpenHydro	Ireland	Open-Centre Turbine	Enclosed tips (Venturi)
QED Naval	Scotland	Subhub	Other
REAC Energy GmbH	Germany	StreamCube	Vertical Axis Turbine
Renewable Devices Marine Ltd	UK	Capricon 5	Horizontal Axis Turbine
Renewable Devices Marine Ltd	UK	River Otter	
Renewable Devices Marine Ltd	UK	Capricon 125	Horizontal Axis Turbine
Renewable Devices Marine Ltd	UK	Sea Otter	
Repetitive Energy Company	UK	REPEN6	Vertical Axis Turbine
ResHydro	USA	Hydrofoil Cascade Resonator (HCR)	Oscillating Hydrofoil
SABELLA SAS	France	D03	Horizontal Axis Turbine
SCHOTTEL group	Germany	STG (SCHOTTEL Tidal Generator)	Horizontal Axis Turbine
Scotrenewables	UK	SR2000	Horizontal Axis Turbine
SeaCurrent	The Netherlands	SeaCurrent TidalKite™	Tidal Kite
SeaPower Gen	UK	SPG	
Seapower scrl	Italy	GEM	Tidal Kite
SMD Hydrovision	UK	TiDEL	Horizontal Axis Turbine
Straum AS	Norway	Hydra Tidal	Horizontal Axis Turbine
Suanders Energy Ltd	UK	Power-Frame	Horizontal Axis Turbine
Sustainable Marine Energy (SME)	UK	PLAT-O	Horizontal Axis Turbine
Tidal Energy Ltd	UK	DeltaStream	Horizontal Axis Turbine
Tidal Energy Pty Ltd	Australia	Davidson Hill Venturi (DHV) Turbine	Enclosed tips (Venturi)
Tidal Sails AS	Norway	Tack Reach	Other
TidalStream Limited	UK	Triton 6 (Tidal Turbine Platform System)	Horizontal Axis Turbine
TidalStream Limited	UK	Triton 3 (Tidal Turbine Platform System)	Horizontal Axis Turbine
Tidalys	France	ELECTRImar 4200	Horizontal Axis Turbine
Tidalys	France	ELECTRImar 1800	Horizontal Axis Turbine
Tocardo Tidal Turbines	Netherlands	T2	Horizontal Axis Turbine
Verdant Power	USA	Free Flow Kinetic Hydropower System (KHPS)	Horizontal Axis Turbine
Vortex Hydro Energy	USA	VIVACE (Vortex Induced Vibrations Aquatic Clean Energy)	Other
Vortex Power Drive	USA	Vortex Power Drive	
Water Wall Turbine Inc	Canada	Water Wall Turbine - In-Flow Water Current Technology	Horizontal Axis Turbine

Marine Current Turbines (MCT) SeaGen team 
Atlantis AR1500 team
** PhD Thesis
abuan, sine wave, Uni. of shieffield

*** 2016 Olczak, Alexander. The influence of waves on tidal stream turbine arrays. Diss. University of Manchester, 2016.

*** 2013 Milne An Experimental Investigation of Turbulence and Unsteady Loading on Tidal Turbines 
lab study, turbulence, unsteady loading

*** 2014 Numerical investigation of Marine Hydrokinetic Turbines: methodology development for single turbine and small array simulation, and application to flume and full-scale reference models.

***   Mcnaughton, Jame Uni. of Manchester 2013 Turbulence modelling in the near-field of an axial flow tidal turbine in code saturne
  Mcnaughton, Jame Uni. of Manchester
 ~\cite{mcnaughton2013turbulence}

*** xin bai 2014 Numerical Simulation of a Marine Current Turbine in Turbulent Flow 
Conclusion:
further research: 



	3. Methods
		a. Free surface scheme
			i. Level set method
			ii. Height function method
		b. FSI
			i. Immersed Boundary Method

** Turbulence Parameters                           :Turbulence_intensity:TI:
- intensity and length scale
**** Turbulence Intensity: TI

*In Numerical Modelling:*
- 1-3% [fn:Luis2009]
- 1.75 % [fn:Ebdon]
- 1%, 10% and 20% (James Mcnaughton, 2013)
- 2.233% (Jacob Dissertation) 

*in water flume*
Normally lower than field data
- 3% [fn:Lust2018] (Naval Academy, USA)
- 3% and 15%  [fn:Mycek2014b] (IFREMER flume tank, France)


*In Field Data*:
in-site TI is higer than 3%  [fn:Mycek2014a]
10% - 25.5% [fn:Novo2017]
file:figures/TI_novo2017_Goto_Islands_japan.png
Turbulent Intensity around a Tidal Turbine Support Structure (Walker, S, 2017, energies, Experimental Studies of Turbulent Intensity around a Tidal Turbine Support Structure)
#+CAPTION: Table 1 On site measurements of turbulence intensity   [fn:Mycek2014a] 
#+NAME: Table:one_site_TI
| Location            | TI^1D (%) | TI_\infty (%) | U_\infty (m/s) | water depth (m) | Techniques | Ref                                                   |
|---------------------+-----------+---------------+----------------+-----------------+------------+-------------------------------------------------------|
| Fall of Warness     |     10-11 |       7.9-8.7 |            1.5 |             5.0 | ADCP       | \cite{osalusi2009reynolds} [fn:osalusi2009]           |
| Sound of Islay      |     12-13 |      9.5-10.3 |            2.0 |             5.0 | ADV        | \cite{milne2013characteristics} [fn:milne2013]        |
| Puget Sound         |  8.4/11.4 |       6.6/9.0 |  1.3 (\pm 0.5) |             4.7 | ADV/ADCP   | \cite{thomson2012measurements} [fn:Thomson2012]       |
| Strangford          |       4-9 |       3.2-7.1 |        1.5-3.5 |              14 | --         | \cite{macenri2013influence} [fn:macenri2013influence] |
| East River, NY      |     20-30 |         16-24 |        1.5-2.3 |            5.22 | ADCP       | \cite{li2010inflow}[fn:li2010inflow]                  |
| Goto Islands, Japan |   10-25.5 |          8-23 | 0.25-2         |              18 | ADCP       | \cite{novo2017field} [fn:Novo2017]                    |

[fn:Lust2018] 2018 lust Survey of the near wake of an axial-flow hydrokinetic turbine in quiescent conditions
[fn:Mycek2014a] Mycek, Paul, et al. "Experimental study of the turbulence intensity effects on marine current turbines behaviour. Part I: One single turbine." Renewable Energy 66 (2014): 729-746.
[fn:Mycek2014b] Mycek, Paul, et al. "Experimental study of the turbulence intensity effects on marine current turbines behaviour. Part II: Two interacting turbines." Renewable Energy 68 (2014): 876-892.
[fn:li2010inflow] Li, Ye, et al. "Inflow measurement in a tidal strait for deploying tidal current turbines: lessons, opportunities and challenges." ASME 2010 29th international conference on ocean, offshore and arctic engineering. American Society of Mechanical Engineers, 2010.
[fn:macenri2013influence] MacEnri, Joseph, Matthew Reed, and Torbjörn Thiringer. "Influence of tidal parameters on SeaGen flicker performance." Phil. Trans. R. Soc. A 371.1985 (2013): 20120247.
[fn:Thomson2012] Thomson, Jim, et al. "Measurements of turbulence at two tidal energy sites in Puget Sound, WA." IEEE Journal of Oceanic Engineering 37.3 (2012): 363-374.
[fn:milne2013] Milne, Ian A., et al. "Characteristics of the turbulence in the flow at a tidal stream power site." Phil. Trans. R. Soc. A 371.1985 (2013): 20120196.
[fn:osalusi2009] Osalusi, Emmanuel, Jonathan Side, and Robert Harris. "Reynolds stress and turbulence estimates in bottom boundary layer of Fall of Warness." International Communications in Heat and Mass Transfer 36.5 (2009): 412-421.
***** effect of TI on Cp ,Ct
- 4% difference (1%, 10% and 20% James,Mcnaughton,2013)

- TI has slight effect on mean Cp and large impact on wake [fn:Mycek2014a] 
   + For higher TI, Cp (TI=15%) is slightly lower than Cp (TI=3%)
***** TI on wake
higher TI, wake axial velocity recovers faster



**** Turbulence Length scale:\ell
How to measure \ell?
you CAN'T  measure \ell in the water flume, you can only guess the value

- 5% of tunnel diameter (emperical )[fn:Luis2009]
*water flume*
- 0.5m and 1m  (turbine D=0.5m) [fn:Ebdon]

*Numerical*
- 1/3 channel depth (numerical DES) [fn:blackmore2011]

- \ell = 0.07 D_H =0.07 (4A/P_w) (Jacob Dissertation)
where D_H is the [[https://www.engineeringtoolbox.com/hydraulic-equivalent-diameter-d_458.html][hydraulic diameter]], A is the area section of the duct , and  P_w is the wetted perimeter of the channel
( based on Hydraulic diameter of pipes and ducts )

***** validation of RANS model for \ell
RANS models is based on Boussinesq hypothesis which assumes isotropic turbulence, thus 
RANS  is suitable for small \ell,  and has deficit for \ell in the wake region. 

[fn:Ebdon] Ebdon, T., et al. "Modelling the Effect of Turbulence Length Scale on Tidal Turbine Wakes using Advanced Turbulence Models."
[fn:blackmore2011] Blackmore, T., et al. "The sensitivity of actuator-disc rans simulations to turbulence length scale assumptions." (2011).
[fn:Novo2017] Novo P Kyozuka Y 2017   Field measurement and numerical study of tidal current turbulence intensity in the Kobe Strait of the Goto Islands, Nagasaki Prefecture


**** Turbulence Parameter in Water Flume
0.5m in water flume, Turbine Diameter 0.5m [fn:Ebdon]
**** Reference
Blackmore, Thomas, W. M. J. Batten, and A. S. Bahaj. "Influence of turbulence on the wake of a marine current turbine simulator." Proc. R. Soc. A 470.2170 (2014): 20140331.
Luis Eca 2009 Report, Best Practice Guidelines for the application of Computational Fluid Dynamics in Marine Hydrodynamics

** Design/optimization
keywords: wind turbine,  design
wind turbine design handbooks (Manwell et al. 2002; Burton et al. 2001),

a rotor operating in unbounded flow>> actuator disc theory>> Lanchester-Betz limit, 16/27


winglets, 
>Yiru Ren, 2017, ocean enginnering, Design and hydrodynamic analysis of horizontal axis tidal stream turbines with winglets
- The triangle tip turbine performs 4.34% increment in power coefficient and 3.97% increment in thrust coefficient at the optimal TSR.

** Numerical Modelling  setup detail
refer to CD-mesh_size_literature-review.excel

| <20>                 | <10>       | <25>                      | <20>                 | <20>                 | <30>                           | <20>                 |
| authors              | Blade Profile | Turbulence Models         | Solver               | CD                   | Steady                         |                      |
|----------------------+------------+---------------------------+----------------------+----------------------+--------------------------------+----------------------|
| Xinbai 2014          | NACA63     | LES                       | CgLes                | 5D 3D 10D            | no                             |                      |
| Abuan 2017           |            | RANS, k-e, k-e RG         | Fluent               | 5D 5D 10D            |     yes and no                 |                      |

*** 	Reynolds number
[
Re=\rho uL/\mu
]

How to determine the characteristic velocity and length?

*characteristic length:*
Case 1:
turbine diameter ~\cite{mcnaughton2013turbulence}
$Re=\rho uD/\mu$
	
	D is diameter of turbine, for e387, $D=0.46m$
case 2: 
	
blade chord length at the middle span ~\cite{chamorro2013interaction}
for e387, $c=(50+25)/2=37.5mm$, then $Re_c=\rho uc/\mu=10^3*0.6*0.00375/1.002^(-3)=2.25e4$


*** CD 
- upstream, 3D
- downstream, > 7D in most paper
(6D has reverse flow in E387 turbine case)


*** MFR vs Sliding Mesh
- Steady MRF
- Unsteady MRF
  + the mean velocity,U is assumed as steady, dU/dt =0
- Sliding mesh, unsteady 

Although Transient solution with sliding mesh method offers a simulation closer to
the real condition of turbine operation with accurate results, *steady* state *MRF* provides
reasonable results while saving a significant computational time.

**** Examples of  SRF VS MRF VS Sliding mesh
	Chapter 9: Modeling Flows with Moving Reference Frames ,Fluent user guide 

a. Single moving reference frame, 
		
			i. cfd study of a wind turbine rotor, federico malatesta queen mary
			ii. CFD-RANS Study of Horizontal Axis Wind Turbines
			Thesis for the degree of Doctor of Philosophy,Carlo Enrico Carcangiu
			Gambit fluent, moving reference frame
			iii. 
			iv. https://confluence.cornell.edu/display/SIMULATION/Wind+Turbine+Blade+FSI+(Part+1)+-+Geometry
b. Sliding mesh, unsteady, more accurate
			i.  james,chapter5,comparing chimera methods and sliding method
			
c. MRF,
			i. Simulations of Flow Over Wind Turbines,Dnyanesh A. Digraskar,University of Massachusetts
		
			
> M. Rahimian, J. Walker, and I. Penesis, “Numerical assessment of
a horizontal axis marine current turbine performance,” International
Journal of Marine Energy, vol. 20, pp. 151–164, 2017.
*** Turbulence Parameters for e387 turbine
U=0.6m/s,
Turbulent length scale:
1.  based on BL thickness (user guide, fluent)
  + in a turbulent BL, \ell is the order of \delta_99, \ell~\delta_99
\ell = 0.4 \delta_{99} =0.4 * 0.35mm=1.4e-4m
where BL thickness is based on post -processing of RANS

2. based on channel depth  [fn:blackmore2011]
\ell= 1/3 channel depth = 1/3*1.6=0.53m

3. Based on *Turbulent viscosity ratio*,  (user guide, fluent)
for external flow, 1< \mu_t/\mu <10
if I=1%, and  \mu_t /\mu =5, then \ell = 1.25e-2m
known: U, I, \mu_t
To get TKE, k:
(U, I) >> k
    k=3/2(UI)^2
To get \ell: 
(\mu_t , k) >> \ell
\ell= \mu_t /(\rho C_\mu^{1/4} k^{1/2})

4. based on Hydrodynamic Diameter
- \ell = 0.07 D_H =0.07 (4A/P_w) =2.743*0.07 =0.192 (Jacob Dissertation)

*** Running time and resources
**** RANS
15 M mesh, steady, k-omega SST, RANS,  3000 iteration, 3h
15 M tetra+prism, unsteady, RANS, 10h, 64 cores, 1000 time steps, 20 iteration per time step
**** LES
1 week per turbine rotation, 4096 cores for 17 Million full scale turbine LES [fn:Ahmed2015] with CD of 4.9D*9.8D*2.35D
*** Time step and total number of time steps
Usually propeller flow problems, especially if cavitation is involved, need an unsteady
approach based on a time stepping procedure. 

For a RANS
-  the wake harmonics determine more or less the time step length. Due to the connection to the wake
field it is reasonable to express the time step first in terms of an angular interval. Here a
distance d \phi = 1-2 degree
is recommended. 
The time step size \(dt \):

dt = d \phi / 360/n
-  n : shaft frequency [1/s]

Rule of thumb: 1 degree of rotation  per time step

For LES, that resolve
the turbulent flow on a macroscopic scale, time steps are typically smaller by a factor of 100.
For propellers the maximum number of time steps may be counted in terms of revolutions that
are simulated after starting from the initial conditions. For a periodic propeller flow problem it
is emphasised to include about 4 revolutions. The history of the one-blade thrust may serve
as an indicator for the periodicity of the flow

*** Turbulence model for Low Reynolds number flows
keywords: turbulence model, Low Reynods number flows,  turbine 

 a good  review  see table 2.1 james
k -\omega SST is the most widely  used model

- k-\epsilon
- k- omega
- LES
k-ɛ RNG and k-ω SST [fn:abuan2017](abuan, 2017)
capture LSB of naca4415 airfoil at Re=120,000  [fn:aftab2016] 
[fn:aftab2016] Aftab, S. M. A., et al. "Turbulence model selection for low reynolds number flows." PloS one 11.4 (2016): e0153755.
**** References
Patel, Virendra C., Wolfgang Rodi, and Georg Scheuerer. "Turbulence models for near-wall and low Reynolds number flows-a review." AIAA journal 23.9 (1985): 1308-1319.

*** RANS study of Tidal turbine
- james, 2013, 

*** LES study of tidal turbine

Kang et al. (2012) were the first to reproduce numerically the operation of a commercial HATT prototype using the immersed boundary method. McNaughton et al. (2014) and Bai et al. (2014) performed LES of the experimental setup from Bahaj et al. (2007), and whilst (McNaughton et al., 2014) used a sliding mesh method, Bai et al. (2014) employed the immersed boundary method. In all three studies an excellent match with the experimental data was achieved showing the potential and accuracy of the method of LES.
https://www.sciencedirect.com/science/article/pii/S0889974616305679#fig2

*** steady case

*** Unsteady case


** Reference with detailed blade profile 
pitch angle, chord length
NACA 63418 profile >> Mycek,2014, Experimental study of the turbulence intensity effects on marine
current turbines behaviour. Part I: One single turbine

Satran L and Bartl J 2015 Invitation to the 2015 \Blind test 4" Workshop Combined power output of two
in-line turbines at different inflow conditions

** Parametric study
- structural loading
- blade performance
- wake structures
- [[Intra-array interactions]] 
- [[FSI]]

| <20>                 | <20>                 | <30>                           |
| independent variable | dependent variable   | Ref                            |
|--------------------------+------------------------------+----------------------|
| [[water depth]]          | wake recovery        |                                |
| [[tip clearance]]        | Cp, Ct               |                                |
| inflow turbulence    |                      | lust, 2017,                    |
|      Froude Number   |                      |      Jacob                     |
| [[axial flow misaligment]]| Cp| Carwyn H.Frost, 2017, renewable energy|

*** Effect of blockage
\end{enumerate}
BEMT: blockage-free state

Experiments and CFD: have blockage effect (flume walls for experiment, domain boundaries for CFD) that forces more fluid through the turbine than in an equivalent unblocked condition.

blade-resolved moving reference frame and coastal models based on the shallow water equations. 


*** Froude number effect on Cp
- Froude number :: the ratio of inertia force and Hydrostatic force
Fr= v/sqrt(gy)

the wave speed as seen by the fixed observer is defined as :
[
v_w = v \pm sqrt(gy)
]


When Froude number is close to 1, Cp dropped 1/3 (Jacob)
Froude number on power performance is studied, which VOF is used to capture free interface and geometry detail is resolved ~\cite{riglin2015characterization}.  

0.082 ≤ Fr ≤ 0.131. Turbine performance, kinetic and hydrodynamic efficiencies were only marginally influenced by
Froude number, while free-surface elevation change was found to be strongly dependent on
Froude number.[fn:consul2013]

*** wake recovery rate 
larger length scale reduces the rate of wake recovery. [fn:Ebdon]
*** Intra-array interactions 


wakes are important when tidal turbines are  in arrays~\cite{malki2014planning}
file:figures/post/velocity_TI_array_malki_2014.png
Cp increased 10%
Methods: (BEM-CFD) model

Stallard, T., et al. "Interactions between tidal turbine wakes: experimental study of a group of three-bladed rotors." Phil. Trans. R. Soc. A 371.1985 (2013): 20120159.

*** FSI
** Workshops
6th Oxford Tidal Energy Workshop (OTE2018) 
proceeding, OTE2018_proceedings_v3b.pdf, http://www.eng.ox.ac.uk/tidal/templates/OTE2018_proceedings_v3b.pdf

** Unsteady Loading
An Experimental Investigation of Turbulence and Unsteady Loading on Tidal Turbines

** Blockage and aspect ratio


*what is acceptable blockage ratio that don't need blockage correction of Cp?*

- the blockage correction is less than 5% for blockage ratio less than 10%[fn:chen2011]
- Solid blockage 0.03  [fn:Schluntz2015])
- Solid blockage in wind tunnel in the range of 0.01- 0.10 with 0.05 being typical[fn:barlow1999]

*** FAQ

**** Is Blockage effect considered  in design stage?
- no, Blockage is not included in blade design stage [fn:Schluntz2015])

*** Blackage effects on Cp
In blocked conditions, the Cp of a rotor may be higher than Betz limit[fn:Garret2007].

*** Blockage correction Methods
- appendix, Bahaj, 2007

*** Concepts

- blockage ratio :: the ratio of rotor swept area to cross section area of  channel
\[
\epsilon = A_t/A
\]

where A_t is the turbine swept area, and A is the channel cross-sectional area
When \( \epsilon < 0.05 \), the flow is regarded as unconfined ([fn:Whelan2009] 

- Solid Blockage :: ( "frontal area" of an  object ) / (the cross-sectional area)


- Apect Ratio (AR) (aeronautics) :: the ratio of its span to its mean chord

- wake blockage :: \(\epsilon_{\omega b}\) , 
- In a close test section, the wake blockage increases the measured *drag*.
- In a open test section, wake blockage is negligible cause the airstream is free to expand.


- Solidity :: \sigma = Nc/R
where N is the number of blades and c is the blade chordlength
x



*** References

Jacob2016 ASME  "Numerical Analysis of Blockage Ratio Effect on a Portable Hydrokinetic Turbine." ASME 2016 International Mechanical Engineering Congress and Exposition. American Society of Mechanical Engineers, 2016.
> Garrett 2007  The efficiency of a turbine in a tidal channel. J Fluid Mech 2007;588:243e51.
> J. Schluntz, 2015, Ren. energy, The effect of blockage on tidal turbine rotor design and performance
> Whelan, J 2009  "A free-surface and blockage correction for tidal turbines." Journal of Fluid Mechanics 624 (2009): 281-291.

>Rotors designed to operate in high local blockage require greater solidity 
and lower blade twist than rotors designed for operation in unblocked flow.(Schluntz, 2015)



>Chen, T. Y., and L. R. Liou. "Blockage corrections in wind tunnel tests of small horizontal-axis wind turbines." Experimental Thermal and Fluid Science 35.3 (2011): 565-569.

Maskell, 1963, 
> Maskell,  1963 E. C. A theory of the blockage effects on bluff bodies and stalled wings in a closed wind tunnel. No. ARC-R/M-3400. AERONAUTICAL RESEARCH COUNCIL LONDON (UNITED KINGDOM), 1963.
> 5.5 Data Acquisition and Corrections, xiang shen, thesis

> ~nasa_wind_tunnel_Blockage_Recommendations.pdf~


> Barlow, Jewel B., W. H. Rae, and Alan Pope. "Low-speed wind tunnel testing, 1999." Jhon Wiley&Sons, Canada

*** Kinsey, 2017, Renew energy, Impact of channel blockage on the performance of axial and cross-flow hydrokinetic turbines
3D URANS blockage effect on horozontal axial-flow and vertical axis flow turbines
- Cp, Ct increase linearly with blockage
- The difference between lateral and vertical confinements plays a secondary role with little effect unless the confinement
asymmetry (CA) becomes greater than approximately 3
- If the turbine is operated at a small tip-speed ratio relative to the
optimal point, dynamic stall is likely to appear due to the increased
angle-of-attack. In such a case, the performance of the turbine
(especially the power coefficient) becomes almost insensitive to the
blockage ratio.

** axial flow misaligment
field velocity data shows that majority of the currents fall within \pm 20 of principal flow direction
CFD results shows that Cp reduces as misalignment angle increase
- magnitude of the bending moments acting on the rotor end of the driveshaft for the misaligned turbines was found to be up to ten times greater than the aligned turbine




**  Full scale tidal turbine
Gabriel Scarlett (University of Edinburgh), ‘Unsteady hydrodynamics of full-scale tidal turbine blades’. 
In the proceedings of the 6th Oxford Tidal Energy Workshop (OTE2018), Oxford, United Kingdom, 26/03/18 - 27/03/18 

Experimental study of hydrodynamic performance of full-scale horizontal axis tidal current turbine  ~\cite{jing2017experimental}
Kang S, 2012, advances in water resources, Numerical simulation of 3D flow past a real-life marine hydrokinetic turbine
Umair Ahmed, 2015,  CFD Simulations of a Full -Scale Tidal Turbine:  Comparison of LES and RANS with Field Data 

** Free surface effect
file:ch6.org
2 phase has 5% of that of one phase (Jacob)

** <<water depth>> 
Payam,Aghsaee 2018, Renewable energy
Effects of flow depth variations on the wake recovery behind a
horizontal-axis hydrokinetic in-stream turbine

The /far wake velocity deficit/ did not exhibit the /symmetric Gaussian profile/ often found downstream of wind turbines.

a deeper flow, the *mean velocity* recovers more rapidly and the *turbulence intensity*  recovers more slowly.
(flow depth)/(turbine diameter),H/D,is an important parameter related to the wake recovery rate.

** <<tip clearance>> impact on performance
effect of tip clearance on torque, file:figures/tip_clearance_noruzi_2015.jpeg  [fn:noruzi2015design],
effect o tip clearance on wake recovery
> Zhang, Yuquan, et al 2017 Energies  "Experimental Analysis and Evaluation of the Numerical Prediction of Wake Characteristics of Tidal Stream Turbine." 

The effect of rotor depth, yaw and dual rotor interference (e.g. Bahaj et al. 2007); 
wake characterization and the influence of the ambient turbulence intensity on the device performance (e.g. Maganga et al. 2010);

flow velocity increase by using annular-ring-type augmentation channels (Radkey \& Hibbs 1981); 

cavitation (e.g. Molland et al. 2004), evolution of tip and hub vortices (Felli, Camussi \& Di Felice 2011) and theoretical derivations (Garrett \& Cummins 2007).[1]

The impact of blade roughness and biofouling on the performance of a two-bladed horizontal axis marine current turbine was investigated experimentally and numerically [2].

** Pitch and Stall Regulated Tidal Stream 
Performance of pitch and stall regulated tidal stream turbines
     Whitby B Ugalde-Loo C  IEEE Transactions on Sustainable Energy 2014 
MATLAB GH Tidal Blade

** Blade effect on seabed scour 
*** Experimental study on scour profile of pile-supported horizontal axis tidal current turbine :scour&turbine: :tip clearance:
Long Chen a, b, , Roslan Hashim b, Faridah Othman b, Shervin Motamedi
**** Purpose of study
**** Conclusion
shorter distance, more scour depth
most scour reach a equilibrum after 35 hours
**** Methods
flume experiment
quantities of interest:
- input quantities: tip clearance
- output quantities: max scour depth, stream wise scour distance, scour vs time

** Cavitation
file:cavitatio
n.org
Definition:
- Cavitation :: 

Quantities to descibe cavitation:


Chernin. et al proposed a  probabilistic method to predict the cavitation of a tidal stream turbine\cite{chernin2017probabilistic}. A case study illustrating the application of the new probabilistic approach as well as an existing deterministic approach is presented. It is shown that the existing deterministic approach does not provide sufficient data for rational and economically efficient design of tidal stream turbines for cavitation.



Shi, Weichao, et al. "Cavitation observations and noise measurements of horizontal axis tidal turbines with biomimetic blade leading-edge designs." Ocean Engineering 121 (2016): 143-155.

** NACA63_812
Experiment work, ~\cite{bahaj2007power}.
CgLes
 Bahaj, refer to, ~\cite{xin2014numerical}.
Code Saturne 
LES, RANS model, open source CFD solver, Code_Saturne, Structured mesh ~\cite{afgan2013turbulent}.

** support structure

*** self balancing kinetic turbine
Zupone, Giacomo Lo, et al. 2017, applied energy, Lcoe evaluation for a tidal kinetic self balancing turbine: Case study and comparison

Zupone, Giacomo Lo, et al.  "Levelized Cost of Energy: a first evaluation for a self balancing kinetic turbine." Energy Procedia 75 (2015): 283-293.

** inflow condition
*** A large-eddy simulation study of horizontal axis tidal turbine in different inflow conditions :LES: :inflow-condition:
OpenFOAM
LES
actuator line method
* Conferences
Asian Wave and Tidal Energy Conference 

International Conference on Ocean, Offshore and Arctic Engineering

* Authors and Institutes
** Academic
| author                 | Institutes                    | Research Interests                        | Methods  | Country |
| [[http://paul-mycek.com/index.html][Paul Mycek]]             |                               | effect of TI on Cp                        |          | France  |
| xiaoxiao guo           | shanghai jiao tong Uni.       | wave frequency effect on floating turbine |          | China   |
| anna yang              | Cambridge Uni.                | tip clearance                             |          | UK      |
| Richard Willden        | Oxford Uni.                   |                                           |          | UK      |
| Feng-mei Jing (荆丰梅) | Harbin Engineering University | Experimental                              |          | China   |
| bing huang             | Zhejiang Uni.                 | Dual Rotor pitch in one direction         | Exp, Num | China   |



   










** Industry
[[https://energy.sandia.gov/energy/renewable-energy/water-power/technology-development/wec-sim-wave-energy-converter-simulator/][Sandia]] USA
https://energy.sandia.gov/energy/renewable-energy/water-power/technology-development/tidal-current-modeling-development-and-validation-2/

Marine Current Turbines Limited's, 

European Marine Energy Centre (EMEC

OpenHydro, atlantis,

Scotrenewable


Atlantis turbine: Solon,

Global Ocean Energy Symposium

From <http://www.atlantiscorp.co.za/marine_projects.htm> 

Alstom

From <http://www.alstom.com/products-services/product-catalogue/power-generation/renewable-energy/ocean-energy/tidal-energy/tidal-power/> 

http://www.fp7-cores.eu/


* Journals on MCT 
- Applied Energy ( SJR 3.16, 2018)
- Renewable and Sustainable Energy Reviews
- renewable energy (SJR, 1.847)
- energy (SJR 1.99)
- ocean engineering
- renewable & sustainable energy review (5-Year Impact Factor: 10.093)
- Journal of Wind Engineering and Industrial Aerodynamics (SRJ 1.264)
- Wind Energy ( SJR 1.051)
- International Journal of Marine Energy
https://www.scimagojr.com/journalrank.php?area=2100&order=sjr&ord=desc

* Numerical methods
** numerical modelling of current turbine
*** TOC
version 1
a broad classification can be set ditinguishing global performance methods
and flow-field models.
- BEM Model
-inviscid-flow models
 + lifting line
   + >> Falcão de Campos, J.A.C., 2007. Hydrodynamic power optimization of a horizontal axis marine current turbine with lifting line theory, In: Proceedings, 17th International Offshore and Polar Engineering Conference, vol. 1, pp. 307–313.
 + lifting surface
 + Vortex Lattice
 + Boundary integral equatons methods

 + viscous flow models ([[https://doi.org/10.1016/j.oceaneng.2015.05.036][A.H.Day, 2015 ocean engineering]])

version 2
- BEM
- BEM-CFD
- CFD
- Coastal area modelling (masters 2015 energies)





*** References
([[https://doi.org/10.1016/j.oceaneng.2015.05.036][A.H.Day, 2015 ocean engineering]])

Masters I et al. 2015, energies, A Comparison of Numerical Modelling Techniques for Tidal Stream Turbine Analysis[J]. Energies, 2015, 8(8): 7833-7853.

*** BEM
([[https://doi.org/10.1016/j.oceaneng.2015.05.036][A.H.Day, 2015 ocean engineering]])
- Batten, 2008, The prediction of the hydrodynamic performance of marine current turbines
- AeroDyn Theory Manual

- I Masters , 2011 A robust blade element momentum theory model for tidal stream turbines including tip and hub loss corrections
- Monte Carlo and sequential quadratic optimisation

*** BEM-CFD

the BEM method is used to model the turbine, and CFD is employed to model the flow properties elsewhere in the domain 
\cite{williams2010combined} [fn:williams2010]
,\cite{malki2014planning}

Advantage:
 a time-averaged estimate of the turbine wake 
 
 Significantly reducing the computational cost compared to a geometry-resolved CFD model
\cite{masters2015comparison} \cite{malki2013coupled}.

>>  Malki, R.; Williams, A.J.; Croft, T.N.; Togneri, M.; Masters, I. A coupled blade element momentum-computational fluid dynamics model for evaluating tidal stream turbine performance.
Appl. Math. Model. 2013, 37, 3006–3020.
[fn:williams2010] Williams, A.J. et al  A combined BEM-CFD model for tidal stream turbine. In Proceedings of the 3rd International Conference on Ocean Energy, Bilbao, Spain, 6–8 October 2010.

**** examples
The coupled BEM–CFD achieves good predictions of turbine performance when compared against measured flume data
from [8]. 
This comparison was presented in [18], and it was shown that despite the relative simplicity of the model com- pared to classical CFD modelling, good power output predictions were estimated by the model with errors in CP values rang- ing between ?1.07% and 7.95% between tip speed ratios of 4.0–8.0. 
\cite{Masters2013The}


*** CFD

*advantages*
viscous flow mdoels based on the numerical solution of the N-S equations provide
a more physically-consistent and comprehensive approach to accurately describe a full range of system
layouts and operating condtions
([[https://doi.org/10.1016/j.oceaneng.2015.05.036][A.H.Day, 2015 ocean engineering]])

*RANS VS DES/LES*
- RANS allows estimation of the effects of flow vorticity and turbulence on hdrodynamic loads, Turbulence
modeling is introduced to aovid the explict solution of eddies in the flow.

- DES/LES allows more detailed descriptions of local flow perturbations and of blade/foil generated wakes
  + ? flow perturbuation


**** Meshing}
Meshing Softwares:
ICM-CFD, ansys meshing, Pointwise, etc.
\subsection{multi-block structured mesh}
see~\cite{afgan2013turbulent}, only surface mesh provided, and the details are not available.
\subsection{Unstructured mesh}
\subsection{Hybrid}

\section{Scheme validation}
\begin{enumerate}
	\item challenges
\end{enumerate}
The principal difficulty in validating these schemes is the lack of field data. 
Several sets of results
are in the literature based on experiments with relatively small diameter rotors. 
Calculation of the Reynolds number based on the blade chord length shows that Reynolds numbers are significantly
lower than those found in typical datasets for aerofoils in air [1].

\section{NACA 63\_812}
research based on lab experiment of Bahaj.
\subsection{Geo}
refer to ~\cite{bahaj2007power}.
software, Solidworks
\subsection{Lab experiment}
Lab experiment, refer to  Bahaj et al~\cite{bahaj2007power}
\subsection{Numerical Modelling}
Numerical simulation, based on lab model of Bahaj, refer to ~\cite{afgan2013turbulent},~\cite{bai2014numerical}, ~\cite{xin2014numerical}.
In reference ~\cite{afgan2013turbulent}:

LES, RANS model, open source CFD solver Code\_Saturne, no wave motion at free surface, Structured mesh.
\subsubsection{LES VS RANS results}
LES get detailed behavior for blade tip vortices and their
interaction with the supporting tower, neither of which are captured completely by the RANS models ~\cite{afgan2013turbulent}.
\chapter{wave effect on MCT}
	\section{authors and organizations}
 turbine at open channel condition
	
	wave effect on turbine

*** Unsteady Hydrodynamic Model
the author combined methodologies developed for helicopter wake modelling with techniques used in naval architecture for modelling thick
maritime propellers into a computational tool~\cite{mccombes2014unsteady}.


***  BEM VS Coastal area model

To evaluate the BEMT, a comparison is made to experiments with three different rotors. We demonstrate that, apart from the near-field wake, there are similarities in the results between the BEM-CFD approach and a coastal area model using a simplified turbine fence at a headland case~\cite{masters2015comparison}

\begin{enumerate}
	
*** literature review

A Virtual Blade Model is coupled with a CFD model to simulate impacts from a Horizontal Axis Tidal Turbine under combined surface waves and a steady current.~\cite{sufian20173d} However, the virtual blade model doesn't solve the blade detail.

Assessing the importance of including waves in simulations of tidal stream turbine impacts~\cite{fairley2016assessing}

Surface waves can be driven by wind and are particularly enhanced by the wind if their phase speed is comparable with the wind speed. Objects such as vessels can also cause waves and swells can also occur. Although the theory beyond gravity waves is well known ~\cite{whitham1974linear}, not much attention has been given for their effects on MCT until recently. 
	\subsection{single turbine}
Wave-Tide Interactions in Ocean Renewable Energy~\cite{hashemi2017wave}
	

Tatum, Sarah, et al. investigate the effect of waves and a velocity profile on the performance of a tidal stream turbine (TST).\cite{tatum2016cfd} A full scale model was subjected to waves both in and out of phase with its period of rotation.it was found that the longer period and in-phase wave had a significant effect on the power range fluctuations, with more modest variations for thrust and the average values.The addition of the profile had a strong effect on the bending moment.
	
	A lab experiment was conducted to study the influence of turbulent inflow condition on Cp for a axial flow hydro-kinetic turbine. spectra analysis shows that the effect of turbulent inflow on Cp is valid in the low frequencies ~\cite{chamorro2013interaction}.
		
	In reference~\cite{riglin2015characterization}, similar method is used to study free surface as what I am doing (commercial software, multiphase model,  VOF is used to capture free surface),  open channel flow is studied, while  stokes wave is used in my model. 	The effect of \textbf{free surface }and \textbf{Froude number} on \textbf{power performance} is studied by ~\cite{riglin2015characterization}.  Results show that  Froude number will also play a critical role in the development of the transient free surface level. A sharp decrease in performance was observed at the critical Froude number, while Results at subcritical conditions showed acceptable agreement with previously published single phase results. 
	
	The following references are from the comference paper ~\cite{ai2016surface}
	
	Barltrop et al . ~\cite{barltrop2007investigation} used linear wave theory, the Blade Element Momentum (BEM) approach and towing tank to investigate the effect of free surface waves on a model turbine of a three-blades horizontal axis MCT (HAMCT). 
	A similar approach was used by Galloway et al.~\cite{galloway2014quantifying}. Both concluded that the time-averaged power coefficient is not much affected by the free surface waves, but high unsteadiness can occur in the blade loading that may affect its long-term structural integrity. More dependence was found on the wave's frequency than the wave's amplitude and form.
	
	Lunzik et al. ~\cite{luznik2013effect} also used towing tank experiments to investigate the effect of small amplitude free surface waves on a small scale three-blades HAMCT. They concentrated on an “intermediate” wave length of about $h/\lambda=0.34$, where $h$  is the undisturbed water's depth and $\lambda$ is the wave length. They also found a small effect on the time-averaged power coefficient $C_p$ of the turbine, but time fluctuations were found, matching the passing of the wave's crest and trough over the turbine.
	
	Lust et al.~\cite{lust2013influence} pursued towing tank experiments for a small scale two-blades HAMCT and used computations based on the BEM model. They concentrated on linear surface waves over deep water with waves of amplitude of up to 0.2 m. They actually found a mild improvement in the time-averaged Cp of a high tip-speed-ratio (TSR) due to increase in the coefficient of thrust (drag) CT. Increase in Cp as the wave's crest passed over the MCT and decrease as the trough passed was also confirmed. Reasonable agreement was found with the BEM calculations.
	
	Bai et al.~\cite{bai2014numerical} used the Large Eddy Simulation (LES) approach, 
where the fluid flow was coupled with a three blades rotor using the immersed boundary method.
 Good agreement was found with experimental results, showing complex turbulent wake behind the rotor.
 Small effect was found for the free surface as no surface waves were imposed although the free surface was allowed to move. 
	

	\subsection{turbine array}
	The effect of \textbf{free surface deformation} on the \textbf{power }extracted by \textbf{a tidal turbine array partially spanning a wide channel} is investigated using a theoretical model~\cite{vogel2016effect}. Blockage ratio, power coefficient and thrust coefficient are analysed for Turbine-scale and array-scale models, and detailed as illustrated in Fig.1 in the paper.
		
	\subsection{wave properties}
	linear or nonlienar 
	wave height/frequency, water depth, wave height
	Parametric study
	\subsubsection{Turbine wave interaction}
	\subsubsection{inflow condition}
	turbulent inflow condition
	
	\textbf{Theory vs lab experiment}\\
	***********\\
	Comparison with test data shows a good agreement which implies that the theory can be effective in analysing the wave–current interactions in marine current turbines.\\
	*************\\
	The paper also carried out \textbf{parametric studies} into related parameters, which include \textbf{wave height, wave frequency, and tip-speed ratio}.\\
	\textbf{most important wave parameter}\\
	wave-heights,wave frequencies, and current speeds\\
	
\section{numerical methods}
\chapter{A7 acoustics}
\section{The Ffowcs-Williams and Hawkings Model}%The Ffowcs-Williams and Hawkings Model
theory part refer to Chapter 15: Aerodynamically Generated Noise, theory guide, fluent 
how to use FW-H model in Fluent, refer to fluent user guide



\chapter{wave effect on e387 using Fluent}
\section{experimental data}
•	Turbine diameter, 0.46m

•	Blade profile, E387

•	Pitch angle, 0 ° , Blade twist, 20°

•	Root chord, 0.05m, tip chord, 0.025m
•	Zo, depth of the turbine hub 0.782m
•	Water depth, 1.6m
•	Free steam velocity, U=0.6m/s
•	Wave period,T, 1.78s
•	Wave amplitude, a, 4cm 

methods
BEM, ansys-fluent
\subsection{e387-BEM}
refer to ~\cite{ai2016surface}

\subsection{e387-ANSYS}

	\paragraph{Geometry}
	Geometry is generated by Solidworks.
	blade section is from airfoil e387.
	To get a blunt trailing edge, e387 airfoil is modified.
	\paragraph{Fluent setup}
	Using VOF model to tackle free surface
	
	Moving reference frame to tackle turbine rotating
	
	Solver: pressure based solver
	vof model, only pressure base solver is available
	Time step: implicit
	pressure based solver, only implicit formulation is available
	
	Boundary conditions:
	
	1)	Distant inlet BCs for air inlet and water inlet, 
	Pressure inlet for air inlet, velocity inlet for water
	
	2)	Single inlet
	calculation process:
	The solution begins with an estimated pressure profile at the outlet boundary.
	
	\section{Numerical theory}
	
	\subsection{Turbine performance}
	It is challenge to Predict the power performance of marine turbine because of complex geometry, highly turbulent conditions, and the transient free surface ~\cite{riglin2015characterization}.
	Thrust force $F_T$
	\begin{equation}
	C_T=\frac{T}{\frac{1}{2}\rho A U_\infty ^2
	\end{equation}
	
	power coefficient
	
	case 1
	
	\begin{equation}
	P=\frac{C_p}{\frac{1}{2}\rho AU^3}
	\end{equation}
		
	where $P$ is power, $\rho$ is density,$A$ is the swept area of blade, and $u$ is the flow velocity passing through the rotor~\cite{chamorro2013interaction}.
	
	case 2\\
	moment=torque
	
	Betz limit, $C_p{max}=\frac{16}{27}$
	\begin{equation}
	C_Q=\frac{Q}{\frac{1}{2}\rho U^2 AR}
	\end{equation}
	Where, $Q$ is torque(moment) on the blades, $\rho$ is fluid density, $A$ is area, $R$ is radius of turbine.\\
	$C_p$ vs $C_Q$
	\begin{equation}
	C_Q=\frac{C_p}{\lambda}
	\end{equation}
	
	$C_Q$ is torque coefficient
	$C_p$ power coefficient
	$\lambda$ tip speed ratio
	
	
	\subsection{turbulence model}
	To numerically solve the question, unsteady RANS is used.
	To close RANS equations, two equation model is used.
	SST k-$\omega$ model is used.
	
	reason to use SST k-$\omega$ model:
	The shear-stress transport(SST) $K-\omega$ was developed by Menter to effectively blend the robust and accurate formulation of the $k-\omega$ model in the near-wall region with the freestream independence of the $k-\epsilon$ model in the far field. To achieve this, the $k-\epsilon$ is converted into a $k-omega$ formulation.
	
	$k-\omega$ vs SST $K-\omega$ model
	
	The SST $K-\omega$ model is similar to the standard $k-\omega$ model, but includes the following refinements:
	% from theory guide, fluent
	
	The standard  $K-\omega$ model and the transformed  $K-\epsilon$ model are both multiplied by a blending function and both models are added together. The blending function is designed to be one in the near-wall region, which activates the standard  $K-\omega$ model, and zero away from the surface, which activates the transformed $K-\epsilon$ model.
	
	The SST model incorporates a damped cross-diffusion derivative term in the $\omega$ equation.
	
	The definition of the turbulent viscosity is modified to account for the transport of the turbulent shear	stress.
	
	The modeling constants are different.
	
	\subsubsection{ transport equations} 
	Unsteady RANS
	\begin{equation}
	\frac{\partial \rho}{\partial t}+\frac{\partial}{\partial x_i}(\rho u_i)=0
	\end{equation}
	
	\begin{equation}
	\frac{\partial }{\partial t}(\rho u_i)+\frac{\partial}{\partial x_j}(\rho u_iu_j)=-\frac{\partial p}{\partial x_i}+\frac{\partial}{\partial x_j}[\mu(\frac{\partial u_i}{\partial x_j}+\frac{\partial u_j}{\partial x_i}-\frac{2}{3}\delta _{ij}\frac{\partial u_l}{\partial x_l})]+\frac{\partial}{\partial x_j}(-\rho \overline{u'_i u'_j})
	\end{equation}
	
	from:Theory guide, Fluent, 17.2
	
	\subsubsection{ Transport Equations for the SST k-$\omega$ model} 
	The turbulence kinetic energy,$k$, and the specific dissipation rate, $\omega$, are obtained from the following transport equations:
	\begin{equation}
	\frac{\partial}{\partial t}(\rho k)+\frac{\partial}{\partial x_i}(\rho ku_i)=\frac{\partial}{\partial x_j}(\Gamma_k\frac{\partial k}{\partial x_j})+G_k-Y_k+S_k
	\end{equation}
	and
	\begin{equation}
	\frac{\partial}{\partial t}(\rho \omega)+\frac{\partial}{\partial x_i}(\rho \omega u_i)=\frac{\partial}{\partial x_j}(\Gamma_\omega \frac{\partial \omega }{\partial x_j})+G_\omega-Y_\omega +D_\omega+S_\omega
	\end{equation}
	% copied from the theory guide, fluent
	In these equations,$G_k$ represents the generation of turbulence kinetic energy due to mean velocity
	gradients.$G_\omega$ represents the generation of $\omega$. $\Gamma _K$ and $\Gamma_\omega$ represent the effective diffusivity of $k$ and $\omega$ ,
	respectively. $Y_k$ and $Y_omega$ represent the dissipation of $k$ and $omega$ due to turbulence. $S_k$ and$S_\omega$ are user-defined source terms.
	
	
	Secondary Stokes wave
	
	dispersion relationship for the Secondary Stokes wave
	
	\begin{equation}
	\omega=Uk+\sqrt{gk\tanh{(kd)}}
	\end{equation}
	
	$L$: wave length
	
	$d$: water depth
	
	$H$: wave height
	
	$a$: wave amplitude
	
	$c$: celerity, wave speed
	
	$k$: wave number
	
	$\omega$,angular frequency
	
	wave number
	$ k=\frac{2\pi}{L}$ 
	
	$\omega=\frac{2\pi}{T}$
	
	$c=\frac{L}{T}=\frac{\omega}{k}$
	
	
	\subsubsection{VOF model theory}
	for detail, see ~\cite{fluent201617}
	
	
	
	

	
1D momentum >> dT (thrust/axial force), dM (torque/moment)
blade element theory (2D aerofoil lift/drag) >> dT, dM
- four Eqs, four unknown variable, a, a' , dT, d M
file:figures/bem-eqs.png

*** Blade modelling

Computer modelling has always been a compromise
 between three issues: 
the numerical description, 
computational resources and 
experimental validation~\cite{masters2015comparison}.

\begin{itemize}
	\item Blade element momentum theory (BEMT)
	\item Blade element actuator disk
	\item BEM-CFD 
	\item blade-resolved geometry (BRG)-CFD
	\item coastal area model
	\item Lab Experiments
\end{itemize}

\section{BEM}
~\cite{branlard2017blade


torque=moment

thrust= force in the negative free velocity direction
The thrust is the force in the streamwise direction resulting
from the pressure drop over the rotor, and is used to reduce the wind speed
from $ v_0 $Vo to $ u_1 $

 $ v_0 $: free stream velocity
 
 $ u_1 $: velocity in wake

\subsection{steady BEM}
BEM It was originally developed by Glauert ~\cite{glauert1935airplane}who combined blade element theory and momentum theory to analyse the airplane propeller performance .
\subsubsection{assumption}
\textbf{Blade element theory} assumes that blades can be divided into small elements that act independently of surrounding elements and operate aerodynamically as two-dimensional airfoils whose aerodynamic forces can be calculated based on the local flow conditions.

\textbf{the momentum theory,} assumes that the loss of pressure or momentum in the rotor plane is caused by the work done by the airflow passing through the rotor plane on the blade elements. Using the momentum theory, one can calculate the induced velocities from the momentum lost in the flow in the axial and tangential directions. These induced velocities affect the inflow in the rotor plane and therefore also affect the forces calculated by blade element theory. This coupling of two theories ties together blade element momentum theory and sets up an iterative process to determine the aerodynamic forces and also the induced velocities near the rotor

 blade geometry modelled :blade element momentum theory (BEMT)\\
 blade geometry resolved CFD :
 Moving Reference Frame, Sliding Mesh Model

*** sliding mesh

challenges in sliding mesh:
The moving boundary in the mesh may present difficulties, manifesting as a pressure discontinuity and greater computational costs

** Software
[[https://www.incompact3d.com/][Incompact3d]]

Fluent, CFX, Code\_Saturne

Models: LES, Unsteady RANS

Unsteady RANS is more common
~\cite{afgan2013turbulent} use Code\_Saturne and LES model to study tidal turbine model of Bahaj et al~\cite{bahaj2007power} .

* similarity of wind turbine
based on same Reynolds number

Froude-scaled or Reynolds scaled?
- Hard to satisfies both Fr and Re

- same TSR 
- same Re for Cp evaluation

- same cavitation number

Reynolds number similarity law
Re_c= V_rel C_{0.7R)/ \nu

when Re is above 1 million, Re effect can be ignored

caivtation number, \sigma
\sigma = 2(p-p_v)/(\rho V_rel^2)
- P : minimum pressure at 0.7R when blade is on 12 o'clock position
- p_v : vapour pressure of water
- V_rel : relative velocity seen by blade section at 0.7R

V_rel = sqrt(U^2 + (0.7\omega R)^2)， where U is free-stream water speed
， D is diameter of water, R is radius, \omega = 2\pi n

*Note:*
*TSR similarity and Re can not be satisfied at the same time*

- kinematic similarity :: the incidence angles of the wind
on each corresponding *rotor blade element* of the model and the prototype are the same

*Froude scaling*

Froude scaling laws are used for the underwater loads

A geometrically-scaled turbine generated a lower thrust and power
coefficient with a Froude-scaled wind velocity due to the
strong Reynolds scale effects on the flow.


** ref
Shi, W., Wang, D. Z., Atlar, M., & Wang, D. (2013). Similarity Laws and Model Test Approaches to Determine Hydrodynamic Performance of a Marine Turbine. Advanced Materials Research,, 665-672.

hydrodynamics similarity laws of marine propeller

Development of a Scaled-Down Floating Wind Turbine for Offshore Basin Testing, International Conference on Ocean, Offshore and Arctic Engineering

流体力学（第3版）作者：罗惕乾 江苏大学 主编 ISBN(书号)：978-7-111-06870-9 丛书名：普通高等教育“十五”规划教材
[[https://link.springer.com/content/pdf/10.1007%2F978-3-642-22938-1_7.pdf][Scaling wind turbines and rules of similarity ]]

ch7, 
R. Gasch and J. Twele (eds.), Wind Power Plants: Fundamentals, Design, Construction                 
and Operation, DOI 10.1007/978-3-642-22938-1_7, © Springer-Verlag Berlin Heidelberg 2012

Similarity Laws and Model Test Approaches to Determine Hydrodynamic Performance of A Marine Turbine


* results

Cp = TSR Cm
- Cm : torque coefficient










* Video
LES HA tidal turbine
https://www.youtube.com/watch?v=7zeoOv_wPxM
https://www.eng.ed.ac.uk/about/people/dr-angus-creech][https://www.youtube.com/watch?v=bAaAf_T-ygY
* Digest
file:Digest_paper.org

* Footnotes

[fn:Luis2009] 

